### ISSUE TITLE
Extending the library

### ISSUE THREAD

**Issue by serkin** [mongodb/mongo-php-library#110]
Hello
Thx for creating library for PHP7
I wanted to use this library but I can't find the way to extend it. Looks like it doesn't suppose to be extended. What if I want to use custom `Collection` class with custom methods? I can't extend it cause all properties are private. Should I fork it and customise for myself? Should I use it as it is? Maybe you can give me some ideas how to wrap it? Thx in advance.

**Comment by jmikola** [comment]
All of the database operations are split into their own classes under the `MongoDB\Operation` namespace if you'd like to re-use them for a new class. In that case, you'd just have to write the shim methods found our own Collection class to forward options over to each operation.

Alternatively, you can use [composition](http://www.marcotroisi.com/composition-over-inheritance/) to encapsulate the library's Collection class in your own and expose its methods as needed. Ultimately, I expect folks will either use our Database and Collection as-is or roll their own (which is why we split off the Operation classes for re-use).

**Comment by serkin** [comment]
Thank you!
