### ISSUE TITLE
Why can't you make it backward compatible with the legacy client?

### ISSUE THREAD

**Issue by marcinrosinski** [mongodb/mongo-php-library#123]
Most of the methods are pretty much backward compatible already, why not making all of them? e.g. adding `limit()`, `sort()`, traversable cursor, clearly big part of the work is already done to make it backward compatible why not make it 100% backward compatible then? 

Can't understand the logic here especially that previous plugin was really great and easy to use and resembled the way you query under mongo shell. Can you advise?

**Comment by jacqueswaller** [comment]
There was a pretty good article about the rationale behind scrapping the old driver, but I can't find it now. Eliminating the dual pre/post nature of cursors is IMO objectively a good thing, with the notable issue that every php script I've written previously no longer works.

But regardless of that, they already don't work. Just about everything has changed (class names, namespaces, all errors as exceptions, the explicitness of the interface like `operationOne` and `operationMany`, etc). So even if they still had `.sort()` and `.limit()` operations on cursors, you'd still be rewriting everything anyway.

**Comment by alcaeus** [comment]
I think you mean the blog posts @derickr made. Part 1 covers the [driver history](https://derickrethans.nl/new-drivers.html) while part 2 covers the [architecture of the new drivers](https://derickrethans.nl/new-drivers-part2.html) (plural since this affects both PHP and HHVM drivers.

There's also a good writeup by @jmikola about the [CRUD API](http://jmikola.net/blog/mongodb-crud-api/) in the new driver and library which explains why some of these changes (like removing `sort` and `limit` options from a cursor) have been made.

**Comment by marcinrosinski** [comment]
@jacqueswaller not sure how you code but if cursor and limit() and sort() would be still in place its just 1 line change our end - client initialisation, thats all.

@alcaeus can't find anything about reasoning behind deleting limit() and sort() under links you sent not to mention how cursor works now.

**Comment by jacqueswaller** [comment]
Perhaps I overstated when I said "rewrite everything". However, the way that projections are passed in is different now so I can assure you that migrating to the new driver it isn't a one line change.

Having said that, you can find/replace the projection into the new format relatively easily and update all your queries with one regex. The `sort` and `limit` are passed as query options just like the projection, so it's easy enough to make the change (although time consuming, as I didn't find a good way to automate that process).

**Comment by marcinrosinski** [comment]
@jacqueswaller exactly, that is my point - it isn't 1 line change with the current library but they are couple line of codes from being hence the question - why not make it backward compatible?

**Comment by jmikola** [comment]
In addition to the blog posts @alcaeus linked, [Designing the Next PHP and HHVM MongoDB Drivers](http://jmikola.net/blog/next-mongodb-php-driver/) is an older post that discusses some of the rationale as well.

> but they are "couple/few" line of codes from being 1 line change, hence the question

Adding `limit()` and `skip()` to the driver's Cursor class is not possible, due to removal of the pre- and post-executed nature that @jacqueswaller cited. The limit and skip need to be known at the time we execute the query, since the cursor is only going to be a Traversable for the results returned by the server. I'm not sure if you were under the impression that the new Cursor was not Traversable and required use of the `toArray()` method, but you can indeed iterate on it directly. We opted not to implement the Iterator methods, but you can wrap the cursor in one of the SPL iterator classes if you'd like direct access to those (e.g. `next()`, `current()`).

> Can't understand the logic here especially that previous plugin was really great and easy to use and resembled the way you query under mongo shell. Can you advise?

While the MongoDB shell is quiet convenient, it's implementation is also a jumble of APIs dating back many years. For BC reasons, the server team needs to continue supporting deprecated APIs; however, we saw no reason to do so in a brand new extension (essentially a major version bump from the old `ext-mongo` driver). Additionally, we now have [cross-driver specifications](https://github.com/mongodb/specifications), which didn't exist 5-6 years ago when many of the original drivers (and shell) were created.

I understand the API changes are an inconvenience, but I hope in time that folks come to see the benefit in the new specs we've implemented.

I would also suggest looking at @alcaeus' [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter) library if you need a quick bridge between the legacy and new API. The vast majority of the old API (including the dual nature of MongoCursor) is implemented there using our new extension, which means you can upgrade to PHP 7 and HHVM without rewriting too much of your app. AFAIK, there are just a few edge cases related to socket timeouts, connection exceptions, and `insert()` accepting array literals.
