### ISSUE TITLE
Question: how can I get cursor->count() in the new driver?

### ISSUE THREAD

**Issue by bjarneo** [mongodb/mongo-php-library#125]
In the old driver this was possible:
http://php.net/manual/en/mongocursor.count.php

Error message (since count doesn't exist)
Call to undefined method MongoDB\Driver\Cursor::count()

Simplified:
$collection = selectCollection(..);
$cursor = $collection->find(.. , ...);

$cursor->count()

What is the approach in this library?

**Comment by bjarneo** [comment]
Found my answer: https://github.com/mongodb/mongo-php-driver/issues/195#issuecomment-169405194

**Comment by bjarneo** [comment]
Actually it didn't quite give me the answer. I'm still not sure how I get the count. Do I need to iterate through the cursor and count how many items there is?

**Comment by bjarneo** [comment]
Found an implementation from another lib
https://github.com/alcaeus/mongo-php-adapter/blob/master/lib/Mongo/MongoCursor.php#L127

**Comment by alcaeus** [comment]
Oh god no. Please don't use that as an example on how to do it.

As stated in the mentioned ticket, the legacy implementation did some silly things (TM) regarding to cursor counts. With the new API there are two choices:
1. store all results in an array, then count them (giving you the number of results returned). You have to store them since the cursor can only be iterated once, not multiple times.
2. Run a separate count operation using the filter you want (this is necessary to replicate the `$foundOnly = false` behavior of the legacy driver).

**Comment by bjarneo** [comment]
I will follow your steps. Thanks for quick reply.

**Comment by bjarneo** [comment]
Update:
I did solve it by calling the collection with count. $collection->count(same_query_data)

**Comment by webdevilopers** [comment]
> Update:
> I did solve it by calling the collection with count. $collection->count(same_query_data)

The `count` method is deprecated since **1.4**:

https://github.com/mongodb/mongo-php-library/blob/master/src/Collection.php#L284-#L313

The `countDocuments` method can be used instead:

https://github.com/mongodb/mongo-php-library/blob/master/src/Collection.php#L315-#L342

Alternatively:

```php
echo count($cursor->toArray());
```
