### ISSUE TITLE
Collection doesn't have an update method

### ISSUE THREAD

**Issue by Athorcis** [mongodb/mongo-php-library#134]
Hello,
Though MongoDB\Operation\Update is implemented MongoDB\Collection doesn't have an update method which is the only way to do several replacements, i guess this is probably an oversight.

**Comment by alcaeus** [comment]
The `update` method from the old `MongoCollection` class has been split into `updateOne` and `updateMany`, both of which are implemented in `MongoDB\Collection`. There is also the `replaceOne` method which replaces calling `update` and passing it a document instead of atomic update operators.

**Comment by Athorcis** [comment]
Can I expect to see a `replaceMany` method implemented in the future?

**Comment by jmikola** [comment]
By design, MongoDB cannot replace multiple documents in a single `update`. See [this documentation](https://docs.mongodb.org/manual/reference/method/db.collection.update/#replace-a-document-entirely).

That said, you can issue multiple `replaceOne` operations in a single bulk write using `Collection::bulkWrite()`:

```
$collection->bulkWrite([
    ['replaceOne' => [['_id' => 1], ['x' => 11]]],
    ['replaceOne' => [['_id' => 2], ['_id' => 2, 'x' => 22], ['upsert' => true]]],
]);
```
