### ISSUE TITLE
Using BSONArray in usort

### ISSUE THREAD

**Issue by fdask** [mongodb/mongo-php-library#146]
I'm trying to pass an array from one of my mongo records into PHP's usort.   It's giving me the following error:  usort() expects parameter 1 to be array, object given.

The data I'm passing in is a BSONArray.   So I guess two things.. should BSONArray not implement something that would let me treat it like a regular array in functions like usort?    

Second, any tips for a quick workaround?  Can I somehow 'flatten' out the BSONArray object into a regular array?

Any help appreciated!

**Comment by jmikola** [comment]
Unfortunately, PHP doesn't provide any mechanism to allow any objects to satisfy typing requirements for arrays. [ArrayObject](http://php.net/arrayobject) is probably the closest thing we have, and BSONArray and BSONDocument both extend it.

The class has several sort methods (e.g. [uasort()](http://php.net/manual/en/arrayobject.uasort.php), [uksort](http://php.net/manual/en/arrayobject.uksort.php)) based on some of the standard array sort functions. Alternatively, you should be able to use [getArrayCopy()](http://php.net/manual/en/arrayobject.getarraycopy.php) or cast the BSONArray to an array (e.g. `(array) $bsonArray`) to obtain a basic PHP array. Note that since PHP's sort functions operate in-place and take their argument by reference, you'll need to store the converted array in a variable before being able to use it with something like [usort()](php.net/usort).
