### ISSUE TITLE
"ErrorException: Trying to get property of non-object"  while trying to access nonexisting field in BSONArray

### ISSUE THREAD

**Issue by Dwarfex** [mongodb/mongo-php-library#166]
If i have a valid BSON Array Object named $data i would access the fields in it via $data->id or $data->name for example.

How do i properly catch following the case: 
using
```
$data->description 
```
where "description" may or may not exist in the $data fields.
Currently calling this would lead to an ErrorException: Trying to get property of non-object
How would i f.e. just return "null" or "false" if the description field doesn't exist in my data.
I thought one big plus of using mongoDB would be the possibility for different structured data in one collection?

 
```
MongoDB\Model\BSONArray Object
(
    [storage:ArrayObject:private] => Array
        (
            [0] => MongoDB\Model\BSONDocument Object
                (
                    [storage:ArrayObject:private] => Array
                        (
                            [id] => 84
                            [enumber] => E 472 b
                            [name] => Milchsäureester von Mono- und Diglyceriden von Speisefettsäuren
                        )

                )

            [1] => MongoDB\Model\BSONDocument Object
                (
                    [storage:ArrayObject:private] => Array
                        (
                            [id] => 198
                            [enumber] => E 407
                            [name] => Carrageen
                            [description]=>TestText
                        )

                )

            [2] => MongoDB\Model\BSONDocument Object
                (
                    [storage:ArrayObject:private] => Array
                        (
                            [id] => 293
                            [enumber] => E 941
                            [name] => Stickstoff
                        )

                )

        )

)
```

**Comment by jmikola** [comment]
> Currently calling this would lead to an ErrorException: Trying to get property of non-object
How would i f.e. just return "null" or "false" if the description field doesn't exist in my data.
I thought one big plus of using mongoDB would be the possibility for different structured data in one collection?

To be fair, this issue is pertaining to PHP raising an exception for accessing an unknown field on an object. That's unrelated to MongoDB permitting you to have diverse document schemas within the same collection, which it does.

By default, the library converts BSON arrays and objects to [`MongoDB\Model\BSONArray`](https://github.com/mongodb/mongo-php-library/blob/9e443408328d7e28df3f02a1cefbd9e190a6c977/src/Model/BSONArray.php) and [`MongoDB\Model\BSONDocument`](https://github.com/mongodb/mongo-php-library/blob/9e443408328d7e28df3f02a1cefbd9e190a6c977/src/Model/BSONDocument.php) classes, respectively. These both extend PHP's [`ArrayObject`](http://php.net/arrayobject), which provides a relatively user-friendly API somewhere between `stdClass` objects (not very convenient) and PHP arrays (very convenient). As an aside, this is a compromise since we need to use _some_ class to ensure that we preserve the BSON types when shuffling data to/from the database.

For `BSONDocument`, we take an extra step and enable `ArrayObject`'s [`ARRAY_AS_PROPS`](http://php.net/manual/en/class.arrayobject.php#arrayobject.constants.array-as-props) flag by default, which allows you to use the property accessor (i.e. `->`) in addition to the always-on array accessor (i.e. `[]`). We also do this because the the underlying [mongodb extension](php.net/mongodb) returns documents as `stdClass` objects, where users would already need to use `->` to access things. Keeping this behavior in the library makes for a more consistent experience.

All that said, PHP still requires you to check that a property or offset exists before accessing it. `ArrayObject` supports such checking via its [`offsetExists()`](http://php.net/manual/en/arrayobject.offsetexists.php) method (part of the [`ArrayAccess` interface](http://php.net/manual/en/class.arrayaccess.php)).

For your example, the following should work:

```
$description = isset($data->description) ? $data->description : null;
```

If you're using PHP 7, you might prefer to use the [null coalesce operator](https://wiki.php.net/rfc/isset_ternary) (i.e. `??`) for brevity.

**Comment by Dwarfex** [comment]
I found my mistake - i used a foreach to go through the $data variable as $value and there tried to access $value->description - here the isset function would just cause the script to abort with the above result .i should have used $data->description - isset() works here as indented.

Thank you for your eyeopening answer - i'm a bit stressed because my cs thesis is due ;)

**Comment by lindelius** [comment]
As already mentioned, this is a general PHP "issue" and not specific to either MongoDB or this PHP library.

Don't be afraid to use the _error control operator_ when accessing fields that may or may not exist. If you expect the result to be of a specific type whether or not the field exists, just cast the result to the specific type and you will get the standard value for that type if the field does not exist.

```
$varOne = @$result->field; // returns the field value, or null if it doesn't exist
$varTwo = (int) @$result->field; // returns the field value as int, or 0 if it doesn't exist
```
