### ISSUE TITLE
[Feature Request] $collection->persist()

### ISSUE THREAD

**Issue by moderndeveloperllc** [mongodb/mongo-php-library#186]
With the addition of the `Persistable` class, there is the opportunity to provide an easy ODM-like function of `persist()` on `Collection` that would take either a single `Persistable`, `Serializable`, or an array of either. This would be basically be a `replaceOne()` on the `_id` if there is one, and `insertOne()` if the object has no `_id`. Not sure if this could just be an `upsert`ed `replaceOne()` (can you `replaceOne()` `upsert` with a blank filter array?)

**Comment by bjori** [comment]
Something like https://github.com/bjori/mongo-php-transistor ?

**Comment by moderndeveloperllc** [comment]
@bjori Yes. It would be interesting to look at the metrics for doing the extra work of figuring the `$set`s of an update vs just doing a full document replacement. I guess that would wind up dependent on the number of fields changed and the size of the document.

I would be interested in @jmikola's opinion of if this functionality belongs in a library like this, or a 3rd party repo like yours.

**Comment by jmikola** [comment]
This sounds quite a bit like the legacy driver's `save()` method, which we [purposefully removed](http://mongodb.github.io/mongo-php-library/upgrade-guide/#mongocollectionsave-removed).

A robust solution would do changeset calculation, as implemented in @bjori's Transistor library. In that library, `bsonSerialize()` returned a document consisting of update modifiers if invoked on an already-persisted document. We ultimately [broke its ability to do so](https://github.com/bjori/mongo-php-transistor/issues/9) when [PHPC-550](https://jira.mongodb.org/browse/PHPC-550) was resolved. `Persistable::bsonSerialize()` must now return a document suitable for storage (i.e. no update operators), since the `__pclass` field will always be injected at the top level.

> I would be interested in @jmikola's opinion of if this functionality belongs in a library like this, or a 3rd party repo like yours.

At the moment, I'd defer to a third-party repository. Composer packaging makes it much easier to split features across multiple packages and I'd prefer to keep this library (mostly) limited to essential functionality dictated by our cross-driver specifications. We can always pull in a feature later if it materializes into an essential feature.

**Comment by moderndeveloperllc** [comment]
Good to know.
