### ISSUE TITLE
No suitable servers found (`serverselectiontryonce` set): [connection error calling ismaster on 'x.x.x.x:xxxx']

### ISSUE THREAD

**Issue by ruansheng** [mongodb/mongo-php-library#201]
php7 normal running
php ext mongodb.so version 1.1.7
mongodb 2.6.x  server normal running
but , this error is random appear

**Comment by moderndeveloperllc** [comment]
@ruansheng I don't work for MongoDB, but I know they will ask you to provide your connection code. Can you paste your PHP code you use to connect to the database? Thanks.

**Comment by ruansheng** [comment]
@moderndeveloperllc 
I use mongo-php-library connect mongodb server,  php 7 +  mongodb.so + mongo server 2.4
running in the production environment
this error tips :  
    [15-Jun-2016 19:23:07 PRC] PHP Fatal error:  Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [connection error calling ismaster on '10.83.76.136:50020']
/mongodb/mongodb/src/Collection.php:435
Stack trace:
#0 /mongodb/mongodb/src/Collection.php(435): MongoDB\Driver\Manager->selectServer(Object(MongoDB\Driver\ReadPreference))

[https://github.com/mongodb/mongo-php-library/blob/master/src/Collection.php](url)    line 435

 Thanks.

**Comment by jmikola** [comment]
@ruansheng: I believe @moderndeveloperllc was suggesting you provide the code used to connect to the database as well (e.g. how you are constructing `MongoDB\Client`). The above exception simply means that the driver cannot connect to `10.83.76.136:50020`, which seems more indicative of a network connectivity issue than a driver bug.

I might also suggest capturing some logs via the [`mongodb.debug`](http://php.net/manual/en/mongodb.configuration.php) INI option (either to a file or "stderr"). That would tell us if anything unexpected is happening internally (within libmongoc).

**Comment by ruansheng** [comment]
before.  In the local environment cannot simulation appear . 
now . In the local environment  simulation this issue.

`
ini_set('error_reporting', E_ALL | E_STRICT); 
$options_base = ['connectTimeoutMS' => 1, 'socketTimeoutMS' => 10000];
$manager = new MongoDB\Driver\Manager("mongodb://localhost:33608/", $options_base);
$readPreference = $manager->getReadPreference();
$server = $manager->selectServer($readPreference);
`

`
PHP Fatal error:  Uncaught MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers found (`serverselectiontryonce` set): [connection error calling ismaster on 'localhost:33608'] in /root/mongobug.php:5
Stack trace:
#0 /root/mongobug.php(5): MongoDB\Driver\Manager->selectServer(Object(MongoDB\Driver\ReadPreference))
#1 {main}
  thrown in /root/mongobug.php on line 5
`

reason :  "connectTimeoutMS"  too small.

ours production environment is set 
`
$options_base = ['connectTimeoutMS' => 50, 'socketTimeoutMS' => 10000];
`
random appear this issue. perhaps I can by add "connectTimeoutMS" solve

**Comment by jmikola** [comment]
The exception is likely due to your connection timeout being too small. If you intend to customize this value, you'll want to ensure it's higher than the expected network latency between your app and database servers.


  timeout is going to work across a network (

**Comment by denbip** [comment]
@jmikola Hi. I'm getting the same error when I shut down one server from replicaSet. Debug log: 
`No suitable servers found (`serverselectiontryonce` set): [connection timeout calling ismaster on '192.168.212.144:27017'] [Failed connecting to '192.168.211.144:27017': Connection timed out] [connection timeout calling ismaster on '192.168.211.32:27017'] [connection timeout calling ismaster on '192.168.212.32:27017'] [connection timeout calling ismaster on '192.168.213.32:27017']`. 

In this example 192.168.211.144:27017 is shut down and all is ok when it is turn on

**Comment by jmikola** [comment]
@denbip: Although you have a similar exception message, the details of your situation differ quite a bit from this issue. The OP is dealing with a single connection timeout, while you appear have a replica set with one inaccessible node. In the future, please err on the side of opening a new issue instead of piling on to an existing thread. It's much easier to consolidate discussion after the fact than track multiple unrelated conversations in an existing thread.

You didn't specify what version of the extension you were using, but [1.1.9](https://github.com/mongodb/mongo-php-driver/releases/tag/1.1.9) addressed an issue related to replica set connections. When a single server in the URI host list was inaccessible (e.g. "Failed connecting to ...") communication to all other hosts would yield "connection timeout calling ismaster" errors. This issue is also resolved in the more recent 1.2.0 alpha releases.

If the issue persists after upgrading, please open a new issue on the [driver project](https://github.com/mongodb/mongo-php-driver) (connection logic does not involve the library).

@ruansheng: I'm going to close this out, since we haven't heard back in some time. I assume that adjusting the `connectTimeoutMS` option worked for you, but feel free to circle back if the issue hasn't been resolved.

**Comment by denbip** [comment]
Version 1.2.0alpha3 seems to work. Thanks

On Nov 18, 2016 19:25, "Jeremy Mikola" <notifications@github.com> wrote:

Closed #201 <https://github.com/mongodb/mongo-php-library/issues/201>.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mongodb/mongo-php-library/issues/201#event-864607650>,
or mute the thread
