### ISSUE TITLE
When save function is supported in Collection?

### ISSUE THREAD

**Issue by hongchangfirst** [mongodb/mongo-php-library#203]
I need a functionality that update and insert a document into mongodb.

I searched the collection class but didn't find the save function. I searched the code and didn't find similar functionality and I saw the documentation has 'save' design(https://github.com/mongodb/mongo-php-library/blob/master/docs/img/save-flowchart.png) three months ago. When do we support save function? And for now how can we implement this functionality?

**Comment by lindelius** [comment]
This is something you will have to create on your own. Depending on your use case and document structure you may want to use either `replaceOne()` or `updateOne()`, or maybe do a check to see if the current document that you're trying to save has the `_id` field set and then either `insertOne()`, `updateOne()`, or `replaceOne()`, depending on what sort of update it is. It really depends on the application, which is why the `save()` function hasn't -- and won't -- be implemented in this library.

**Comment by jmikola** [comment]
The [`save()` flowchart](https://github.com/mongodb/mongo-php-library/blob/master/docs/img/save-flowchart.png) you referenced is only used in the [Upgrade Guide](http://mongodb.github.io/mongo-php-library/upgrade-guide) section of the docs where we discuss its [removal](http://mongodb.github.io/mongo-php-library/upgrade-guide) from the library. In short, the `save()` method made it all too easy for new users to inadvertently overwrite their documents and we want to encourage explicitness.

**Comment by hongchangfirst** [comment]
I see, thanks.
