### ISSUE TITLE
Unrecognized parameter to $cond with '$project'

### ISSUE THREAD

**Issue by litan1106** [mongodb/mongo-php-library#208]
RuntimeException in Aggregate.php line 168:
Unrecognized parameter to $cond: $eq

Example Code: 

```
['$project' =>
    [
        '_id' => '$KeywordId',
        'AdGroup' => '$AdGroup',
        'Campaign' => '$Campaign',
        'Clicks' => '$Clicks',
        'Impressions' => '$Impressions',
        'Conversions' => '$Conversions',
        'Cost' => [ '$cond' => [ '$eq' => [ [ '$Clicks', 0 ] ], 1, 0 ] ],
        'AvgCost' => [ '$divide' => [ '$Cost', '$Clicks' ] ],
        'CTR' => [ '$divide' => [ '$Clicks', '$Impressions' ] ],
        'QualityScore' => '$QualityScore',
        'Keyword' => '$Keyword',
        'KeywordStatus' => '$KeywordStatus',
    ]
]
```

**Comment by lindelius** [comment]
It's because you messed up the array-brackets around the `$eq` operation a bit :)
The "Cost" projection should look like this:

```
'Cost' => [
    '$cond' => [ 
        [ '$eq' => [ '$Clicks', 0 ] ],
        1,
        0 
    ] 
],
```
instead of

```
'Cost' => [
    '$cond' => [ 
        '$eq' => [ [ '$Clicks', 0 ] ],
        1,
        0 
    ] 
],
```

**Comment by jmikola** [comment]
For reference:

 * https://docs.mongodb.com/manual/reference/operator/aggregation/cond/
 * https://docs.mongodb.com/manual/reference/operator/aggregation/eq/

Note that it may be more descriptive to use the if/then/else keys with `$cond` (available since 2.6) instead of the positional array syntax.

Also note that this issue is not related to the PHP driver or library, as it's a server error for a malformed query. In the future, please defer to one of the [community support channels](https://docs.mongodb.com/manual/support/#community-support) for such a topic.

**Comment by mandaputtra** [comment]
## Question
@jmikola @lindelius What are the `1` and `0` stand for in 

```
'Cost' => [
    '$cond' => [ 
        [ '$eq' => [ '$Clicks', 0 ] ],
        1,
        0 
    ] 
],
```

the last `1` and `0`?

**Comment by derickr** [comment]
The ``Cost`` field is set to: the first value (``1``) is used when the condition matches, and to the second value (``0``) when the condition does not match.
