### ISSUE TITLE
GridFS file uploads broken

### ISSUE THREAD

**Issue by jserle** [mongodb/mongo-php-library#210]
In the current master branch, all attempts to save files to GridFS are failing.

Here is the code we're using:

```
$manager = new \MongoDB\Driver\Manager($uri, $uriOptions, $driverOptions);
$bucket = new \MongoDB\GridFS\Bucket($manager, $settings['dbname']);
foreach ($_FILES as $file) {
    $stream = $bucket->openUploadStream($file['tmp_name']);
    $bucket->uploadFromStream($file['name'], $stream);
}
```

Inside the internal class method `WritableStream->uploadFromSream`, this code loop is run:

```
while ($data = $this->readChunk($source)) {
    $this->insertChunk($data);
}
```

This code triggers a fatal error because the resulting call to `fread` proxies to `StreamWrapper->stream_read` which calls undefined method `$this->stream->downloadNumBytes`.

It is clear from the code in `stream_read` that it's expecting `$this->stream` to be an instance of `ReadableStream` which does have the method `downloadNumBytes()`, but in the case of a file upload, it's an instance of `WritableStream`.

**Comment by jmikola** [comment]
`Bucket::openUploadStream()` returns a writable stream, while `Bucket::uploadFromStream()` accepts a readable stream. These methods are not intended to be used together.

#198

I would suggest opening `$file['tmp_name']` as a readable stream and then passing that resource to `Bucket::uploadFromStream()` to upload the file into GridFS. If you peak into the [`uploadFromStream()` implementation](https://github.com/mongodb/mongo-php-library/blob/07cbd47b0eca2587f91cdfbb843cc1bc0076ece7/src/GridFS/Bucket.php#L345), you'll see that we actually use `Bucket::openUploadStream()` to create a writable stream and pipe a readable stream's data into it using [`stream_copy_to_stream()`](http://php.net/manual/en/function.stream-copy-to-stream.php). This was a recent refactoring from #198.

Folks needing to upload an entire file/stream at a time will likely want to use `Bucket::uploadFromStream()`. `Bucket::openUploadStream()` should not be necessary unless you want to call `fwrite()` manually or otherwise need direct access to the writable stream.

I realize these the current API is not documented (beyond method doc blocks). We do intend to have a proper documentation of Bucket methods and a general GridFS tutorial in place before releasing 1.1.0. @schmalliso is currently migrating our existing docs over to a new format (similar to the MongoDB manual), so we're holding off on creating new content until that process is complete.

> This code triggers a fatal error because the resulting call to fread proxies to StreamWrapper->stream_read which calls undefined method $this->stream->downloadNumBytes.

I have an outstanding ticket to clean up error handling in the StreamWrapper class ([PHPLIB-199](https://jira.mongodb.org/browse/PHPLIB-199)). While that ticket pertains to exception handling, I will cover this case as well. The current code makes several assumptions about the internal stream's class and needs some correction to be more defensive.

Stream resources created by the Bucket methods will still be read-only or write-only, but I do need to correct the wrapper methods to ensure that we fail gracefully (or consistently with PHP's own file streams). A fatal error on a non-existent method call is certainly a bug to fix.

**Comment by denbip** [comment]
@jmikola Can you post an example of read/store files via GridFS?

**Comment by jmikola** [comment]
FYI: There is a fair bit of new documentation waiting to be merged in https://github.com/mongodb/mongo-php-library/pull/276. That includes many corrections from the original port from GitHub pages to the new format along with new content for the upcoming 1.1.0 release (e.g. GridFS, MongoDB 3.4 options). I'm hoping to get this merged and deployed in the coming week once I sort through some build issues with @schmalliso.

Here's a snippet from the GridFS tutorial:

> #### Uploading Files with Writable Streams
> 
> To upload a file to GridFS using a writable stream, you can either open a stream and write to it directly or write the entire contents of another readable stream to GridFS all at once.
> 
> To open an upload stream and write to it:
> 
> ```php
> <?php
> 
> $bucket = (new MongoDB\Client)->example->selectGridFSBucket();
> 
> $stream = $bucket->openUploadStream('my-file.txt');
> 
> $contents = file_get_contents('/path/to/my-file.txt');
> fwrite($stream, $contents);
> fclose($stream);
> ```
> 
> To upload the entire contents of a readable stream in one call:
> 
> ```php
> <?php
> 
> $bucket = (new MongoDB\Client)->example->selectGridFSBucket();
> 
> $file = fopen('/path/to/my-file.txt', 'rb');
> $bucket->uploadFromStream('my-file.txt', $file);
> ```
> 
> #### Downloading Files with Readable Streams
> 
> To download a file from GridFS using a readable stream, you can either open a stream and read from it directly or download the entire file all at once.
> 
> To open a download stream and read from it:
> 
> ```php
> <?php
> 
> // In practice, $fileId denotes the _id of an existing file in GridFS
> $fileId = new MongoDB\BSON\ObjectId;
> 
> $bucket = (new MongoDB\Client)->example->selectGridFSBucket();
> 
> $stream = $bucket->openDownloadStream($fileId);
> $contents = file_get_contents($stream);
> ```
> 
> To download the file all at once and write it to an writable stream:
> 
> ```php
> <?php
> 
> // In practice, $fileId denotes the _id of an existing file in GridFS
> $fileId = new MongoDB\BSON\ObjectId;
> 
> $bucket = (new MongoDB\Client)->example->selectGridFSBucket();
> 
> $file = fopen('/path/to/my-output-file.txt', 'wb');
> 
> $bucket->downloadToStream($fileId, $file);
> ```
> 
> #### Selecting Files by Filename and Revision
> 
> You can also download a file specified by filename and (optionally) revision number. Revision numbers are used to distinguish between files sharing the same `filename` metadata field, ordered by date of upload (i.e. the `uploadDate` metadata field). The revision option accepted by `openDownloadStreamByName()` and `downloadToStreamByName()` can be positive or negative.
> 
> A positive revision number may be used to select files in order of the oldest upload date. A revision of 0 would denote the file with the oldest upload date, a revision of 1 would denote the second oldest upload, and so on.> 
> 
> A negative revision may be used to select files in order of the most recent upload date. A revision of -1 would denote a file with the most recent upload date, a revision of -2 would denote the second most recent upload, and so on. The revision option defaults to -1 if not specified.> 
> 
> The following example downloads the contents of the oldest version of a particular file:
> 
> ```php
> <?php
> 
> $bucket = (new MongoDB\Client)->example->selectGridFSBucket();
> 
> $stream = $bucket->openDownloadStreamByName('my-file.txt', ['revision' => 0]);
> $contents = file_get_contents($stream);
> ```

**Comment by denbip** [comment]
@jmikola Thank you!

**Comment by jmikola** [comment]
The GridFS API is now included in the [library documentation](https://docs.mongodb.com/php-library/master/), so I'm closing this out. The GridFS tutorial I shared above is published on: https://docs.mongodb.com/php-library/master/tutorial/gridfs/.

**Comment by laupill** [comment]
Hello,
looking at the code for uploading the entire contents of a readable stream in one call, i am wondering why  you are not closing explicitely the stream after uploadFromStream. 
any reason for that?
regards.

**Comment by jmikola** [comment]
> i am wondering why you are not closing explicitely the stream after uploadFromStream.

PHP will close the stream when all references to it are dropped (i.e. variable goes out of scope), so I opted to omit `fclose()` from the examples for conciseness. See [Does PHP close the file after the file handler is garbage collected?](https://stackoverflow.com/a/12143588/162228) and, in the PHP manual, [Freeing resources](http://php.net/manual/en/language.types.resource.php#language.types.resource.self-destruct).
