### ISSUE TITLE
PHP7 and the old ['_id']->{'$id'}

### ISSUE THREAD

**Issue by Roycohen** [mongodb/mongo-php-library#218]
Hi There,

Is there a way to return and to query the database using the old fashion way.
In the old way MongoID Class returned ['_id']->{'$id'} and now MongoDB\BSON\ObjectID Class returns ['_id']->oid which is not good for me as I will need to refactor the entire client and server project as they are using the $id method.
Help will really be appreciated.

**Comment by jmikola** [comment]
> In the old way MongoID Class returned ['_id']->{'$id'} and now MongoDB\BSON\ObjectID Class returns ['_id']->oid which is not good for me as I will need to refactor the entire client and server project as they are using the $id method.

The legacy driver's [MongoId](http://php.net/mongoid) class had a public `$id` property, which you could access as `$value->{'$id'}`; however, the new [MongoDB\BSON\ObjectID](http://php.net/manual/en/class.mongodb-bson-objectid.php) class has no public properties. Are you referring to debug output?

Both the old and new driver return the 24-character hexadecimal string via `__toString()`, so I would suggest string casting if you need a consistent way to access the hash in both drivers.

If you absolutely need the legacy driver's API on PHP 7 (perhaps due to other API differences), I would suggest using the third-party [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter/) library until you can port over your project.

**Comment by Roycohen** [comment]
Hi @jmikola,

I've taken a look in to [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter/) library, but I still can't understand how I can use the old fashion $id.
So I need to use both Libraries? This with conjunction of the [mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter/) library?

So you guys not plan to support it with something like the driverOptions? Can this done easily with the driverOptions?

**Comment by jmikola** [comment]
[mongo-php-adapter](https://github.com/alcaeus/mongo-php-adapter/) implements the legacy driver API on top of this library and the extension; however, that does not mean you need to use this library directly.

If you are using the adapter library, you should get instances of [`MongoId`](https://github.com/alcaeus/mongo-php-adapter/blob/master/lib/Mongo/MongoId.php) back instead of `MongoDB\BSON\ObjectID`. The library implements `__get()` and returns the 24-character hexadecimal string when you access the property named `$id` (i.e. `$oid->{'$id'}`).

With [PHPC-640](https://jira.mongodb.org/browse/PHPC-640), we hope to allow users to wrap the extension's BSON types with custom classes. This is technically what @alcaeus is already doing in his adapter, but our feature will save a lot of manual work on his part. @derickr has started implementing this for HHVM in https://github.com/mongodb/mongo-hhvm-driver/pull/111, but it's still a ways off. When implemented, it will be possible through the type map settings (which is one of the `$driverOptions` in this library).

**Comment by Roycohen** [comment]
Great Thanks.
So it will be supported in the next versions.

**Comment by jmikola** [comment]
> So it will be supported in the next versions.

Custom type classes will be supported, but implementing such a thing would require considerably more code on your end than migrating your code to cast the ObjectID to a string. I don't understand the desire to access the `$id` property given that `__toString()` is a consistent API for both the legacy and new drivers.

**Comment by Roycohen** [comment]
There are lots of use cases. SPA applications. Rest API which returns Mongo Docs.
OK?

**Comment by jmikola** [comment]
I wasn't soliciting examples of applications. I just did not understand the issue with changing `$objectid->{'$id'}` to `(string) $objectid` when migrating an application from `ext-mongo` to `ext-mongodb`. That is a small change relative to the many other API differences between the old and new driver.

In any event, there is no specific action to take for this issue (apart from [PHPC-640](https://jira.mongodb.org/browse/PHPC-640)), so I think we can just close it out.
