### ISSUE TITLE
Extensive use of private methods instead of protected

### ISSUE THREAD

**Issue by rpavlicek** [mongodb/mongo-php-library#235]
From the source tree -- I'm curious of the choice to make non-public class methods private instead of protected in _**all**_ cases.

Being that its a library, its quite useful to extend it to meet our own needs. Working around classes that only use private methods (when it seems they should be protected) is difficult (i.e., we plan on implementing a way for TTL expiration to work on files & chunks for GridFS).

Was this intentional or just an oversight?

**Comment by sangio90** [comment]
I agree on changing methods and attributes access to protected. I would like to extend the Collection class to change some parts about Filters management but I cannot do that at the moment.

**Comment by jmikola** [comment]
The use of `private` throughout the library is intentional, as it minimizes the public API and forces us to consider specific extension points. This is the same design employed by [Symfony](http://fabien.potencier.org/pragmatism-over-theory-protected-vs-private.html), Doctrine, et al. Once a method or property is `public` or `protected`, it becomes an immutable part of the public API (at least until the next major version). Defaulting to `private` access errs on the side of being conservative in what we expose and allows us to consider opening up the API on a case-by-case basis. The most recent example of this was adding a `getManager()` accessor on the core classes.

Most methods in the Client, Database, and Collection classes delegate to Operation classes. The intention behind those classes was that users could work with them directly or through new methods. The methods on the core classes are only responsible for incorporating options from the local context (e.g. Collection's read preference) and selecting a server.

> I would like to extend the Collection class to change some parts about Filters management but I cannot do that at the moment.

@sangio90: I'd be interested to hear what you need access to in order to achieve this. Is it just a matter of accessing the internal Collection properties (in a better manner than `__debugInfo()`)?

> (i.e., we plan on implementing a way for TTL expiration to work on files & chunks for GridFS).

@rpavlicek: Admittedly, the GridFS Bucket was not implemented like the Collection and Database classes (with accessible operation classes). I'm not against the idea of adding more operations for various Bucket methods if requested. Opening up the StreamWrapper would be more challenging. Perhaps its context could allow options so that custom ReadableStream and WritableStream classes (implementing a new interface) could be provided.

**Comment by RobbieLePommie** [comment]
Thelack of exposure points is also creating blocks for me. One example is trying to wrap each executable call with some logging capabilities e.g. record how long it takes each execution/command to make. For other libraries (predis, PDO; memcache) it's a simple matter of extending the classes and wrapping calls to "parent" with the necessary timings. With this library there appears no way to grab hold of/extend the collection or the individual operations. Unless I'm missing a design point?

**Comment by jmikola** [comment]
> With this library there appears no way to grab hold of/extend the collection or the individual operations. 

@RobbieLePommie: How are private properties within the Client, Database, and Collection classes preventing you from wrapping the public API and invoking parent methods? None of those classes are final and any of the public methods can be overridden. Can you outline exactly what API you'd need to support your use case?

**Comment by lindelius** [comment]
```php
class WrapperCollection
{
    private $collection;

    public function __construct(Collection $collection)
    {
        $this->collection = $collection;
    }

    public function __call($method, $parameters)
    {
        // TODO: Stuffz

        return call_user_func_array([$this->collection, $method], $parameters);
    }
}

$collection = new WrappedCollection($collection);
$collection->insertOne(['test' => 'OK']);

```

**Comment by alcaeus** [comment]
@lindelius this is the way it should be, but it requires that interfaces are present:

```php
class WrappedCollection implements CollectionInterface
{
    private $collection;

    public function __construct(CollectionInterface $collection)
    {
        $this->collection = $collection;
    }

    public function __call($method, $parameters)
    {
        // TODO: Stuffz

        return call_user_func_array([$this->collection, $method], $parameters);
    }
}

$collection = new WrappedCollection($collection);
$collection->insertOne(['test' => 'OK']);
```

If there's no interface, this forces you to extend the original collection class. Otherwise you won't be able to pass it into classes expecting a collection object (that would be typehinted against `Collection` since there's no `CollectionInterface`).

**Comment by jmikola** [comment]
> but it requires that interfaces are present

On that note, I've purposefully avoided creating interfaces for Client, Database, and Collection as that would limit our ability to add new methods on the classes (since interfaces cannot be expanded without breaking BC). And while we could add methods to the classes alone without modifying the interface, that kind of defeats the point of the interface.

**Comment by petr-buchin** [comment]
@alcaeus , @lindelius that both implementation will not work. Since there is method `Collection::insertOne()` or `CollectionInterface::insertOne()`, method `__call()` will not be called.
To log all requests, you should wrap each method individually.

Another problem is that you cannot know, what actually will be sent to the server. 
For example, call to `Collection::findAndModify()` will change options to the format, acceptable by the server. That means that you can log only options, passed by the user, not options, that actually sent to the server.

In my alternative driver I solve this problem by having two extension points: 
1. Wrapper class for `MongoDB\Driver\Manager`. Extending this class allows intercept all requests just before they are sent to the MongoDB server - https://github.com/tequila/mongodb-driver-wrapper/blob/master/src/Manager.php
2. CommandBuilder - Collection, Database and Client objects use this object to create commands. Extending it allows to intercept **all** commands, log options, passed by the user and options that will be actually sent to the server: https://github.com/tequila/mongodb-php-lib/blob/refactoring-options/src/CommandBuilder.php#L43

I think this library also should have some simple extension points, but for now it's hard to implement such points, since each command has it's own class and is self-executable (`Executable::execute()`). By moving command execution logic to one place we will have ability to intercept all requests by extending one class/method.

**Comment by lindelius** [comment]
@alcaeus That's right. You would have to rewrite your application to use the `WrappedCollection` class. There's currently no way to magically inject a wrapper class in places where a `Collection` object is expected.

@petr-buchin I don't see why this wouldn't work if you just want to log the input etc, but you are right in that we still wouldn't be able to log the data that is sent to the database after all validation, parsing and what not. If one would wrap the `Collection` class like in the very basic example posted above, you would only be able to log the input to the various `Collection` methods, and not the information that is later passed to MongoDB.

**Comment by petr-buchin** [comment]
@lindelius , your solution **will** work, because your `WrappedCollection` does not extend `Collection` and does not have it's methods. But yes - if you want to use your `WrappedCollection`, you will need to rewrite all your code to accept `WrappedCollection` instead of `Collection`.
I think that's not a good soultion. 
Solution, described by @alcaeus,  solves the problem by using `CollectionInterface`. But method `__call()` will not work for that solution, because user will need explicitly implement interface methods. That means, if you want to extend `Collection`, you need to extend each method from it.
Also, `CollectionInterface` is not the best solution, as @jmikola described above.

Injection of some kind of "CommandBuilder", or "BulkWriteBuilder" does the trick. But this requires such architecture, when all commands are executed in one place, otherwise you would need to extend each command. For now architecture of this library does not allow using some "CommandBuilder", because all commands are self-executable.

**Comment by alcaeus** [comment]
@petr-buchin yes, the `__call` magic might not work, so you'd have to re-implement all methods and proxy them to the original class. Nonetheless, extending a class merely to wrap original calls is not the right choice - that's what the decorator pattern is for. One example where this is heavily used is the query builder in doctrine/mongodb ([example](https://github.com/doctrine/mongodb/blob/1c22128/lib/Doctrine/MongoDB/Query/Builder.php#L438..L442)).

Nonetheless, you could still extend the original collection class (which allows substitution in arguments) and decorate it at the same time:

```php
class WrappedCollection extends Collection
{
    private $collection;
    public function __construct(Collection $collection)
    {
        $this->collection = $collection;
    }

    public function doSomething()
    {
        // yadda yadda
       return $this->collection->doSomething();
    }

    public function doSomethingElse()
    {
        // yadda yadda
       return $this->collection->doSomethingElse();
    }
}
```

Much like in the original approach, you'd have to overwrite all methods where you want to add your custom code, but you can do it without an interface and without having knowledge of the private/protected API.

Also, the approach above obviously wouldn't work with `final` classes, but if you're using `final` without providing interfaces, you're an animal 😉

**Comment by RobbieLePommie** [comment]
@jmikola @lindelius @alcaeus  Thanks for the discussion

The `WrappedCollection` does work with __call, without need to rewrite any method (so in that respect, it's an easy solution) but there are several disadvantages.

Ideally I'd like to extend the base MongoDB\Client class for several reasons:
 a) It's a single collection point for the information; otherwise I'd need another object to pass to the `WrappedCollection` that tallies up the information for later reporting/handling
 b) It's an extra step to remember each time; being able to extend MongoDB\Client (and then extend the selectDB/Collection methods) will allow everything to "just happen".
 c) MongoDB\Client is already a wrapper-class-of-sorts for PHP's MongoDB, so we're wrapping a wrapper class which appears unnecessary overkill? 

For now I'll have a solution of wrapping both the MongoDB\Client and MongoDB\Collection and passing both, putting error reporting and logging in the Client and the actual data collection in Collection. Not sure it's the best way forward but thanks for the responses - it'll work. Cheers

**Comment by jmikola** [comment]
The 1.2.0 release introduced accessors for options on core classes ([PHPLIB-271](https://jira.mongodb.org/browse/PHPLIB-271), https://github.com/mongodb/mongo-php-library/pull/401), which I believe was the last stumbling block for extending our classes like Client, Database, and Collection.

> Another problem is that you cannot know, what actually will be sent to the server.
For example, call to Collection::findAndModify() will change options to the format, acceptable by the server. That means that you can log only options, passed by the user, not options, that actually sent to the server.

As for logging command sent to the MongoDB server, extension version 1.3.0 introduced an API for command monitoring. That all sits at the driver layer, so it is configured independently of the userland library. See [Application Performance Monitoring](http://php.net/manual/en/mongodb.tutorial.apm.php) in the PHP.net manual for more information on that.

Closing this as I don't believe there's anything left to do. Feel free to follow up here or open a new issue if I'm mistaken, though.
