### ISSUE TITLE
How to construct  a filter Array

### ISSUE THREAD

**Issue by rocketsryf** [mongodb/mongo-php-library#245]
LIKE:  a=1 and (b=2 or c=3) and (d=4 or e=5)
I use function find(),what is the filter to be?

**Comment by jmikola** [comment]
Since you have two OR clauses here, each of which would be expressed with an [`$or`](https://docs.mongodb.com/manual/reference/operator/query/or/) operator, you'll need to wrap them with an [`$and`](https://docs.mongodb.com/manual/reference/operator/query/and/) operator. This case where criteria keys would clobber each other is one of the few cases where `$and` is helpful. The query can be expressed in PHP as:

```
[
    'a' => 1,
    '$and' => [
        [
            '$or' => [
                ['b' => 2],
                ['c' => 3],
            ],
        ],
        [
            '$or' => [
                ['d' => 4],
                ['e' => 5],
            ],
        ],
    ],
]
```

For additional reference, see the [Query Documents](https://docs.mongodb.com/manual/tutorial/query-documents/) tutorial in the MongoDB Manual. I realize this particular example isn't discussed there, so I'd invite you to request that this example be added via the [Report a Problem](https://jira.mongodb.org/secure/CreateIssueDetails!init.jspa?pid=10380&issuetype=4&priority=4&summary=Comment+on%3a+%22tutorial%2Fquery-documents%2Etxt%22) link in the footer of that documentation page.

**Comment by rocketsryf** [comment]
Ok, I will try to use it in my project. Thank you very much! @jmikola
