### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-library#267]
Hi!
I'm writing my own MongoDB driver library for PHP, inspired by, and quite similar to this library:
https://github.com/tequila/mongodb-php-lib

I want to use classes BSONDocument and BSONArray from this library in my lib.
I copied this two classes to my library, and inserted a link to this lib:
https://github.com/tequila/mongodb-php-lib/blob/master/src/BSON/BSONDocument.php#L16

Am I doing this right? What should I do to not break the license rules?

Thanks in advance.

**Comment by jmikola** [comment]
This article outlines some steps for including code with an Apache 2 license: https://www.patrick-wied.at/blog/how-to-correctly-use-code-you-didnt-write

Since this project doesn't include a `NOTICE` file, you can disregard those bullets. Also, we don't have the license repeated in each source file, so your own comment that the class is copied from this library should suffice. I might add that the code is licensed under Apache 2.0 there, as well as bundling the Apache 2.0 license test in your own library.

Lastly, the license appears to require you to note any modifications to the original source. I imagine this doesn't apply now but may be relevant in the future if you alter them.

**Comment by petr-buchin** [comment]
Thank you very much!

**Comment by jmikola** [comment]
Quick update: license headers will be added to library source files in [PHPLIB-223](https://jira.mongodb.org/browse/PHPLIB-223).

**Comment by petr-buchin** [comment]
Thank you, but I decided to delete this two classes from my library and to use array type map by default: since database commands in my lib already use array type map (the same as in the legacy driver), this classes could be helpful only for Find queries and aggregation. Since typeMap can be set by the user, the end users of the library could implement similar classes if they need them. But I think in real-world application there is a rare case: class BSONDocument would be helpful for the case, when user wants to insert an empty PHP array to MongoDB as an object, not as a list: in such case, user most likely will have his own model class, implementing `\MongoDB\Driver\Persistable` interface.

But again, thank you very much for your time!

**Comment by jmikola** [comment]
> class BSONDocument would be helpful for the case, when user wants to insert an empty PHP array to MongoDB as an object, not as a list

For the record, that can easily be achieved with `(object) []` or `new stdClass`. The BSONDocument and BSONArray classes are mainly helpful for ensuring that BSON documents like `{ }` and `{ "0": "document-not-array" }` can be round-tripped between MongoDB and PHP.

:+1:
