### ISSUE TITLE
Projection as regular array

### ISSUE THREAD

**Issue by Roycohen** [mongodb/mongo-php-library#268]
Hello Guys,

I've just upgraded to the latest alpha release 1.2.0alpha3 and I think projection as regular array doesn't work anymore.
This doesn't work:
        $projection = array('name', 'type', 'hosts', 'pvpconf.children', 'customerId', 'status');
This works:
        $projection = array('name' => 1, 'type' => 1, 'hosts' => 1, 'pvpconf.children' => 1, 'customerId' => 1, 'status' => 1);

Might be that I'm missing something, but it used to work.

**Comment by jmikola** [comment]
In what version of the extension did the first projection work for you? When you say it is no longer working, are you receiving an error/exception or just finding that all fields except for `_id` are excluded?

I don't believe `['name', 'type', 'hosts', 'pvpconf.children', 'customerId', 'status']` was ever a valid projection in the current driver. It may have been supported in the legacy driver, but we only documented using the field names as keys in the projection array (see: [MongoCollection::find()](http://php.net/manual/en/mongocollection.find.php)).

In any event, your second example is what you should be using for a projection document (see: [server docs](https://docs.mongodb.com/v3.2/tutorial/project-fields-from-query-results/#projection-document)).

**Comment by Roycohen** [comment]
OK.
It worked with the master build.
It might be that the driver has supported it, because the issue started to occur when I started using the latest ALPHA driver.

If you want, I can send you a script to install the driver and test with it.

**Comment by jmikola** [comment]
> It worked with the master build
> ... the issue started to occur when I started using the latest ALPHA driver.

A commit hash would be more helpful than "master", which is ambiguous. The 1.2.0alpha3 tag (i.e. latest alpha) is currently behind the master commit.

It's possible that this is related to [PHPC-783](https://jira.mongodb.org/browse/PHPC-783), which was introduced in 1.2.0alpha3, as libmongoc now [checks that "projection" is a document](https://github.com/mongodb/mongo-c-driver/blob/1.5.0-rc0/src/mongoc/mongoc-cursor.c#L912) when preparing an [OP_QUERY](https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/#op-query) for server versions before 3.2. On 3.2+, the options should be sent as-is to the [find command](https://docs.mongodb.com/manual/reference/command/find/).

My previous question was unanswered:

> When you say it is no longer working, are you receiving an error/exception or just finding that all fields except for _id are excluded?

If you were executing the query on a pre-3.2 server, I expect you might see an error/exception with "invalid option projection, should be type document" before the driver even communicates with the server. 

A BSON array (e.g. `['name', 'type', 'hosts']`) would still not never have been a valid projection for the "mongodb" extension. Versions before 1.2.0alpha2 simply [validated that the "projection" option was an array or document and then prepared it as a BSON document](https://github.com/mongodb/mongo-php-driver/blob/1.2.0alpha2/php_phongo.c#L426). This mean that `['name', 'type', 'hosts']` was expressing the following projection: `{ "0": "name", "1": "type", "2": "hosts" }`.

> If you want, I can send you a script to install the driver and test with it.

If you have a stand-alone script that demonstrates a non-associative array (e.g. `['name', 'type', 'hosts']`) actually projecting fields whose names correspond to values within the array, I would be very interested to see that. It'd be best to have the script prepare the collection with freshly inserted documents before executing the query and dumping results. Also, please give me a tag (or commit hash) of the extension that should be used to reproduce the behavior.

**Comment by Roycohen** [comment]
I think it is working with every master I've tried. I need to retest it, and it would take me some time.
Though, I think it is related to the driver.

> When you say it is no longer working, are you receiving an error/exception or just finding that all fields except for _id are excluded?

I'm not getting error. I've just getting the _id of all the documents. Just like you thought.
My servers are 3.2+, so I don't know what happens in other versions.


And regarding the script, I'll try to create an example for you on our development environment.
Do you need Mongo Access, or just a script and you'll set up a mongo?

**Comment by jmikola** [comment]
> I think it is working with every master I've tried.

I have to reiterate how ambiguous "master" is, especially when you're referring to multiple "masters" as in this sentence. You could be referring to absolutely any commit in the driver's [master branch](https://github.com/mongodb/mongo-php-driver/commits/master). Please refer to specific commit hashes or tags in the future.

> I'm not getting error. I've just getting the _id of all the documents. Just like you thought. My servers are 3.2+, so I don't know what happens in other versions.

If the documents only contain the `_id` field, the driver is working exactly as designed and there is no bug here. The numerically indexed array you used as a projection was akin to specifying the document `{ "0": "name", "1": "type", "2": "hosts" }`. The server expects booleans or specially formed documents for fields; I'm assuming that a string like "name" may be interpreted as a truthy value, so you're actually asking MongoDB to project the "0", "1", "2", etc. fields. The `_id` field is included by default and those numeric fields do not exist in your collection documents, which is why you only see results with an `_id` field. This behavior is discussed more thoroughly in the [projection documentation](https://docs.mongodb.com/v3.2/tutorial/project-fields-from-query-results/).

> And regarding the script, I'll try to create an example for you on our development environment. Do you need Mongo Access, or just a script and you'll set up a mongo?

Access to your MongoDB environment is not an option. At most, you could provide a [dump](https://docs.mongodb.com/manual/reference/program/mongodump/) that we can load locally.

All of that said, the only bug in this issue would be if a projection of `['name', 'type', 'hosts']` resulted in the "name", "type", and "hosts" fields being included (i.e. `{ "name": 1, "type": 1, "hosts": 1 }`). If you eventually reproduce that behavior, feel free to follow-up in this issue and we can re-open it. Otherwise, the observed behavior in your original post is correct and expected.
