### ISSUE TITLE
What is the best alternative new way to get count from cursor instead of older $cursor->count() ?

### ISSUE THREAD

**Issue by vishalmelmatti** [mongodb/mongo-php-library#271]
Hi,

Cursor->count is not supported anymore, so what is the best and reliable way to get count from the cursor ?

**Comment by alcaeus** [comment]
I'll link to a previous [comment](https://github.com/mongodb/mongo-php-driver/issues/195#issuecomment-169405194) by @jmikola explaining the reasoning behind the change.

In a gist, instead of `$collection->find($filter)->count()` you'll do `$collection->count($filter)`. As explained in the comment above, it triggers the same logic (invoking the `count` command on the server) anyways.
