### ISSUE TITLE
No suitable servers found (`serverSelectionTryOnce` set): [socket timeout calling ismaster on 'xx.xx.xx.xx:27017']

### ISSUE THREAD

**Issue by xiaoxintiaoda** [mongodb/mongo-php-library#292]
php version:5.6.15
OS:Windows 7 x86
php mongodb ext version:1.2.0
php-mongo-library:   1.1.0-alpha1
mongodb server version: v3.2.11

connection code:
     const MONGODB_CONFIG = 'mongodb://uname:password@ip';
     protected static $mongodbDatebase = 'dbname';
     $option = [
            'authSource' => self::$mongodbDatebase,
            'connectTimeoutMS' => 3000,
            'socketTimeoutMS' => 10000,
     ];
     $mongodbClient = new Client(self::MONGODB_CONFIG,$option);

   this error is random appear,can't solution

**Comment by xiaoxintiaoda** [comment]
please help me, >_<

**Comment by jmikola** [comment]
If this exception appears sporadically and you database server is not actually offline, I expect it's caused by latency between your application and database servers. Since you're using a using a custom `connectTimeoutMS` option, you'll need to increase that.

I would generally suggest you avoid customizing the connection and socket timeouts unless absolutely necessary.

**Comment by xiaoxintiaoda** [comment]
I test in my server,It;s ok,So I close this issue first,thanks !!

**Comment by Rinkukumar** [comment]
'No suitable servers found (`serverSelectionTryOnce` set): 
i Am facing this error plz help me.
