### ISSUE TITLE
MongoDB\Driver\Manager can't found

### ISSUE THREAD

**Issue by xuboso** [mongodb/mongo-php-library#310]
I have install php mongodb extension on mac with `brew install php56-mongodb`,
and I have install php library with `composer require "mongodb/mongodb=^1.0.0"`,
but the MongoDB\Driver\Manager can't found.

```php
<?php
require 'vendor/autoload.php';
$manager = new MongoDB\Driver\Manager("mongodb://localhost:27017");
var_dump($manager);

?>
```

<img width="1026" alt="2016-12-12 00 27 22" src="https://cloud.githubusercontent.com/assets/8718559/21081438/ce2442da-c001-11e6-9b2e-da09bf4660a4.png">

Anyone can help me?

**Comment by jmikola** [comment]
What does `phpversion('mongodb') report when called from the same script where you claim `MongoDB\Driver\Manager` cannot be found? This sounds like an environment configuration issue and a discrepancy between INI configurations (e.g. loading the extension for a web SAPI but not CLI).

**Comment by xuboso** [comment]
@jmikola the `phpversion('mongodb')` result is 1.2.1 , same as the `phpinfo()` show

**Comment by jmikola** [comment]
Can you try running the following?

```
<?php 

var_dump(bin2hex(\MongoDB\BSON\fromPHP(['x'=>1])));
var_dump(class_exists('MongoDB\Driver\Manager'));
var_dump(new \MongoDB\Driver\Manager);
```

Expected output would be similar to:

```
string(24) "0c0000001078000100000000"
true
object(MongoDB\Driver\Manager)#1 (2) {
  ["uri"]=>
  string(20) "mongodb://127.0.0.1/"
  ["cluster"]=>
  array(0) {
  }
}
```

**Comment by xuboso** [comment]
all step is success except `new \MongoDB\Driver\Manager`, it results nginx 502 error.
![mongodb](https://cloud.githubusercontent.com/assets/8718559/21183014/ef62441a-c240-11e6-9198-8f537214d289.png)

when I excute it in **psysh**, it shows like this
<img width="468" alt="2016-12-14 21 06 06" src="https://cloud.githubusercontent.com/assets/8718559/21183108/51ac4468-c241-11e6-9c6b-8ac00f032519.png">

**Comment by jmikola** [comment]
The missing `_clock_gettime` symbol was previously reported in [PHPC-836](https://jira.mongodb.org/browse/PHPC-836) and it appears to be due to a packaging problem in specific versions of Mac OS (the function is reported in headers and detected during the build process, but the actual implementation is not found at runtime). Based on discussions in https://github.com/Homebrew/homebrew-php/issues/3737, folks have solved it by upgrading to Sierra with a new version of Xcode.

The same issue was also reported for various Homebrew packages in the [homebrew-core](https://github.com/Homebrew/homebrew-core/issues?q=is%3Aissue+label%3Aclock_gettime+is%3Aclosed) repository. I haven't come across a specific fix that we could utilize to work around this. If one exists, it likely needs to be added to [libbson](https://github.com/mongodb/libbson), which is our dependency that checks for this symbol.

> but the MongoDB\Driver\Manager can't found

In the future, please try to be more accurate when reporting the issue. Knowing that the extension crashed would have saved some back and forth on both of our parts.

**Comment by xuboso** [comment]
Thanks a lot, you solved my problem.
