### ISSUE TITLE
InvalidArgumentException in WritableStream.php line 105: MongoDB\BSON\UTCDateTime::__construct() expects exactly 1 parameter, 0 given

### ISSUE THREAD

**Issue by gatisdukurs** [mongodb/mongo-php-library#331]
https://github.com/mongodb/mongo-php-library/blob/master/src/GridFS/WritableStream.php#L105

http://php.net/manual/en/mongodb-bson-utcdatetime.construct.php

  - Removing mongodb/mongodb (1.1.0)
  - Installing mongodb/mongodb (1.1.1)

**Comment by jmikola** [comment]
The 1.1.x series of the PHP library [requires `ext-mongodb` 1.2.0+](https://github.com/mongodb/mongo-php-library/blob/1.1.1/composer.json#L14). Since extension version 1.2.0, the UTCDateTime constructor defaults to the current time if no arguments are provided (see: [PHPC-536](https://jira.mongodb.org/browse/PHPC-536)). If you are installing the library with Composer, it should have caught this when checking the [platform](https://getcomposer.org/doc/02-libraries.md#platform-packages) requirements. If you're installing manually, you'll need to ensure your extension is current when upgrading the PHP library.

Regardless, the [`UTCDateTime::__construct()`](http://php.net/manual/en/mongodb-bson-utcdatetime.construct.php) documentation needs to be updated for 1.2.0. I'll take care of that shortly.

**Comment by jmikola** [comment]
PHP.net documentation updated [here](http://svn.php.net/viewvc?view=revision&revision=341725). Changes should be live in a few days.
