### ISSUE TITLE
GridFS is not functional

### ISSUE THREAD

**Issue by wolfsoft** [mongodb/mongo-php-library#339]
Dear developers!

I've installed latest mongodb driver from pecl (mongodb 1.2.4 stable; git master repo was also tested) and php 7.0 (ubuntu xenial repository).

In function `openDownloadStreamByFile` declared in `Bucket.php` after call of:
```
        $context = stream_context_create([
            self::$streamWrapperProtocol => [
                'collectionWrapper' => $this->collectionWrapper,
                'file' => $file,
            ],
        ]);
```
$context is always NULL.

**Comment by jmikola** [comment]
This is a bit odd, as [`stream_context_create()`](https://github.com/php/php-src/blob/PHP-7.1.1/ext/standard/streamsfuncs.c#L1098) is only responsible for creating a data structure to encapsulate its two array arguments and return a corresponding resource.

Did you dump `$context` after this line to determine it was `null`?

I'd be curious what the following yields in your environment:

```php
$context = stream_context_create(['gridfs'=>['collectionWrapper' => 'foo', 'file' => 'bar']]);
var_dump($context);
var_dump(stream_context_get_options($context));
```

I would expect:

```
resource(155) of type (stream-context)
array(1) {
  ["gridfs"]=>
  array(2) {
    ["collectionWrapper"]=>
    string(3) "foo"
    ["file"]=>
    string(3) "bar"
  }
}
```

**Comment by wolfsoft** [comment]
Thank you for reply.

I've used `error_log(var_export($context, true))` instead of var_dump(). It prints NULL. var_dump() is not :)

Sorry, it seems that I can't download file from GridFS by another reason, but don't sure why.

Thank you anyway!

**Comment by jmikola** [comment]
I just realized there was an error in the [GridFS tutorial](https://docs.mongodb.com/php-library/master/tutorial/gridfs/), which suggested using `file_get_contents()` on the readable GridFS streams instead of `stream_get_contents()`. I've fixed that in https://github.com/mongodb/mongo-php-library/pull/340 and should have it deployed shortly.

Assuming you're experiencing a separate issue and have additional questions, feel free to follow up in a new issue and we'll try to sort it out.
