### ISSUE TITLE
how to use the command 'auth'?

### ISSUE THREAD

**Issue by TIGERB** [mongodb/mongo-php-library#357]
how to use the command 'auth'?

command in client as follows:

```
db.auth({user: username, pwd: password})
```

**Comment by moderndeveloperllc** [comment]
@TIGERB Are you looking to just be able to connect to your database with authentication? If so, you can just put the user/pass [into the connection string](https://docs.mongodb.com/manual/reference/connection-string/). Otherwise I _believe_ that you will need to use the [MongoDB\Driver\Command](http://php.net/manual/en/mongodb-driver-command.construct.php) class from the driver itself to execute arbitrary commands.

**Comment by TIGERB** [comment]
I got it, thank you~

**Comment by jmikola** [comment]
To clarify, the `mongodb` extension does not have any helper method to authenticate after a connection is created. The legacy `mongo` extension did such a method, but it doesn't play nice with persistent connections and required us to mark the socket(s) ineligible for re-use, lest we leak authentication credentials to a separate context (e.g. another `MongoClient`, a subsequent request).

Depending on the authentication mechanism, you may also need to run a _sequence_ of commands to complete the handshake (see: [authentication spec](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst)). As such, it is best to allow the driver to handle all of this in the connection string (or options array).

**Comment by TIGERB** [comment]
Thank you very much~
