### ISSUE TITLE
error [ ] php old version with Mongodb library

### ISSUE THREAD

**Issue by dimsidet** [mongodb/mongo-php-library#364]
( Note I must use this version , old version use Array and new version use [ ] , but I need use array , is not [ ] ) . thanks you

**Comment by jmikola** [comment]
This is discussed in the library's [BSON documentation](https://docs.mongodb.com/php-library/master/reference/bson/#emulating-the-legacy-driver).

**Comment by jmikola** [comment]
If you're referring to the new driver returning documents as objects instead of arrays, that is discussed in the library's [BSON documentation](https://docs.mongodb.com/php-library/master/reference/bson/#emulating-the-legacy-driver).

If you are asking about the library's use of short array syntax (`[]` instead of `array()`), the library depends on PHP 5.4+ as noted in [`composer.json`](https://github.com/mongodb/mongo-php-library/blob/1.1.2/composer.json#L13). There is no reason to support PHP 5.3, as the required `mongodb` extension requires PHP 5.4 (see dependencies in the footer of the [PECL package](https://pecl.php.net/package/mongodb)).

Cross-referencing with https://github.com/mongodb/mongo-php-library/issues/363, which you opened earlier.

**Comment by dimsidet** [comment]
Hi , it is meaning that we do not have solution ( use array() instead of [ ]  , no library for PHP version 5.3 ? )

**Comment by lindelius** [comment]
@dimsidet No, unfortunately not. You will have to upgrade PHP to version 5.4 (or higher) in order to use the MongoDB PHP driver, as well as this library.

**Comment by dimsidet** [comment]
thanks all for answer my question
