### ISSUE TITLE
Can't do multi update

### ISSUE THREAD

**Issue by marcinrosinski** [mongodb/mongo-php-library#376]
to reproduce

```
$client = new \MongoDB\Driver\Manager($connectionUri,$connectionOptions);
$bulk = new BulkWrite(['ordered' => true]);
$bulk->update(['foo'=>'bar'],['key'=>'val'],['multi'=>true]);
$client->executeBulkWrite('db.collection',$bulk);
```

will throw: `MongoDB\Driver\Exception\BulkWriteException: Cannot do an empty bulk write`

however when you change to `['multi'=>false]`

it works just fine.

How to do multi updates then?

PHP Version tested in: 7.0.9, Mac, Sierra installed via brew; Mongo Server version tested against: 3.4.0; driver version: 1.1.8; libmongoc version: 1.3.5

**Comment by jmikola** [comment]
Given the code you've shared, it looks like you're using the extension API directly and not the PHP library. In the future, please open extension-specific issues against the [mongo-php-driver](https://github.com/mongodb/mongo-php-driver) repository.

----

MongoDB does not support multi-document replacements. The update document would need to use atomic modifiers (e.g. `$set`) exclusively. This limitation is discussed in the shell documentation for [`db.collection.update()`](https://docs.mongodb.com/manual/reference/method/db.collection.update/#multi-parameter). We do not discuss this in the [PHP library documentation](https://docs.mongodb.com/php-library/) as we don't provide any API where it would be possible to execute this operation. The update CRUD methods are limited to `updateOne()`, `updateMany()`, and replaceOne()`. However, it would be helpful if we mentioned this limitation in the [`MongoDB\Driver\BulkWrite::update()`](http://php.net/manual/en/mongodb-driver-bulkwrite.update.php) documentation. I will follow up with a patch to mention that the `multi` option is incompatible with replacement documents.

Note that in the most recent extension version ([1.2.9](https://pecl.php.net/package/mongodb/1.2.9)), running your original code yields a more helpful exception at the time `BulkWrite::update()` is invoked:

> Uncaught MongoDB\Driver\Exception\InvalidArgumentException: Replacement document conflicts with true "multi" option

The exception you encountered in 1.1.8 originates from [mongoc-bulk-operation.c](https://github.com/mongodb/mongo-c-driver/blob/1.3.5/src/mongoc/mongoc-bulk-operation.c#L413). Looking at the implementation for [`BulkWrite::update()`](https://github.com/mongodb/mongo-php-driver/blob/1.1.8/src/MongoDB/BulkWrite.c#L159), the PHP extension invokes `mongoc_bulk_operation_update()`, which checks if the update document is a replacement document or uses atomic modifiers (see: [here](https://github.com/mongodb/mongo-c-driver/blob/1.3.5/src/mongoc/mongoc-bulk-operation.c#L290)). In the case of a replacement document, a warning is logged, which would only be visible if [`mongodb.debug`](http://php.net/manual/en/mongodb.configuration.php#ini.mongodb.debug) was enabled. Unfortunately, version 1.3.x of libmongoc did not support error reporting in its bulk write API, which is why feedback was deferred until you attempt to execute the bulk write.

This also means that if the BulkWrite included multiple write operations, invalid operations such as this one would be silently omitted and the BulkWrite might still execute successfully (assuming at least one other valid operation was added). This is obviously dangerous and one of the reasons we added improved error reporting in 1.2.

**Comment by jmikola** [comment]
PHP documentation updated in svn.php.net/viewvc?view=revision&revision=342593.
