### ISSUE TITLE
Speed up "\MongoDB\extract_id_from_inserted_document()" function

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-library#377]
For now function `\MongoDB\extract_id_from_inserted_document()` can extract id from the `\MongoDB\BSON\Serializable` document by calling it's method `bsonSerialize()`. I believe that many high-level tools (ODMs) will use `\MongoDB\BSON\Serializable` interface for their documents. Also it's a good idea to generate id at ODM level for object to have it's id after insertion, without reloading from DB. 
Therefore, i think this way of extracting id (unserializing document) will be used frequently.
But unserializing document just to get it's id is very inefficient.

I think of some kind of `MongoIdAwareInterface` or `DocumentInterface` which may look like follows:
```php
interface DocumentInterface
{
    public function getMongoId();
}
```

Having such an interface, function `\MongoDB\extract_id_from_inserted_document()` can be refactored as follows:

```php
function extract_id_from_inserted_document($document)
{
    if ($document instanceof DocumentInterface) {
        return $document->getMongoId();
    } elseif ($document instanceof Serializable) {
        return extract_id_from_inserted_document($document->bsonSerialize());
    }

    return is_array($document) ? $document['_id'] : $document->_id;
}
```

I made a benchmark of modified function and original function as follows:

```php
function timer(callable $callback, int $numberOfIterations)
{
    $start = microtime(true) * 1000;
    for ($i = 0; $i < $numberOfIterations; ++$i) {
        $callback();
    }

    return microtime(true) * 1000 - $start;
}

$blogPost = new BlogPost();
// ...fulfilling $blogPost with some data
$c1 = function() use ($blogPost) {
    return extract_id_from_inserted_document($blogPost);
};
$c2 = function () use ($blogPost) {
    return extract_id_from_inserted_document_modified($blogPost);
};

echo sprintf('Original function: %g ms.', timer($c1, 100000)), PHP_EOL;
echo sprintf('Modified function: %g ms.', timer($c2, 100000)), PHP_EOL;
```
`BlogPost` is a pretty complex class I wrote for this test. It implements `MongoDB\BSON\Serializable` and `DocumentInterface`.
The output on my MacBook is:
```
Original function: 102.495 ms.
Modified function: 13.8369 ms.
```

@jmikola , what are you think? If you agree with idea of having some `DocumentInterface`, I would be happy to create MR.

**Comment by jmikola** [comment]
Thanks for putting the effort into benchmarking. As mentioned in the source comments for `extract_id_from_inserted_document()` was only necessary because the extension lacked logic to always return the `_id` field from `BulkWrite::insert()` (see: [PHPC-382](https://jira.mongodb.org/browse/PHPC-382) and [PHPC-471](https://jira.mongodb.org/browse/PHPC-471)). I was finally able to address that with https://github.com/mongodb/mongo-php-driver/pull/587, which will be included in 1.3.0.

Rather than introduce a new interface, I think we can remove `extract_id_from_inserted_document()` entirely and bump the extension dependency to 1.3.0 in the forthcoming 1.2.0 tag. I will attempt to circle back next week about release scheduling once I have time to discuss that with @derickr. We've both been pulled into non-driver projects, which is why there has been little development activity on the extension/library recently.

**Comment by petr-buchin** [comment]
@jmikola , thank you for pointing that out, it's great that this issue is fixed in extension. Looking forward for 1.2 :)

**Comment by jmikola** [comment]
FYI: We moved several tickets out of the [1.3.0 milestone](https://jira.mongodb.org/browse/PHPC/fixforversion/17597/) this morning, which leaves us with <10 issues for a release.
