### ISSUE TITLE
Symfony integration

### ISSUE THREAD

**Issue by petr-buchin** [mongodb/mongo-php-library#383]
I'm writing an [ODM](https://github.com/tequila/mongodb-odm) for MongoDB and PHP7. 
Initially it was based on my own high-level driver, which was an alternative to this library, but recently I decided to move an ODM to this driver. Before that, I have written a [bundle](https://github.com/tequila/mongodb-odm-bundle) for ODM integration with Symfony framework. 
Currently, when ODM is based on this lib, I have to rewrite a Symfony bundle, but I believe an integration of Mongo PHP Library with Symfony framework should reside in a separate bundle. 

I understand that it's not a subject to discuss **here**, but I also know that some of Mongo PHP Library core developers are also contributors of Doctrine MongoDB ODM and other open-source PHP projects (for example @jmikola). Maybe you can point me to some existing bundle, that integrates this library with the Symfony framework and can be recommended by the core developers of this library?

After googling I found this:
https://github.com/facile-it/mongodb-bundle

But the configuration provided in README does not seem nice, and I doubt about the quality of this bundle.

Maybe you guys have plans to write such a bundle?
I am asking this to know, whether I should create bundle for integration of this library with Symfony by myself, or better to wait for "official" bundle.

Anyway, thanks in advance!

**Comment by Algatux** [comment]
@petr-buchin Hi! I'am one of the mantainers of the 'facile-it/mongodb-bundle' if you have any ideas to improve the bundle you are welcome aboard for contribution. In any case I please you to create an issue on that repository about your doubts. Thx a lot and sorry for the OT

**Comment by jmikola** [comment]
@petr-buchin: I could have sworn that I had written a reply to this a few weeks ago when I first saw the thread, but it must have just been a draft copy. Sorry for the delayed reply.

> Maybe you guys have plans to write such a bundle? I am asking this to know, whether I should create bundle for integration of this library with Symfony by myself, or better to wait for "official" bundle.

We haven't had any internal discussions about creating framework-specific modules for the library. Given the maintenance overhead of each integration (if we start with Symfony, other frameworks will surely be requested), I think this is something we'd rather encourage community members to develop organically.

Doctrine ODM 2.0 will end up using `ext-mongodb` and this library, so I expect its Symfony bundle and Zend Framework module will provide some integration. Since ODM 2.0 will also do away with Doctrine MongoDB, I think we can reasonably expect that those modules will end up exposing the library's client as a service (possibly usable without configuring the rest of the ODM). This is something we'll have to brainstorm with @alcaeus and @malarzm.

That said, my original draft reply was going to suggest reaching out to @Algatux and the other maintainers to express your concerns and try to improve the existing bundle. Assuming collaboration is possible, I think the community would be better served.

Either way, it would be worthwhile to have any actively supported integrations added to the [PHP Libraries, Frameworks and Tools](https://docs.mongodb.com/ecosystem/drivers/php-libraries/) page in the MongoDB manual (any objections, @Algatux?). @petr-buchin: I might have suggested that in an older thread when you first mentioned Tequila ODM and IIRC you wanted to wait until it was more stable.

**Comment by Algatux** [comment]
@jmikola we would be glad to be added inside the index, and as said in my previous reply to @petr-buchin we are always excited when someone opens a pr on our repositories.

**Comment by jmikola** [comment]
Closing this, as [PHP Libraries, Frameworks, and Tools](https://docs.mongodb.com/ecosystem/drivers/php-libraries/) tracks community projects.
