### ISSUE TITLE
Cursor not found in GridFS/StreamWrapper.php

### ISSUE THREAD

**Issue by fastmanu** [mongodb/mongo-php-library#387]
Is there a way to pass _nocursorTimout_ option (like on the cursor object) while getting a download stream from a gridfs bucket ? Asking this because i faced following error today, that makes me think about a _cursor timeout_ : 
`Warning: MongoDB\Driver\Exception\RuntimeException: Cursor not found, cursor id: 245969474954 in /code/vendor/mongodb/mongodb/src/GridFS/StreamWrapper.php on line 134
`

Here's the code that triggered the exception : 
```
$grid = $con->dbbame->selectGridFSBucket();
$id_file = new MongoDB\BSON\ObjectID($id_file);
return $grid->openDownloadStream($id_file);
```

returned ressource is then used in fgetcsv...

**Comment by jmikola** [comment]
Per [Closure of Inactive Cursors](https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/#closure-of-inactive-cursors) in the MongoDB manual, the server closes a cursor after 10 minutes of inactivity. In this case, "activity" will be the initial query and any subsequent `getMore` operations to return additional batches of documents from the `fs.chunks` collection. Per [Cursor Batches](https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/#cursor-batches), the first batch defaults to 101 documents and subsequent batches may be up to 16MB in size.

Since the PHP library keeps a cursor for `fs.chunks` in the stream object, it could become inactive if you did not read 16MB worth of data from the stream within 10 minutes. Can you confirm whether your code may have satisfied that condition while using `fgetcsv()` to read the GridFS file? If so, this seems a like a legitimate use case we should address in the [GridFS specification](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst) by allowing the `openDownloadStream()` and related methods to support a `noCursorTimeout` option.

The specification currently only supports a [`noCursorTimeout` option on the `Bucket::find()` method](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#generic-find-on-files-collection), which queries the `fs.files` collection and is unrelated to reading the GridFS file stream.

**Comment by fastmanu** [comment]
"while fgetcsv" was satisified during 18 000 csv lines, it then started throwing some errors...

here is a code snippet, where `$this->getFile()` refers to the code previously mentionned : 

```
if (($handle = $this->getFile($id_file)) !== FALSE) {
			
	// loop through the file line-by-line
	while(($data = fgetcsv($handle, 2000, $delimiter, $enclosure)) !== false) {
		[ultra crazy stuff like inserts && updates]
	}
}
```

**Comment by jmikola** [comment]
> "while fgetcsv" was satisified during 18 000 csv lines, it then started throwing some errors...

Is it likely that more than ten minutes elapsed between the time the `while` loop began and the first "Cursor not found" exception was thrown?

Without knowing the contents of the GridFS file being read, it's hard to saw how 18,000 CVS lines translates into megabytes and batches on the `fs.chunks` cursor. Can you estimate how many megabytes would have been read between the first `while` iteration and the "Cursor not found" exception?

I'm trying to establish whether it's reasonable that you actually hit the cursor inactivity limit, which would make a strong case for supporting a `noCursorTimeout` option for the stream cursors. That said, getting a "Cursor not found" exception under some other circumstances (e.g. iterating for only 90 seconds) would hint at a bug of some sort.

**Comment by jmikola** [comment]
Thanks for confirming. This should be enough to conclude there's no bug and this is just a feature request. I'll follow up once I have more feedback from the other driver developers about how we can address this in the specification.

If this is currently blocking your work and you're willing to modify the library directly, modifying [`MongoDB\GridFS\CollectionWrapper::findChunksByFileId()`](https://github.com/mongodb/mongo-php-library/blob/1.1.2/src/GridFS/CollectionWrapper.php#L96) to specify the `noCursorTimeout` option on the internal cursor should work around the issue.

**Comment by fastmanu** [comment]
No worries, sorry for having filled the issue as "bug" since it wasn't one. Thanks for your help Jeremy ;)

**Comment by jmikola** [comment]
No worries. Our internal spec tickets in JIRA are private, so I've opened [PHPLIB-274](https://jira.mongodb.org/browse/PHPLIB-274) as a public tracking ticket. Feel free to follow that for updates.
