### ISSUE TITLE
Easier way to return array as default

### ISSUE THREAD

**Issue by vlechemin** [mongodb/mongo-php-library#39]
I'm trying to use this library in a project who uses the old driver.
But now the default behavior is to return objects from queries.
The only way I found was to make a wrapper around Collection and to specify for each operation (find, findOne, aggregate...) the type map.
Is there a better way to do this? Do you plan having default options for this kind of use case? (inherit from database/client, similar to read preference)
Thanks!

**Comment by jmikola** [comment]
Thanks for the feedback! We've actually been tracking this in [PHPLIB-74](https://jira.mongodb.org/browse/PHPLIB-74) and hope to have it resolved before the 1.0.0 release.

Supporting a type map option at the Client, Database, and Collection level is definitely feasible, and we'd also like to provide a class implementing [ArrayAccess](http://php.net/arrayaccess) to use by default (instead of stdClass). We definitely don't want to encourage regular PHP arrays, since those are lossy (we have no way of knowing if `[0 => 'foo']` is really an array or an object when converting back to BSON); however, you'd certainly be allowed to specify an array in your own type map.

**Comment by vlechemin** [comment]
Thank you, that's great news. The class implementing ArrayAccess would be the perfect transition. Also, I'm not sure if it is a type map feature, but is it possible to allow a custom class for ObjectID to implement the JsonSerializable interface or add a public property to the class ObjectID (it used to be $id in the old driver) so the json_encode function does not return an empty object.

**Comment by bjori** [comment]
@vlechemin You can use BSON\toJSON() for that

```php
    $oid = new MongoDB\BSON\ObjectID();
    $bson = MongoDB\BSON\fromPHP(array("oid" => $oid));
    $json = MongoDB\BSON\toJSON($bson);
    var_dump($json);
```

    string(51) "{ "oid" : { "$oid" : "56213136bd21b96081103f11" } }"

I thought we had a ticket for going from PHP to (e)JSON but I cannot find it at the moment.
The intention was that you should be able to encode the BSON objects (such as ObjectID) using json_encode().

Its not going to make it into 1.0.0 though

**Comment by bjori** [comment]
See https://jira.mongodb.org/browse/PHPC-459

**Comment by vlechemin** [comment]
Thanks for the temporary solution and the ticket, I will be waiting for 1.1

**Comment by jmikola** [comment]
On a related note, [1.0.0-beta2](https://github.com/mongodb/mongo-php-library/releases/tag/1.0.0-beta2) of the library includes a new top-level `typeMap` option to centrally control BSON unserialization throughout the library.

**Comment by jmikola** [comment]
https://github.com/mongodb/mongo-php-library/pull/78 has now been merged, which means ArrayObject instances are being returned by default for BSON arrays and documents.
