### ISSUE TITLE
 throw new InvalidArgumentException('$pipeline is empty');

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-library#398]
why is an exception thrown for an empty pipeline? Like db.test.aggregate([])?

db.test.aggregate([]) works fine directly in mongo

See https://github.com/mongodb/mongo-php-library/blob/master/src/Operation/Aggregate.php#L115

**Comment by 719media** [comment]
Sorry, one more addition, in the console:
`db.test.aggregate()`
is also valid, so perhaps the PHP method should have default array parameter:
`public function __construct($databaseName, $collectionName, array $pipeline = [], array $options = [])`
as well

Thanks

**Comment by jmikola** [comment]
We'll take a look at this and contemplate a change for 1.2.0. I had some mental recollection that this was due to earlier versions of the [CRUD specification](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst), which also prohibits `bulkWrite()` from being called with no operations; however, I wasn't able to find specific mention of the aggregate pipeline. The non-empty pipeline requirement is also inconsistent across various language drivers (PHP isn't the only one with this behavior, but many others do allow empty pipelines).

**Comment by jmikola** [comment]
Tracking in [PHPLIB-281](https://jira.mongodb.org/browse/PHPLIB-281).
