### ISSUE TITLE
Question regarding result

### ISSUE THREAD

**Issue by 719media** [mongodb/mongo-php-library#409]
Hello

Can you tell me if it is possible to get any sort of "WriteResult" object out of a call to findOneAndUpdate? Or perhaps some other method to achieve the below use case?

The use case here is wanting to get both the "new" document back as a response from findOneAndUpdate, and information to determine if the document was modified or not (e.g. the findOneAndUpdate() call could have just $set a value to a field that already had that same value, which should result in a nModified of 0).

If this is not possible, it is a limitation of this library? Or mongo-php-driver? Or mongo itself? I am thinking it is mongo itself, since I do not see a way to get any sort of result out of https://docs.mongodb.com/manual/reference/method/db.collection.findOneAndUpdate/

Thank you for your assistance.

**Comment by jmikola** [comment]
The [`MongoDB\Driver\WriteResult`](http://php.net/manual/en/class.mongodb-driver-writeresult.php) class is specific to the basic insert, update, and delete operations executed through [`MongoDB\Driver\BulkWrite`](http://php.net/manual/en/class.mongodb-driver-bulkwrite.php). The MongoDB server does not report that information for other commands that write. Other write commands may return different information on a case-by-case basis.

The [`findAndModify`](https://docs.mongodb.com/master/reference/command/findAndModify/) command does include a [`lastErrorObject`](https://docs.mongodb.com/master/reference/command/findAndModify/#findandmodify-lasterrorobject) field in its response, but it may not be useful for your desired purpose. Consider the following shell example:

```
> db.foo.drop()
true
> db.runCommand({findAndModify:"foo",query:{x:1},update:{$set:{x:2}},upsert:true})
{
	"lastErrorObject" : {
		"updatedExisting" : false,
		"n" : 1,
		"upserted" : ObjectId("59bc4665dd930c84860c3c6c")
	},
	"value" : null,
	"ok" : 1
}
```

Starting with an empty collection, we attempt to find and modify a document that doesn't exist. We specify the `upsert` option, so a new document is created. The ID of that document is reported in `upserted` and `updatedExisting` is false because we didn't modify an existing document. `n` is not documented, but I believe it is just reporting the number of documents affected (logically, only 0 or 1 should be possible).

Note that `value` is `null` because we didn't specify the `new` option. Since the document didn't exist, the its pre-modified state is `null`. If `new` was true, `value` would contain the entire upserted document (including the generated ID).

```
> db.runCommand({findAndModify:"foo",new:true,query:{x:2},update:{$set:{x:3}}})
{
	"lastErrorObject" : {
		"updatedExisting" : true,
		"n" : 1
	},
	"value" : {
		"_id" : ObjectId("59bc4665dd930c84860c3c6c"),
		"x" : 3
	},
	"ok" : 1
}
```

We then match the document we just upserted and modify it. The post-modified state is returned and `lastErrorObject` tells us that we did modify a document.

```
> db.runCommand({findAndModify:"foo",new:true,query:{x:3},update:{$set:{x:3}}})
{
	"lastErrorObject" : {
		"updatedExisting" : true,
		"n" : 1
	},
	"value" : {
		"_id" : ObjectId("59bc4665dd930c84860c3c6c"),
		"x" : 3
	},
	"ok" : 1
}
```

In this example, we match the same document but our `update` option doesn't actually result in any modifications. Therefore, `lastErrorObject` is not as useful as the WriteResult returned for an update operation:

```
> db.foo.update({x:3},{$set:{x:3}})
WriteResult({ "nMatched" : 1, "nUpserted" : 0, "nModified" : 0 })
```

**Comment by 719media** [comment]
Thank you very much for the detailed response. Unfortunately, that does not help my use case, but your explanation was helpful in understanding more about the internals of Mongo. The use case I have is to specifically tell if the document was modified or not so that I can create change log records (without having to do additional queries that also are no longer "atomic"). Regardless, I appreciate your time in answering my question. Thanks!

**Comment by jmikola** [comment]
You're most welcome. I didn't think that `lastErrorObject` addressed your needs, but I thought it best to walk through it so you understood its shortcomings.

> so that I can create change log records

On that note, you may be interested by an upcoming feature in MongoDB 3.6: [Change Streams](https://github.com/mongodb/specifications/blob/master/source/change-streams.rst). These will be implemented as tailable cursors, which you'll be able to both resume and mix with aggregation pipelines. The API for change streams should end up in future driver releases the complement 3.6.
