### ISSUE TITLE
Help with number of concurrent connections

### ISSUE THREAD

**Issue by closca** [mongodb/mongo-php-library#420]
Hi,
I got an on Mongo Atlas an M10 which has a limit of 350 concurrent connections.
Got 2 PHP servers which are configured for high traffic. 
Every time I have a request (from the same client) into my PHP app, the mongo driver is opening a new connection to Mongo and remains open.
How can I set the max number of concurrent connections, and why is not reusing old connection?

**Comment by jmikola** [comment]
> How can I set the max number of concurrent connections, and why is not reusing old connection?

The PHP driver is reusing connections within each worker process (according to [Connection Handling](http://php.net/manual/en/mongodb.connection-handling.php)). After serving a request, the connection remains persisted to be reused by the next request served by that worker.

If you're reaching Atlas' connection limit, I expect your application server deployment has more than 350 active PHP workers. If that is not the case and you have far fewer than 350 workers, I expect your application may be varying its constructor arguments to `MongoDB\Driver\Manager` (as discussed in the connection handling docs, those arguments are used as a key to persist and reuse connections).

Please see my response in https://github.com/mongodb/mongo-php-driver/issues/662#issuecomment-338003969, which goes into greater detail about the driver's connection handling.

**Comment by closca** [comment]
Thanks @jmikola 
My application is load balanced in multiple servers.
Each server has much more than 350.
Can I configure the number of connections to not be dependent on the number of php workers?


Thanks,
Costel.

**Comment by jmikola** [comment]
> Can I configure the number of connections to not be dependent on the number of php workers?

The behavior described on [Connection Handling](http://php.net/manual/en/mongodb.connection-handling.php) is not configurable. Since we cannot share anything across PHP worker processes, the driver is being as efficient as it can in the current situation by only opening single connections to each database server (this is related to why the PHP driver does not implement connection pooling, as multiple connections sitting in a pool would only consume more resources).

The related issue I linked in my last post does discuss several workarounds (e.g. using a community-developed proxy, mongos), but I'm not sure those are applicable if you're using Atlas. The only relevant solution may be to either limit the number of workers, or restrict the amount of workers that actually open database connections.

**Comment by closca** [comment]
Thank you @jmikola
