### ISSUE TITLE
MongoDB 3.6 arrayFilters support

### ISSUE THREAD

**Issue by H-Max** [mongodb/mongo-php-library#430]
Hey,

I have been trying the new functionnalities of MongoDB 3.6 with the PHP driver and this library, and it appears that the arrayFilters in the new update methods is not supported.

I used the example in the documentation to test it out: https://docs.mongodb.com/master/reference/operator/update/positional-all/#update-nested-arrays-in-conjunction-with-identifier

Error is:
`Fatal error: Uncaught exception 'MongoDB\Driver\Exception\BulkWriteException' with message 'No array filter found for identifier 'score' in path 'grades.$[].questions.$[score]'' in ....`

Note: this may be related to the underlying MongoDB Driver rather than the library.
Note 2: I tried running the same update using the mongo shell 3.4.10 against a 3.6.0-rc2 MongoDB instance and it does not work either, with the same error (it does work with mongo shell 3.6.0-rc2 tho).

My version of PHP Driver is: homebrew/php/php56-mongodb: stable 1.3.2 (bottled), HEAD
My version of PHP Library is: 1.2 (installed with composer)

**Comment by jmikola** [comment]
> Note: this may be related to the underlying MongoDB Driver rather than the library.

This actually depends on both driver ([PHPC-975](https://jira.mongodb.org/browse/PHPC-975)) and library ([PHPLIB-295](https://jira.mongodb.org/browse/PHPLIB-295)) support and will be implemented in driver version 1.4.0 and library version 1.3.0, respectively.

At the moment, we're still working on 3.6 support in libmongoc, which is used by the PHP driver. Once that is wrapped up, we'll move on to PHPC and PHPLIB. Unfortunately, I do not expect PHP to have support for all new features in MongoDB 3.6 (such as arrayFilters, which require driver API changes) in time for the server's stable release.

> Note 2: I tried running the same update using the mongo shell 3.4.10 against a 3.6.0-rc2 MongoDB instance and it does not work either, with the same error (it does work with mongo shell 3.6.0-rc2 tho).

That's to be expected. Since this involves changes to the command API (unless you want to run your write commands manually via `db.runCommand()`), you will need to use a 3.6 shell to pass the options.

**Comment by H-Max** [comment]
Hello @jmikola, and thank you for your answer, I guess I'll just wait for the implementations, but in the meantine, if you need people to test these features, I'll be happy to help.

Cheers

**Comment by jmikola** [comment]
Closing this, as array filters are supported in [1.3.0](https://github.com/mongodb/mongo-php-library/releases/tag/1.3.0). Options are also now [documented](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-updateMany/) (UpdateOne was missing, but will be fixed once #505 is deployed).

> but in the meantine, if you need people to test these features, I'll be happy to help.

Apologies for losing track of that once we had an implementation under review, but thanks for the offer just the same :)

**Comment by H-Max** [comment]
Thanks for supporting this and for the updated documentation.

Will try to implement this in our application as soon as our move to 3.6 (not easy) is complete.

**Comment by jmikola** [comment]
Note that the library docs are purposefully light on discussing specifics for the `arrayFilters` option, as that is covered in much greater detail in the [MongoDB manual](https://docs.mongodb.com/manual/reference/command/update/#update-command-arrayfilters).
