### ISSUE TITLE
gridfs and filenames

### ISSUE THREAD

**Issue by rbro** [mongodb/mongo-php-library#508]
I have a question regarding filenames in gridfs using the mongo-php-library.

In the legacy mongo driver, the function storeBytes would create a file in gridfs without giving it a filename.  Similarly, you could call storeFile with a path to a file, and internally, it would create a filename from it.

Looking at openUploadStream and uploadFromStream, it looks like you have to pass a filename to create a gridfs file.

Can you confirm that you now need to have a filename to save a file in gridfs?

Assuming yes, could it just be a random string if the application doesn't need it?  Or are there any downsides to storing every gridfs file with the same filename such as 'abc.txt'?  I'm storing files in gridfs and just need the _id back to point to it.  I don't have or need a filename for the file I'm wanting to store.

Thanks for your help.

**Comment by jmikola** [comment]
> Can you confirm that you now need to have a filename to save a file in gridfs?

A filename string is required by the [GridFS spec](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst), which is implemented by various MongoDB drivers (PHP included).

>  Assuming yes, could it just be a random string if the application doesn't need it? Or are there any downsides to storing every gridfs file with the same filename such as 'abc.txt'?

The filename string is only used for [File Download by Filename](https://github.com/mongodb/specifications/blob/master/source/gridfs/gridfs-spec.rst#file-download-by-filename) API methods, where the combination of `filename` and `uploadDate` fields is used to determine a revision order. For example, if two documents in `fs.files` share the same filename, the most recent "revision" will be the document with the most recent upload date. If you have no intention of using those methods in your application (or other applications accessing the same GridFS collection), I'd say you're in the clear.

Note that [`mongofiles`](https://docs.mongodb.com/manual/reference/program/mongofiles/) also has some methods that utilize the `filename` field for GridFS records, so those would be affected as well. If you're using that tool, you'd need to ensure you stick to the ID-based methods.

Since GridFS does maintain an index of `filename` and `uploadDate` for said APIs, your decision to use large random strings or small fixed values (e.g. `""`, `"abc.txt"`) for the `filename` field would have implications for the size of that index; however, the significance of that will certainly depend on how many files you expect to track in GridFS.

**Comment by rbro** [comment]
Thanks for your feedback.  Since the filename is now required, I think I'll just generate one randomly, so that each file still has a unique filename.
