### ISSUE TITLE
Issue with apply_type_map_to_document

### ISSUE THREAD

**Issue by moderndeveloperllc** [mongodb/mongo-php-library#515]
TL,DR: `apply_type_map_to_document()` is munging booleans in instances where class variables have a default.

## The Problem
I'm running into a rather strange issue with `apply_type_map_to_document()` when I run `FindAndModify`. Basically, if I have a field in my model object that is boolean, and defaulted to `true`, it looks like that value is used - instead of a `false` that is getting returned from the driver. Below is a `var_dump()` as specific points in the process:

## The Command Sent
This is the `FindAndModify` object right before being executed. You can see here that I'm setting **`isActive`** to a boolean `false`.
```
/xxx/vendor/mongodb/mongodb/src/Operation/FindOneAndUpdate.php:152:
object(MongoDB\Operation\FindAndModify)[364]
  private 'databaseName' => string 'spp' (length=3)
  private 'collectionName' => string 'users' (length=5)
  private 'options' => 
    array (size=6)
      'query' => 
        array (size=1)
          '_id' => 
            object(MongoDB\BSON\ObjectId)[399]
              public 'oid' => string '598cbc7b33074e1fbb6cd5e4' (length=24)
      'update' => 
        array (size=1)
          '$set' => 
            array (size=2)
              'isActive' => boolean false
              'modifiedDate' => 
                object(MongoDB\BSON\UTCDateTime)[398]
                  public 'milliseconds' => string '1521665659337' (length=13)
      'typeMap' => 
        array (size=3)
          'array' => string 'array' (length=5)
          'document' => string 'MongoDB\Model\BSONDocument' (length=26)
          'root' => string 'MongoDB\Model\BSONDocument' (length=26)
      'upsert' => boolean false
      'new' => boolean true
      'remove' => boolean false
```
## The Return
The next few dumps are from the following commands:
```
var_dump($result->value, $this->options['typeMap']);
var_dump(\MongoDB\apply_type_map_to_document($result->value, $this->options['typeMap']));
```
You can see in the first dump of the results themselves that `isActive` is correctly being returned as `false`. Though most all of my models are `Persistable`, I _am_ setting a typeMap to force things I may be missing. This means we run through `apply_type_map_to_document()` even though we are already effectively mapped by `Persistable`.

```
/xxx/Sites/spp-engine/vendor/mongodb/mongodb/src/Operation/FindAndModify.php:235:
object(SPPEngine\Model\User)[403]
  public '_id' => 
    object(MongoDB\BSON\ObjectId)[361]
      public 'oid' => string '598cbc7b33074e1fbb6cd5e4' (length=24)
  public 'username' => string 'nn@nnn.com' (length=23)
  public 'password' => string '$2y$10$Rg5WBiakAw93HUQEAsv51O2jS0zoe2zays8i7BFADINKjaSgZeOaq' (length=60)
  public 'email' => null
  public 'lastName' => string 'nn' (length=5)
  public 'firstName' => string 'nn' (length=3)
  public 'companyName' => string 'nnnnnnn' (length=16)
  public 'doctors' => 
    array (size=0)
      empty
  public 'aclList' => 
    array (size=0)
      empty
  public 'phone' => string 'nnnnnn' (length=10)
  public 'userType' => int 2
  public 'passwordExpire' => 
    object(MongoDB\BSON\UTCDateTime)[402]
      public 'milliseconds' => string '1495474372000' (length=13)
  public 'lastLogin' => 
    object(MongoDB\BSON\UTCDateTime)[400]
      public 'milliseconds' => string '1487698408242' (length=13)
  public 'badLoginCount' => null
  public 'isActive' => boolean false
  public 'readOnly' => boolean false
  public 'modifiedDate' => 
    object(MongoDB\BSON\UTCDateTime)[401]
      public 'milliseconds' => string '1521665659337' (length=13)
  public '__pclass' => 
    object(MongoDB\BSON\Binary)[359]
      public 'data' => string 'SPPEngine\Model\User' (length=20)
      public 'type' => int 128
/Users/mgarrett/Sites/spp-engine/vendor/mongodb/mongodb/src/Operation/FindAndModify.php:235:

array (size=3)
  'array' => string 'array' (length=5)
  'document' => string 'MongoDB\Model\BSONDocument' (length=26)
  'root' => string 'MongoDB\Model\BSONDocument' (length=26)
```
## The Mapping
Here we see the result of `apply_type_map_to_document()` and **`isActive`** has been set to `true` instead of the supplied `false`.
```
/xxx/Sites/spp-engine/vendor/mongodb/mongodb/src/Operation/FindAndModify.php:236:
object(SPPEngine\Model\User)[409]
  public '_id' => 
    object(MongoDB\BSON\ObjectId)[405]
      public 'oid' => string '598cbc7b33074e1fbb6cd5e4' (length=24)
  public 'username' => string 'nnn@nnnn.com' (length=23)
  public 'password' => string '$2y$10$Rg5WBiakAw93HUQEAsv51O2jS0zoe2zays8i7BFADINKjaSgZeOaq' (length=60)
  public 'email' => null
  public 'lastName' => string 'nnn' (length=5)
  public 'firstName' => string 'nnn' (length=3)
  public 'companyName' => string 'nnnnnn' (length=16)
  public 'doctors' => 
    array (size=0)
      empty
  public 'aclList' => 
    array (size=0)
      empty
  public 'phone' => string '8702451725' (length=10)
  public 'userType' => int 2
  public 'passwordExpire' => 
    object(MongoDB\BSON\UTCDateTime)[406]
      public 'milliseconds' => string '1495474372000' (length=13)
  public 'lastLogin' => 
    object(MongoDB\BSON\UTCDateTime)[407]
      public 'milliseconds' => string '1487698408242' (length=13)
  public 'badLoginCount' => null
  public 'isActive' => boolean true
  public 'readOnly' => boolean false
  public 'modifiedDate' => 
    object(MongoDB\BSON\UTCDateTime)[408]
      public 'milliseconds' => string '1521665659337' (length=13)
  public '__pclass' => 
    object(MongoDB\BSON\Binary)[352]
      public 'data' => string 'SPPEngine\Model\User' (length=20)
      public 'type' => int 128
```

The `SPPEngine\Model\User` class has declared
```   
  /**
     * @var boolean
     */
    public $isActive = true;
```

I have a very basic `bsonUnserialize` function that works just fine:
```
public function bsonUnserialize(array $data): void
    {
        foreach ($data as $field => $value) {
            /** @noinspection PhpVariableVariableInspection */
            $this->$field = $value;
        }
    }
```

**Comment by jmikola** [comment]
@moderndeveloperllc: Since you've verified that the document returned by `findAndModify` is what you would expect based on dumping `$result->value`, I suggest we attempt to reproduce this with a standalone script that constructs an SPPEngine\Model\User object with those values and then roundtrips it through `apply_type_map_to_document()`.

Assuming you can reproduce that, can you include the most minimal script that does so? I'd start with a script that defines SPPEngine\Model\User, constructs an instance, and roundtrips it. From there, you can start removing properties/code that don't hamper the ability to reproduce the issue.

For instance, I attempted to reproduce this (unsuccessfully) with the following document:

```php
class Document implements MongoDB\BSON\Persistable
{
    public $_id;
    public $name;
    public $isActive = true;

    public function __construct($name)
    {
        $this->_id = new MongoDB\BSON\ObjectId;
        $this->name = $name;
    }

    public function bsonSerialize()
    {
        return get_object_vars($this);
    }

    public function bsonUnserialize(array $data)
    {
        foreach ($data as $field => $value) {
            $this->$field = $value;
        }
    }
}
```

My only hunch at the moment is that `bsonSerialize()` may not be correctly saving a `false` value for `$isActive`, so I'd certainly want to see that method to contrast it with the `bsonUnserialize()` method you provided.

Another avenue we can use to attempt reproduction is to have you give me the raw BSON for the document that reproduces the error on your side. We can do this independently of a standalone script, although I'd prefer to do both if possible. For BSON, you can base64-encode the results of [`MongoDB\BSON\fromPHP()`](http://php.net/manual/en/function.mongodb.bson-fromphp.php) when called with the object. I'll likely still need the entire class definition for SPPEngine\Model\User in order to test unserialization.

Finally, please let me know the exact versions PHP, the extension, and library you're using.

**Comment by moderndeveloperllc** [comment]
@jmikola I think the issue may be with my `bsonSerialize`. My brain didn't register the consequences  of the round trip of `fromPHP`/`toPHP`:
```
public function bsonSerialize(): array
{
    return array_filter(get_object_vars($this));
}
```
As you can see, I was filtering the array because I was wanting to save on storage space - if the class member wasn't set, it wouldn't be saved in the document. Not much of a savings, but I always felt it fit with the philosophy of document-based storage. I think I can remove the `array_fiter()` without consequence.

I do wonder though if perhaps there should be a short-circuit to prevent the bson round trip if the document is `Persistable` because we have already dealt with the unserialization:
```
use MongoDB\BSON\Persistable;

if ( ! is_array($document) && ! is_object($document)) {
    throw InvalidArgumentException::invalidType('$document', $document, 'array or object');
} elseif (is_object($document) && $document instanceof Persistable) {
    return $document;
}
```

**Comment by jmikola** [comment]
Using [`array_filter()`](http://php.net/array_filter) in this context is definitely problematic, as it removes any array element that [converts to a `false` boolean value](http://php.net/manual/en/language.types.boolean.php#language.types.boolean.casting). To do this properly, you'd want to explicitly omit `null` values with a callback.

> I do wonder though if perhaps there should be a short-circuit to prevent the bson round trip if the document is Persistable because we have already dealt with the unserialization:

I believe that would only work if we could guarantee that the Persistable did not have any BSON arrays or non-Persistable documents within it. Crawling the document to make that assessment would add significant complexity, since we'd need to call `bsonSerialize()` at each level when dealing with a Persistable or Serializable instance. The roundtripping in FindAndModify is only temporary until [PHPC-998](https://jira.mongodb.org/browse/PHPC-998) is implemented and we can apply the user's root type map directly to the `value` field in `findAndModify`'s result document. I'm inclined to wait for that in 1.5.0 rather than alter PHPLIB today.

**Comment by moderndeveloperllc** [comment]
> I'm inclined to wait for that in 1.5.0 rather than alter PHPLIB today.

Sounds good to me. I'll close this.
