### ISSUE TITLE
Error when using MongoDB\Collection::aggregate() in 1.3.0

### ISSUE THREAD

**Issue by karptonite** [mongodb/mongo-php-library#516]
When I try to do what seems to be a simple `aggregate()` in 1.3.0, I get the following error:
MongoDB\Driver\Command::__construct() expects exactly 1 parameter, 2 given
This seems to be a problem with this commit:
https://github.com/mongodb/mongo-php-library/commit/43e742ad0380e240f20c4d5a72c220ed04168728#diff-3b2e2c1a4b1425910f13159568854106L312
line 321, where a `MongoDB\Driver\Command` is created with two arguments, and seems to expect only 1 in its constructor.

If I downgrade to 1.2.0, I don't see this bug, so it looks like a real regression.

**Comment by karptonite** [comment]
Oops, saw that bugs are tracked in Jira. Copied this issue to here: https://jira.mongodb.org/browse/PHPLIB-338

**Comment by jmikola** [comment]
> Oops, saw that bugs are tracked in Jira.

No worries. JIRA is certainly preferred, but we also track GitHub issues. Those also have a higher chance of being answered by other users.

Per my [reply on PHPLIB-338](https://jira.mongodb.org/browse/PHPLIB-338?focusedCommentId=1846103&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1846103), the error you're seeing is most certainly caused by running library version 1.3.0 without the required extension version 1.4.0 or later.

**Comment by karptonite** [comment]
You are correct! My mistake.  1.4 extension was on my local machine, but 1.3.3 was on the test server.
