### ISSUE TITLE
Uncaught PHP Exception MongoDB\Driver\Exception\AuthenticationException: “Authentication failed.”

### ISSUE THREAD

**Issue by rottenoats** [mongodb/mongo-php-library#540]
Description:
------------

I'm trying to drop a mongo collection in my Symfony application, however I get an "authentication fails" when I try to drop a collection. I'm able to **select a database** and I'm able to **select a collection**.

The mongoUrl connection string that I inject into my MongoService uses the same credentials specified in my docker compose:

    mongodb://root:XXX@redaph_mongo_1:27017

Note: That even when I put in the wrong credentials I'm still able to select a database and collection without any error being thrown. 

Question:
---------

Why am I getting "Authenticaion Fails" when I try to drop a collection when I'm using root credentials?
How do I correctly authenticate with the root username and password?

Error:
------

> [2018-06-21 08:45:41] request.CRITICAL: Uncaught PHP Exception
> MongoDB\Driver\Exception\AuthenticationException: "Authentication
> failed." at
> /var/www/redaph/vendor/mongodb/mongodb/src/Operation/DropCollection.php
> line 108 {"exception":"[object]
> (MongoDB\\Driver\\Exception\\AuthenticationException(code: 11):
> Authentication failed. at
> /var/www/redaph/vendor/mongodb/mongodb/src/Operation/DropCollection.php:108)"}
> []

Relevant code:
--------------

**docker-compose.yml snippet**

    version '3':
      services:
        mongo:
          image: mongo
          restart: always
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: "XXX"
          volumes:
            - mdb_data:/data/db

**MongoService.php snippet:**

    class MongoService
    {
        const QUESTION_RESPONSE_COLLECTION = "question_response";
        const DATABASE_NAME = "redaph";
        private $mongoDB;
    
        public function __construct($mongoUrl)
        {
            $mongoClient = new MongoClient($mongoUrl);
    
            $this->mongoDB = $mongoClient->selectDatabase(self::DATABASE_NAME);
    
        }
    
        private function getQuestionResponseCollection(){
            return $this->mongoDB->selectCollection(self::QUESTION_RESPONSE_COLLECTION);
        }
    
       
        public function generateQuestionResponses(){
    
            /** code here to populate $questionResponses **/
    
            $collection = $this->getQuestionResponseCollection();
            #-> Authentication Fails Here
            $collection->drop();
            $results = $collection->insertMany($questionResponses);
            return $results->getInsertedCount();
        }
    
        public function getQuestionResponses(){
            return $this->getQuestionResponseCollection()->find([]);
        }
    }

https://stackoverflow.com/questions/50964577/uncaught-php-exception-mongodb-driver-exception-authenticationexception-authen

**Comment by jmikola** [comment]
I'll also note that there exists an [`authMechanism`](http://php.net/manual/en/mongodb-driver-manager.construct.php) URI option. This can be expressed in either the connection string or options array of the `MongoDB\Driver\Manager` or `MongoDB\Client` constructors. Possible values are discussed in [Authentication Options](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authMechanism) in the MongoDB manual.

The default auth mechanism used will vary by combination of server and driver version. This is discussed in the cross-driver [Authentication Specification under Supported Authentication Methods: Defaults](https://github.com/mongodb/specifications/blob/master/source/auth/auth.rst#defaults). In summary, servers before 3.0 use MONGODB-CR, servers 3.0+ use SCRAM-SHA-1 or SCRAM-SHA-256 (if available).

You've not specified what version of the server or driver you're using, so you'll have to interpret the above on your own. IMO, the most useful information here will be a snippet from the mongod log around the time your PHP script is attempting to connect and authenticate. That may provide some more insight into the authentication failure and mechanism being used. Additionally, driver logs obtained from the [`mongodb.debug`](http://php.net/manual/en/mongodb.configuration.php#ini.mongodb.debug) INI setting may also be helpful ("stderr" can be used to easily collect information if running PHP from the CLI).

> How do I correctly authenticate with the root username and password?

On the off chance that your username (unlikely) or password contains special characters, note that those values should URL-encoded if appearing in the connection string (discussed in `[Manager::__construct()` docs for the `$uri` parameter](http://php.net/manual/en/mongodb-driver-manager.construct.php)). Alternatively, you can use the options array, which doesn't require escaping.

> Why am I getting "Authenticaion Fails" when I try to drop a collection when I'm using root credentials?

Selecting a database or collection object, much like constructing a Manager or Client, does not perform any IO on its own (also discussed in docs for `[Manager::__construct()`](http://php.net/manual/en/mongodb-driver-manager.construct.php)). Based on the script above, the first interaction you have with the server is executing the drop operation. Before the driver can execute that command, it initializes the connections and attempts authentication, which is why you encounter the AuthenticationException at that point.

**Comment by rottenoats** [comment]
@jmikola thanks for the response. I've specified latest and I'm on version 
> MongoDB server version: 3.6.5

I've changed my MongoService constructor to:

```
public function __construct($mongoUrl, $mongoUsername, $mongoPassword)
    {
        $mongoClient = new MongoClient($mongoUrl, ["authMechanism" => "SCRAM-SHA-1", "username" => $mongoUsername, "password" => $mongoPassword]);
        $this->mongoDB = $mongoClient->selectDatabase(self::DATABASE_NAME);
    }
```

I tried using SCRAM-SHA-256 but it is not recognized by this library.

I also checked to see if there were any logs in `/var/log/mongodb/` in my mongo container but the directly was empty.

I then added mongodb.debug and set it to stderr like you advised and provided the relevant logs:

> symfony_1  | [2018-06-22T11:14:21.369206+00:00]     PHONGO: DEBUG   > Connection string: 'mongodb://redaph_mongo_1:27017'
> symfony_1  | [2018-06-22T11:14:21.369260+00:00]     PHONGO: DEBUG   > Creating Manager, phongo-1.4.4[stable] - mongoc-1.9.4(bundled), libbson-1.9.4(bundled), php-7.2.6
> symfony_1  | [2018-06-22T11:14:21.369631+00:00]     PHONGO: DEBUG   > Created client hash: a:4:{s:3:"pid";i:18;s:3:"uri";s:30:"mongodb://redaph_mongo_1:27017";s:7:"options";a:3:{s:13:"authMechanism";s:11:"SCRAM-SHA-1";s:8:"username";s:4:"root";s:8:"password";s:3:"123";}s:13:"driverOptions";a:0:{}}
> mongo_1    | 2018-06-22T11:14:21.402+0000 I ACCESS   [conn1] SCRAM-SHA-1 authentication failed for root on admin from client 172.18.0.4:35714 ; AuthenticationFailed: SCRAM-SHA-1 authentication failed, storedKey mismatch
> symfony_1  | [2018-06-22T11:14:21.403768+00:00]    cluster: DEBUG   > Authentication failed: Authentication failed.

I do not know how to resolve this issue, I'll keep on looking for a solution.

**Comment by Neofox** [comment]
In doubt try to create a new user in our mongodb instance 
`db.createUser({ user : "admin", pwd : "admin", roles : ["root"] })`

And try to connect with this one

**Comment by rottenoats** [comment]
@Neofox helped. I recreated my volume and it solved the problem. Probably had a conflict when I first created my root user a while back.

**Comment by jmikola** [comment]
> I tried using SCRAM-SHA-256 but it is not recognized by this library.

For the record: MongoDB 4.0 will be the first server version to support SCRAM-SHA-256. Usage will also require version 1.5.0 of the PHP extension (the library version isn't a factor).
