### ISSUE TITLE
Concurrent connections leaking memory

### ISSUE THREAD

**Issue by cylosh** [mongodb/mongo-php-library#576]
I've moved my application(not using any frameworks) to a [Swoole](https://github.com/swoole/swoole-src)-based daemon which uses 100 workers and when I start the server it automatically opens the same number of connections to mongodb. However, not being able to control the mongo connections it seems that the amount of memory thats being used by mongod daemon keeps increasing with time, it starts from 0.3% from total RAM but slowly in 12 hours goes up to huge levels. That is memory increased solely by mongod:
`1565 mongodb   20   0 1591008 1.129g   6824 S   0.7 14.5   9:44.38 mongod
`
while the server connections count stay the same:
   ```
 "connections" : {
        "current" : 116,
        "available" : 703,
        "totalCreated" : 377
    },

```
I've tried to find an explanation as to why the persistent connections to mongod keep leaking memory and thats a process I can't investigate as it happens perhaps in the low level driver. Is there a solution that I'm not aware of? How can I check the internal driver connection handling(in the deprecated library there was something like getConnections() but here I can't check whats happening under the hood - even a summary)

**Comment by jmikola** [comment]
> Swoole-based daemon which uses 100 workers and when I start the server it automatically opens the same number of connections to mongodb.

Assuming each worker is an independent PHP process and you're constructing `MongoDB\Client` objects with the same arguments (i.e. connection string, options), I expect the driver will create one persisted libmongoc client for each process per the [connection handling](https://www.php.net/manual/en/mongodb.connection-handling.php) documentation.

The `connections` object you shared above looks to be the [`serverStatus` result](https://docs.mongodb.com/manual/reference/command/serverStatus/#connections). I'm not sure how this leads into the next statement:

> I've tried to find an explanation as to why the persistent connections to mongod keep leaking memory and thats a process I can't investigate as it happens perhaps in the low level driver.

The driver (i.e. `mongodb` extension) does not provide any API for exposing its socket usage. When a `MongoDB\Driver\Manager` is constructed, we do [log whether it is able to re-use a previously persisted libmongoc client](https://github.com/mongodb/mongo-php-driver/blob/1.5.2/php_phongo.c#L2450). That message will show up in the trace output, which may be captured via the [`mongodb.debug`](http://www.php.net/manual/en/mongodb.configuration.php#ini.mongodb.debug) INI setting. If you experiment with constructing multiple `MongoDB\Driver\Manager` objects (or `MongoDB\Client` instances) with the same or varying arguments and examine the trace logs, you can get a sense for how the driver behaves in accordance with the [connection handling](https://www.php.net/manual/en/mongodb.connection-handling.php) documentation.

That said, I'm not sure how this plays into the `serverStatus` output you're seeing. I might suggest examining [`netstat`](https://en.wikipedia.org/wiki/Netstat)  output on the host running these Swoole works for the most accurate information about sockets (either in use or no longer used, but still allocated).

**Comment by cylosh** [comment]
Yes each worker creates a parallel PHP processes and each one has a MongoDB\Driver\Manager persistent connection, as per the server result which shows around 100 current connections at all time(they are created instantly when opening the Swoole server). The Swoole clients are running by crontab every minute and they give out tasks to about 40 workers each time.

I investigated all the PHP processes memory usage and while there seems to be a memory leak of around 40-50Kb each couple of hours, the memory usage of the mongod process sky rockets during that time. For instance, since I opened this issue when mongo used about 14.5% RAM, now it reached 22.1%:
` 2884 mongodb   20   0 2146824 1.724g   6844 S   0.3 22.1   6:02.82 mongod
`

I also checked the sockets opened and there only few opened on the Swoole port so I can't see an issue there.

The problem is mongod process that keeps growing in memory usage and it doesn't happen constantly, every few hours a spike occurs and another few hundred Mb of memory are leaked through it for no apparent reason.

**Comment by cylosh** [comment]
Thanks @jmikola for trying to help, I'll try to respond to each of your questions below.

> Can you explain the relation between your Swoole clients and the workers? Do the clients themselves utilize the driver, or are they only responsible for dispatching HTTP requests to a fixed-size pool of workers? I'd just like to confirm if the pool of 100 workers (and effectively libmongoc clients) remains fixed, irrespective of any cron behavior.

The swoole clients are passing along the tasks parameters(via cronjobs) to the fixed-size workers that were setup when the swoole server started. The workers are fixed, they listen for connections and perform certain tasks based on the received parameters.


> Do I understand correctly that the memory footprint of each PHP worker is only increasing by 40-50 kilobytes over the course of a few hours?

They increase by more(Mbs not Kbs) in couple of hours, the ps aux command displays the memory in Kbs it seems, I initially thought those were bytes as I've investigated memory leaks in my application with tools that displayed bytes only. When I'm analyzing my PHP application with php-meminfo I run about 1000 tasks with little or no memory loss, but its running continuously from a single process and perhaps thats why there's no issue with mongo but when they get forked by the swoole server into 100 processes then the unexpected memory consumption starts to happen and I assume it has something to do with mongo and the communication with so many php processes at the same time..

> Can you correlate the number of sockets reported by netstat with the 100 connections you expect to see? That assumes you're connecting to a single mongod. 

Yes I believe its a single mongod, the number of sockets are 1:1 with the number of workers.

> To clarify, is the mongod process running on the same server as the PHP workers, such that the PHP driver is making localhost connections?

Exactly, both Swoole and Mongo servers are being run on the same OS installation and swoole workers connect to mongo using localhost.

> Some other factors to look at in the mongod server may be open cursors or long-running operations

I'm not using open cursors or have long running operations in the application.

> Lastly, I would advise upgrading the server version.

I've just upgraded to version 4.0.2, I've also upgraded the mongo driver to version 1.4.2 and the php extension:
```
MongoDB extension version => 1.6.0-dev
MongoDB extension stability => devel
libbson bundled version => 1.12.0
libmongoc bundled version => 1.12.0
```
With the upgraded mongo libraries I've performed and restarted the Swoole server with only 40 workers and collected the statistics as you advised for 1 hour. I've attached them here and during this time the mongod process increased its memory from 1.09G to 1.12G (its at 14.8% at this moment). 

[Server Status 12-15.txt](https://github.com/mongodb/mongo-php-library/files/2363387/Server.Status.12-15.txt)
[Server Status 12-20.txt](https://github.com/mongodb/mongo-php-library/files/2363388/Server.Status.12-20.txt)
[Server Status 12-25.txt](https://github.com/mongodb/mongo-php-library/files/2363389/Server.Status.12-25.txt)
[Server Status 12-30.txt](https://github.com/mongodb/mongo-php-library/files/2363390/Server.Status.12-30.txt)
[Server Status 12-35.txt](https://github.com/mongodb/mongo-php-library/files/2363391/Server.Status.12-35.txt)
[Server Status 12-40.txt](https://github.com/mongodb/mongo-php-library/files/2363392/Server.Status.12-40.txt)
[Server Status 12-45.txt](https://github.com/mongodb/mongo-php-library/files/2363393/Server.Status.12-45.txt)
[Server Status 12-50.txt](https://github.com/mongodb/mongo-php-library/files/2363394/Server.Status.12-50.txt)
[Server Status 12-55.txt](https://github.com/mongodb/mongo-php-library/files/2363395/Server.Status.12-55.txt)
[Server Status 13-00.txt](https://github.com/mongodb/mongo-php-library/files/2363396/Server.Status.13-00.txt)
[Server Status 13-05.txt](https://github.com/mongodb/mongo-php-library/files/2363383/Server.Status.13-05.txt)
[Server Status 13-10.txt](https://github.com/mongodb/mongo-php-library/files/2363384/Server.Status.13-10.txt)
[Server Status 13-15.txt](https://github.com/mongodb/mongo-php-library/files/2363385/Server.Status.13-15.txt)
[Mongostat logs.txt](https://github.com/mongodb/mongo-php-library/files/2363386/Mongostat.logs.txt)

**Comment by jmikola** [comment]
### MongoDB memory usage

The memory increases reported by `mongostat` can be correlated to the `serverStatus` output. If we look at the [`mem`](https://docs.mongodb.com/manual/reference/command/serverStatus/#serverstatus.mem) output between 12:15 and 13:15:

```
    "mem" : {
        "bits" : 64,
        "resident" : 1128, // -> 1145
        "virtual" : 2101, // -> 2121
        "supported" : true,
        "mapped" : 0,
        "mappedWithJournal" : 0
    },
```

1128 MiB corresponds to 1.1015625 GiB. 1145 MiB corresponds to 1.118164063 GiB. Those numbers agree with the 1.09G and 1.12G values we see from `mongostat` over this time. Also, looking at the documentation for the [`mem.resident`](https://docs.mongodb.com/manual/reference/command/serverStatus/#serverstatus.mem.resident) field:

> The value of mem.resident is roughly equivalent to the amount of RAM, in megabytes (MB), currently used by the database process. During normal use, this value tends to grow. In dedicated database servers, this number tends to approach the total amount of system memory.

This seems like expected behavior. Assuming most of this growth is related to the storage engine, I expect it's growing as new data is inserted, updated, and/or queried over the lifetime of the application. So long as there is available memory on the system, the database server is going to continue using it. This is unlike a closed connection/cursor, whose resources would be freed when no longer in use.

Any further questions about server-side memory usage would probably be better asked on one of the server-related [community support](https://docs.mongodb.com/manual/support/index.html#community-support) channels, as I have a finite amount of experience in this area.

### PHP memory usage

> When I'm analyzing my PHP application with php-meminfo I run about 1000 tasks with little or no memory loss...

I don't believe [`php-meminfo`](https://github.com/BitOne/php-meminfo) provides any insight into memory usage within other PHP extensions (unless those extensions are creating zvals), so that may not be helpful.

> but when they get forked by the swoole server into 100 processes then the unexpected memory consumption starts to happen and I assume it has something to do with mongo and the communication with so many php processes at the same time..

I'm still not clear on how Swoole is spawning these processes. In `Mongostat.logs.txt`, you have `ps aux` output that shows 43 seemingly identical `php -f /var/www/html/swoole-server.php` processes. After a few iterations, one of these processes maintains the 7720 RSS (resident set size), which is approximately 7.54 MiB, while the other 42 processes increase to anywhere between 10 MiB and 28 MiB. In later iterations of `ps aux` further into `Mongostat.logs.txt`, the RSS figures for those other 42 processes remain constant, so I don't see anything there that would indicate a leak.

Please correct me if I'm mistaken then, and there's something on the PHP side I may be missing.

**Comment by cylosh** [comment]
Ok, thats useful information about mem.resident. Looking at it now after running continuously since giving the above logs its showing
```
    "mem" : {
        "resident" : 1295,
        "virtual" : 2250,
    },
```
 and its utilizing 16.2% of the total memory, continually growing and it seems those spikes were connected with the swoole server restart but only happened after several hours because the workers were not reaching their full capacity immediately. This time around I haven't restarted the swoole server to see how much memory its going to eat over a longer period but surprisingly they stopped consuming memory after a while, now almost all using around ~50MB.

> This seems like expected behavior. Assuming most of this growth is related to the storage engine, I expect it's growing as new data is inserted, updated, and/or queried over the lifetime of the application. So long as there is available memory on the system, the database server is going to continue using it. This is unlike a closed connection/cursor, whose resources would be freed when no longer in use.

So if I'll move to a dedicated mongoDb server will the server crash once it'll reach 100% or just free up memory and continue serving requests?

> I don't believe php-meminfo provides any insight into memory usage within other PHP extensions (unless those extensions are creating zvals), so that may not be helpful.

Yes I was only analyzing my own application memory leaks(objects that kept growing, etc.). When I was performing these memory tests everything looked normal but in practice when running the swoole server the mongo process kept growing.

> After a few iterations, one of these processes maintains the 7720 RSS (resident set size), which is approximately 7.54 MiB, while the other 42 processes increase to anywhere between 10 MiB and 28 MiB
Please correct me if I'm mistaken, and there's something on the PHP side I may be missing.

That was a bug of mine, the worker had id 0 and I was skipping it when assigning tasks.

**Comment by jmikola** [comment]
> So if I'll move to a dedicated mongoDb server will it crash once reaching 100% or just free up memory and continue serving requests?

I would not expect MongoDB to crash due to an OOM error, no. I believe the memory growth we're seeing is primarily from the storage layer, which we can consider "soft" usage. The server naturally tries to use whatever RAM is available for caching, indexes, etc. If memory isn't available for this purpose, I think you'd just see slower performance instead of an OOM error. This is different than allocating memory for connections and cursors, which is more of a "hard" requirement (you'd certainly get some sort of error if there was insufficient memory available for _those_ resources). If you'd like a more detailed explanation of this, I'd definitely suggest you ask on the [mongodb-user](https://groups.google.com/forum/#!forum/mongodb-user) mailing list, as you're likely to get a server engineer to chime in with more technical details than I can provide.

MongoDB's preference to use as much memory as available factors into why we don't advise running multiple `mongod` processes on the same host (unless isolated in VMs, containers, etc.). This advice can extend to application servers on a case by case basis, but I think there's more leeway there (e.g. some applications will use a fixed memory footprint and won't compete with `mongod` for resources).

**Comment by cylosh** [comment]
Thanks for the advices @jmikola, I appreciate taking the time. In case I need more info I'll check with mongodb group but for the moment I'm satisfied with the answers you provided.

All the best
