### ISSUE TITLE
Add exception if CountDocuments used with empty filter

### ISSUE THREAD

**Issue by qRoC** [mongodb/mongo-php-library#581]
The current implementation allows use operation `CountDocuments` with empty filter:

`public function countDocuments($filter = [], array $options = [])`

That potential bug, because final query is:

```
[
{
    "$match" : {}
},
{
    "$group" : {
        "_id" : null,
        "n" : {
            "$sum" : 1
        }
    }
}
]
```

PHP can be stopped by timeout but mongo query will continue.

**Comment by jmikola** [comment]
Approximately how large is the collection? If you have access to a `mongo` shell, you can share `db.collection.stats()` output for the collection. I expect that your query is taking longer than PHP's maximum socket timeout. While the driver's default [`socketTimeoutMS`](http://php.net/manual/en/mongodb-driver-manager.construct.php) value is 300000 (i.e. 5 minutes), I expect you're hitting PHP's [max_execution_time](http://php.net/manual/en/info.configuration.php#ini.max-execution-time) first.

The aggregation pipeline you shared is expected behavior for `countDocuments()`, as that is necessary to compute an exact count of documents in the collection. The reasons for that approach are discussed in [this specification](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#count-api-details).

If you don't require an _exact_ count, it would be more performant to use `estimatedDocumentCount()`, which is equivalent to running the old `count()` method without a filter. Both `count()` and `estimatedDocumentCount()` use the [`count`](https://docs.mongodb.com/manual/reference/command/count/) database command. As explained in the spec referenced above, the `count` command has historically had issues with providing exact counts, which is why two new methods were introduced. I realize the resulting API with three count methods is rather confusing, but that was necessary to (a) preserve BC for the now-deprecated `count()` method and (b) avoid introducing a single new method that had two very different modes of execution (e.g. `newCount()` method with an `estimated` option).

Note that all three methods support a `maxTimeMS` option that you can use to limit the amount of time the query will run on the server (even if the driver drops its connection). This [blog post](http://jmikola.net/blog/mongodb-timeouts/) explains why it's helpful to use that option (mostly comparing it to apps only using client-side socket timeouts).

**Comment by qRoC** [comment]
~15000000000 records
socketTimeoutMS - not set
connectTimeoutMS - 5000
PHP max_execution_time - 300

But:
```
"clientMetadata" : {
    "driver" : {
        "name" : "mongoc / ext-mongodb:PHP",
        "version" : "1.12.0 / 1.5.2"
    },
    ...
},
"active" : true,
"secs_running" : NumberLong(**21167**),
"microsecs_running" : NumberLong("21167593559"),
"command" : {
    "aggregate" : "...",
    "pipeline" : [
        {
            "$match" : {

            }
        },
        {
            "$group" : {
                "_id" : null,
                "n" : {
                    "$sum" : 1
                }
            }
        }
    ],
    "cursor" : {

    },
    "$db" : "...",
    "$readPreference" : {
        "mode" : "secondaryPreferred"
    },
    ...
},
...
```


So work without maxTimeMS is unsafe.

Thanks.
