### ISSUE TITLE
Map and sort with JavaScript function

### ISSUE THREAD

**Issue by Chameleon-m** [mongodb/mongo-php-library#585]
```javascript
db.getCollection('user').find(
    {"external_identity":
        {"$elemMatch":
            {
                "type":"bpo",
                "value":{
                    "$in":  ["34","17753","7828","35060","21"]
                }
            }
        }
    })
    .map( function(u) {   
        var t = ["34","17753","7828","35060","21"];
        u.order_column = u.order_column = t.indexOf(u.external_identity[0].value)
        return u; 
    }).sort(function(item1, item2) {
        return item1.order_column - item2.order_column 
  })
```
How to translate this into mongo-php-library ?
Or how to make Mongodb return in the correct order, "34", "17753", "7828", "35060", "21", and not "21", "34", "7828", "17753", "35060"

**Comment by jmikola** [comment]
In your shell example, [`db.collection.find()`](https://docs.mongodb.com/manual/reference/method/db.collection.find/) is the only function that interacts with the database and is analogous to [`MongoDB\Collection::find()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-find/).

The [`cursor.map()`](https://docs.mongodb.com/manual/reference/method/cursor.map/) method in the shell is a bit of syntactic sugar to iterate through the cursor and apply a callback function to each result. You can inspect its source in the shell:

```
> db.foo.find().map
function (func) {
    var a = [];
    while (this.hasNext())
        a.push(func(this.next()));
    return a;
}
```

The PHP driver does not go out of its way to provide helpers for its [`MongoDB\Driver\Cursor`](http://php.net/manual/en/class.mongodb-driver-cursor.php) object. It can either be iterated directly (e.g. `foreach`) or you can wrap it with a custom iterator (e.g. [SPL iterator classes](http://php.net/manual/en/spl.iterators.php)). If you wish to apply some conversion logic to each element in the cursor's results, I can think of two options off the top of my head:

 * Convert the cursor to an array using either [`MongoDB\Driver\Cursor::toArray()`](http://php.net/manual/en/mongodb-driver-cursor.toarray.php) or [`iterator_to_array()`](http://php.net/iterator_to_array) and then call [`array_map()`](http://php.net/array_map) on the resulting array.
 * Initialize an empty array. Iterate through the cursor with `foreach` and process each element in the body of the loop and add it to the array. This is most similar to what the shell is doing in its `cursor.map()` function (as we can see above).
 * Wrap the cursor with your own class that extends PHP's [`IteratorIterator`](http://php.net/manual/en/class.iteratoriterator.php) and override the `current()` method to implement your processing logic. Then, iterate on your custom iterator instead of the cursor directly. This solution would be the most efficient as you can avoid converting the entire result set into a single array.

The final `sort()` method call refers to [`Array.prototype.sort()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) in Javascript, and is not specific to the MongoDB shell. The most obvious analogy in PHP would be [`usort()`](http://php.net/manual/en/function.usort.php) (since [`array_sort()`](http://php.net/array_sort) does not take a custom comparison callback).

----

A completely different approach to this problem would be to make use of an [aggregation pipeline](https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/) to query, modify, and sort the documents. This would have the benefit of being handled entirely on the server and you would end up with a portable pipeline that can be executed with any driver (including the shell).

At a glance, the `$match`, `$project`, and `$sort` stages could take the place of the `find()`, `map()`, and `sort()` calls, respectively. The most challenging part of this will be devising the `$project` operation to produce the desired `order_column` field based on the value of `external_identity`. There are a large number of [operators](https://docs.mongodb.com/manual/reference/operator/aggregation/) available to use for this purpose. For instance, you might project `order_column` as the result of [`$switch`](https://docs.mongodb.com/manual/reference/operator/aggregation/switch/). One of the [`$switch` examples](https://docs.mongodb.com/manual/reference/operator/aggregation/switch/#example) actually demonstrates how to project a new field based on some analysis of another field in the same document, so I might suggest starting there.

To bring this back to the PHP driver, you can execute (and test) your aggregation pipeline using the [`MongoDB\Collection::aggregate()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-aggregate/) method.

----

Side note: this line in your code example stood out:

```js
u.order_column = u.order_column = t.indexOf(u.external_identity[0].value)
```

The second assignment of `u.order_column` looks redundant and can probably be removed.

**Comment by Chameleon-m** [comment]
@jmikola Thank you for such a detailed answer.
I will study in more detail aggregation pipeline.

u.order_column = u.order_column = t.indexOf(u.external_identity[0].value)
copying error:)

**Comment by Chameleon-m** [comment]
@jmikola I did it this way
```javascript
db.getCollection('user').aggregate([
    { $match :
        {"external_identity":
            {"$elemMatch":
                {
                    "type":"bpo",
                    "value":{
                        "$in": ["34","21","32957"]
    }}}}},
    { $project : {
        firtsIdentity: { $arrayElemAt: [ "$external_identity", 0 ] }
    }},
    { $project : {
        order_column: { $indexOfArray: [ ["34","21","32957"], "$firtsIdentity.value" ] }
    }},
    { $sort: {"order_column": 1}}
])
```
please tell me how to improve the query

**Comment by jmikola** [comment]
Since the first `$project` appears to be pulling out the first element of the `external_identity` field, you may be able to simply use the second `$project` (with `$indexOfArray`) and refer to the `$external_identity.0.value` field (per the [field path](https://docs.mongodb.com/manual/meta/aggregation-quick-reference/#field-path-and-system-variables)) syntax).

Other than that, and without running your pipeline myself, the example you have looks OK. You should be able to compare its output against your original shell example and confirm they produce identical results.

**Comment by Chameleon-m** [comment]
$external_identity.0.value and $external_identity[0].value
This is the first that I tried, but it did not work

**Comment by jmikola** [comment]
In that case, `$arrayElemAt` may be the way to go. Any additional questions on aggregation pipeline specifics are probably better asked in one of the [community support channels](https://docs.mongodb.com/manual/support/#community-support), as those are more general MongoDB questions outside the scope of the driver/library.

**Comment by derickr** [comment]
I'm closing this out. Please feel free to create a new ticket if you find potential bugs in the driver or library.
