### ISSUE TITLE
Session and transaction example and questions

### ISSUE THREAD

**Issue by cystbear** [mongodb/mongo-php-library#602]
Hi guys, as far as MongoDB session/transaction quite fresh feature there is lack of docs and/or examples. 

I would like to know more closely how that two guys works together with examples and explanations.

Concrete questions:
1) Should I explicit pass `Session` object to each query which I want belong to?

2) From PHP doc [link](http://php.net/manual/en/mongodb-driver-session.endsession.php)

```
Session::endSession

This method closes an existing session. If a transaction was associated with this session, this transaction is also aborted, and all its operations are rolled back.
```

What happen if I started session, but will not end it explicitly and my PHP script will exit(despite of exit code) for a reason of: normal end, exception or memory limit or execution time limit. Will be session ended correctly? What about transaction inside this session? Will it rollback correctly?

I suppose kinda `Session::__destruct()` 

```php
function __destruct()
{
    $this->endSession();
}
```

**Comment by cystbear** [comment]
cc @jmikola

**Comment by jmikola** [comment]
Good to hear from you, Oleg :)

I noticed that the PHP.net docs were a bit vague on the interactions between sessions and transactions, so I just improved those a bit in [r346802](svn.php.net/viewvc?view=revision&revision=346802). Those improvements should answer your questions, but I'll do so here as well:

> Should I explicit pass `Session` object to each query which I want belong to?

Yes. This was also the case before transactions if you wanted to associate an operation with an explicit session (e.g. to track it across the cluster). Since transactions are bound to a session, the same rule applies for associating a sequence of operations with a transaction.

> What happen if I started session, but will not end it explicitly and my PHP script will exit(despite of exit code) for a reason of: normal end, exception or memory limit or execution time limit. Will be session ended correctly? What about transaction inside this session? Will it rollback correctly?

[`Session::endSession()`](http://php.net/manual/en/mongodb-driver-session.endsession.php) simply accelerates the process of closing the session, which would otherwise happen during garbage collection. Under normal circumstances, you shouldn't need to call `endSession()` manually.

If there is an active transaction on the session when it closes, the transaction will be aborted and you can trust that that any data changes made during the transactions will not be applied. You can refer to that as a roll back if it helps, but do note that it's different than a [replica set roll back](https://docs.mongodb.com/manual/core/replica-set-rollbacks/), which is why we avoid using that language in the documentation.

**Comment by jmikola** [comment]
Closing this since I don't think there's anything outstanding. Feel free to follow up if that's not the case.

**Comment by cystbear** [comment]
👍
