### ISSUE TITLE
Get database defined in connection string

### ISSUE THREAD

**Issue by mnavarrocarter** [mongodb/mongo-php-library#609]
Hi there!

I'm creating a new instance of `Client` with a mongodb+srv uri pointing to a cluster. This is stored in an env variable in my app, so this uri can and will change. 

The problem I'm facing is that the `mongodb/mongodb` library does not expose the default database defined in the connection string. I have to explicitly call `selectDatabase($dbName)` if I want the database instance. As you may know, this is not very "environment variable" friendly. 

I can work something out, but I would like to know if there's a way of getting the defined database name without parsing the uri myself.

Thanks a lot! :)

**Comment by mnavarrocarter** [comment]
Well, it wasn't that hard really. Leave this here for someone who may need it.

```php
<?php

$client = new Client(getenv('MONGO_URI'));
$database = trim(parse_url(getenv('MONGO_URI'))['path'], '/');

return $client->selectDatabase($database);
```

**Comment by jmikola** [comment]
The database name found in the connection string is technically only relevant for authentication and is deprecated in favor of the [`authSource`](https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource) URI option. Since the component is deprecated, serves no purpose outside of authentication, and authentication is handled internally by the driver, we've not considered adding an API to extract its value. See the following documents for additional detail on this component:

 * [Connection String: Components](https://docs.mongodb.com/manual/reference/connection-string/#components) from the MongoDB manual
 * [Connection String specification](https://github.com/mongodb/specifications/blob/master/source/connection-string/connection-string-spec.rst#auth-database-optional)

Some other drivers may use the URI's database component for other purposes (e.g. selecting a default database), but that behavior is likely rooted in preserving some legacy behavior. I believe the Node.js driver (and/or Mongoose ODM) is one such case where there is the concept of a "default" database.

If you're using a `mongodb+srv` scheme with the URI, it's also quite possible that the SRV or TXT record contains an `authSource` value (among other URI options). This is mentioned in the [DNS Seedlist Connection Format](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format) section in the MongoDB manual entry above.

My advice to you would be to create a separate environment variable to track the default database for your application. If you'd rather leave it within the URI string and manually parse it, please just note how it is actually used (or ignored) by the driver to ensure there are no surprises.

**Comment by alcaeus** [comment]
Closing since the original question seems to be resolved. Feel free to follow up if this is not the case.
