### ISSUE TITLE
generate_index_name gives "Notice: Array to string conversion" with ordered index configuration

### ISSUE THREAD

**Issue by rbaarsma** [mongodb/mongo-php-library#627]
From the [documentation](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/indexes.html) we're using YAML configuration:

```
  indexes:
    processingStation:
      keys:
        processingStation: 
          order: asc
```

In functions.php (generate_index_name) line 76, the `$type` variable then becomes an array with `["order" => "asc"]`

This gives: `Notice: Array to string conversion`

I get this issue when trying to load doctrine fixtures with latest version of all mongo/doctrine shizzle in Symfony 3.4.

**Comment by jmikola** [comment]
Can you share a backtrace for the notice? I believe Symfony will already throw an exception for notices, but if not you can set an [error handler to do so](https://stackoverflow.com/a/32822054/162228).

At a quick glance, this looks like an error in Doctrine. The `keys` document should consist of key/value pairs where each key is a string (i.e. field name or path) and the corresponding value is either a number (ordering) or string (index type). See the [createIndexes](https://docs.mongodb.com/manual/reference/command/createIndexes/) command reference for more details. The "Array to string conversion" error suggests that Doctrine is passing `{ "processingStation": { "order": "asc" }}` directly to the MongoDB library, which rightfully produces an error.

It may be preferable if the library raised an exception for this instead of relying on PHP to emit a notice. I've opened [PHPLIB-447](https://jira.mongodb.org/browse/PHPLIB-447) to track that.

The library currently only works with the `keys` document to generate an index name and would otherwise pass it as-is to the server. I'm not sure what version of the server you're using, but MongoDB 3.4+ would report an error if it encountered a value within `keys` that was neither a number nor a string (added in https://github.com/mongodb/mongo/commit/315f92405c5f5e5f4159ccbb55b0352cfe235852 for [SERVER-26659](https://jira.mongodb.org/browse/SERVER-26659)). I'm not sure what older server versions do, but I would not be surprised if an invalid type was treated as an ascending order.

**Comment by rbaarsma** [comment]
I'm using mongod version v4.0.9

https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/indexes.html
In the docs, if you look for example at the YAML example of "If you want to specify an index that consists of multiple fields you can specify them on the class doc block:", you will see that this is (at least according to doctrine docs) a valid notation. If it isn't, perhaps we should report a documentation bug there.

I did fix the notice by changing my YAML to

```
  indexes:
    processingStation:
      keys:
        processingStation: asc
```

(which is the notation in other examples).

Symfony catches notices in the same way as it catches errors. It's not-done in symfony-land to disable php notices :P 

In any case: thanks for looking at this issue. I hope that at the very least other people with this problem will find my solution and better even would be to find a real fix.

Isn't it as simple as changing the function where the notice is to not break when an array is given? Instead look for the order key in the array and use that to make the name unique? You could even serialize the array to make it into a unique string.

**Comment by jmikola** [comment]
Thanks for reporting this, and I'm glad to see it was easily fixed on your end. 

> https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/indexes.html
In the docs, if you look for example at the YAML example of "If you want to specify an index that consists of multiple fields you can specify them on the class doc block:", you will see that this is (at least according to doctrine docs) a valid notation. If it isn't, perhaps we should report a documentation bug there.

This definitely appears to be a documentation bug. The `order` key is only used when specifying an index for a single field (within the field's mapping) and should not be used for the multi-field index examples.

We even see this explicitly mentioned in [this line within YamlDriver](https://github.com/doctrine/mongodb-odm/blob/1.2.9/lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php#L202).

I've opened https://github.com/doctrine/mongodb-odm/pull/2035 to correct the ODM manual.

> Isn't it as simple as changing the function where the notice is to not break when an array is given? Instead look for the order key in the array and use that to make the name unique? You could even serialize the array to make it into a unique string.

My original point was that `order` should never be in the index specification (i.e. `keys` document) at all. Modifying `generate_index_name()` to ignore or work around a non-scalar value would only mask the issue and cause you to hit a server error. That said, the logic in `generate_index_name()` is intended to be consistent with the [Index Management spec](https://github.com/mongodb/specifications/blob/master/source/index-management.rst#index-name-generation). All drivers and the server should create the same name for a given `keys` document, so we don't want to deviate.

If we look at [`YamlDriver`'s processing of the `indexes`](https://github.com/doctrine/mongodb-odm/blob/1.2.9/lib/Doctrine/ODM/MongoDB/Mapping/Driver/YamlDriver.php#L91) field, it passes `keys` as-is to [`ClassMetadataInfo::addIndex()`](https://github.com/doctrine/mongodb-odm/blob/1.2.9/lib/Doctrine/ODM/MongoDB/Mapping/ClassMetadataInfo.php#L871). That function uses `array_map()` to normalize some values and convert "asc" and "desc" strings to numbers, but otherwise leaves the value as-is. In your case, the value is an associative array.

Further down the rabbit hole, [`SchemaManager::prepareIndexes()`](https://github.com/doctrine/mongodb-odm/blob/1.2.9/lib/Doctrine/ODM/MongoDB/SchemaManager.php#L233) accesses the index definitions from class metadata. The only modification it makes to the index specification is to translate field names in the event the class property and database names differ. It then attempts to create the index on the server in [`ensureDocumentIndexes()`](https://github.com/doctrine/mongodb-odm/blob/1.2.9/lib/Doctrine/ODM/MongoDB/SchemaManager.php#L267), but at no point are the values within `keys` modified.

It appears that an ODM user would only encounter this via the YAML driver, since the annotation and XML drivers would not allow arbitrary values to make it into ClassMetadataInfo's indexes property.
