### ISSUE TITLE
Referencing other fields

### ISSUE THREAD

**Issue by sevenpixels** [mongodb/mongo-php-library#701]
```php
    $collection->updateMany(
        ['game_id' => $game_id],
        ['$min' => ['low_score' => '$score'], '$max' => ['high_score' => '$score']]
    );
```
The above code doesn't actually compare the values currently in low_score with the value of score. If I replace $score with a numeric value it works as it should.

```php
    $collection->updateMany(
        ['user' => $this->user['id'], 'low_score' => ['$exists' => false], 'high_score' => ['$exists' => false]],
        ['$set' => ['low_score' => '$score', 'high_score' => '$score']]
    );
```

This code doesn't set low_score and high_score to the value of score if they don't exist. It sets them to the string "$score". I want it to set them to the value of score

**Comment by alcaeus** [comment]
The MongoDB query syntax only allows comparing fields with literal values, not with other fields from the same document. Similarly, updates using this query language can only refer to literal values, not other fields in the document either. The `$min` and `$max` query operators also work differently. I'll make the first example where we're storing the score in the document, simultaneously updating the `low_score` and `high_score` fields:
```php
$collection->updateOne(
    ['game_id' => $game_id],
    [
        '$set' => ['score' => $score],
        '$min' => ['low_score' => $score],
        '$max' => ['high_score' => $score],
    ]
);
```

Note that the `$min` and `$max` operator set the field to the specified value if the field previously did not exist (which is what you attempted to do in the second document). This all works well because we're using literal values. If you want to update the documents after the fact, referencing another field in your document, you have to use aggregation pipeline to do so.       

With MongoDB 4.2, you can use an aggregation pipeline as update specification, but you may only use the `$addFields`, `$project`, and `$replaceRoot` pipeline stages. You can also use their aliases `$set`, `$unset`, and `$replaceWith`. Note that you must be using the latest versions of MongoDB (4.2.0 or newer), the `mongodb` PHP extension (1.6.0 or newer), and this library (1.5.0 or newer) for the following examples to work.

The query above would have to look like this:
```php
$collection->updateOne(
    ['game_id' => $game_id],
    [
        ['$set' => [
            'low_score' => ['$min' => ['$score', '$low_score'],
            'high_score' => ['$max' => ['$score', '$max_score'],
        ]],
    ]
);
```

In this example, we're using the `$set` aggregation pipeline stage (also known as `$addFields`) to update the `low_score` and `high_score` fields. Note that the `$set` operator is no longer in the top-level array of the update specification but nested once - this is because we can have multiple aggregation pipeline stages in any order, even repeating previous stages (e.g., `$set` followed by `$replaceWith`, followed by another `$set` stage). The `$min` and `$max` aggregation pipeline operators have a different syntax compared to the query operators of the same name, but the behaviour is the same. You can find a list of aggregation pipeline operators in the [MongoDB Documentation](https://docs.mongodb.com/manual/reference/operator/aggregation/).

One more point about aggregation pipeline updates: while the entire update operation is atomic, each aggregation pipeline stage is evaluated and executed in sequence. Thus, when using the `'$score'` expression in a stage, it will refer to the value of the `score` field **before** applying the current pipeline stage. Take the following example:
```php
$collection->updateOne(
    ['game_id' => $game_id],
    [
        ['$set' => [
            'score' => ['$sum' => '$score', $score],
            'low_score' => ['$min' => ['$score', '$low_score'],
            'high_score' => ['$max' => ['$score', '$max_score'],
        ]],
    ]
);
```

You would think that this aggregation pipeline stage would increase the stored score by the value in `$score`, then update the `low_score` and `high_score` fields accordingly. However, the entire `$set` stage is evaluated at once, so the `$min` and `$max` operators use the value of `score` **before** the `$sum` operator is applied. You have to split this into two separate aggregation pipeline stages for this to work as expected:
```php
$collection->updateOne(
    ['game_id' => $game_id],
    [
        ['$set' => [
            'score' => ['$sum' => '$score', $score],
            'low_score' => ['$min' => ['$score', '$low_score']],
            'high_score' => ['$max' => ['$score', '$max_score']],
        ]],
    ]
);
```


Of course, if you wanted to combine them you could use the literal value and make it a single `$set` stage:
```php
$collection->updateOne(
    ['game_id' => $game_id],
    [
        ['$set' => [
            'score' => ['$sum' => '$score', $score],
        ]],
        ['$set' => [
            'low_score' => ['$min' => ['$score', '$low_score']],
            'high_score' => ['$max' => ['$score', '$max_score']],
        ]],
    ]
);
```

Now, the first stage increases the score, while the second stage updates the `low_score` and `high_score` fields. However, the entire operation is atomic, so you don't have to worry about a second update query coming in to mess things up - they will be executed in sequence.

One last point I'd like to make is that you can only reference fields from the document being updated, not any other documents. The latter would require an aggregation command using the `$out` or `$merge` stage instead of an update command as shown above.

Please let me know if you have any other questions.

**Comment by sevenpixels** [comment]
Ok, I think I see what you're saying. I tried it but got an error.

```php
        $collection->updateOne(
            ['project' => 12],
            [
                ['$set' => [
                    'low_score' => ['$min' => ['$score', '$low_score']],
                    'high_score' => ['$max' => ['$score', '$max_score']],
                ]]
            ]
        );
```
```
Error determining if update will go over space quota: Error estimating update space usage: Error finding 'u' part of update: Expected 'u' to be BSON (or equivalent), but got []interface {} instead. Doc = [{q [{game_id 12}]} {u [[{$set [{low_score [{$min [$score $low_score]}]} {high_score [{$max [$score $high_score]}]}]}]]} {upsert false} {multi true}]
```

I tried by dropping the first set of [] on the 2nd parameter, I did some commands like that and they work, but wasn't with $min and $max.

```php
        $collection->updateOne(
            ['project' => 12],
            ['$set' => [
                    'low_score' => ['$min' => ['$score', '$low_score']],
                    'high_score' => ['$max' => ['$score', '$max_score']],
            ]]
        );
```
```
The dollar ($) prefixed field '$max' in 'high_score.$max' is not valid for storage.
```

**Comment by jmikola** [comment]
@sevenpixels: I attempted to reproduce this on a standalone `mongod` instance (v4.2.1) using extension version 1.6.1 and library version 1.5.1.

```sh
$ rm -rf /tmp/db1;
$ mkdir /tmp/db1;
$ mongod --dbpath /tmp/db1 --port 27017
```

I then ran the following script, based on your example above:

```php
<?php

require_once 'vendor/autoload.php';

$client = new MongoDB\Client('mongodb://127.0.0.1/');

$collection = $client->selectCollection('test', 'gh701');

$collection->drop();

$collection->insertOne([
    'project' => 12,
    'score' => 10,
    'low_score' => 15,
    'high_score' => 5,
]);

$collection->updateOne(
    ['project' => 12],
    [
        ['$set' => [
            'low_score' => ['$min' => ['$score', '$low_score']],
            'high_score' => ['$max' => ['$score', '$max_score']],
        ]]
    ]
);

var_dump($collection->findOne());
```

This resulted in the following output, which is what I would have expected:

```
object(MongoDB\Model\BSONDocument)#12 (1) {
  ["storage":"ArrayObject":private]=>
  array(5) {
    ["_id"]=>
    object(MongoDB\BSON\ObjectId)#11 (1) {
      ["oid"]=>
      string(24) "5dfa57a6280de609357968d2"
    }
    ["project"]=>
    int(12)
    ["score"]=>
    int(10)
    ["low_score"]=>
    int(10)
    ["high_score"]=>
    int(10)
  }
}
```

**Comment by sevenpixels** [comment]
PHP 7.3.12
MongoDB extension version => 1.6.1
libbson bundled version => 1.15.2
libmongoc bundled version => 1.15.2

mongodb/mongodb 1.5.1

MongoDB is in Atlas and shows Version 4.0.13

Not sure if it matters, but I'm using `updateMany` vs `updateOne`. I edited my comment to reflect that. I'm trying to update all the scores for a particular game at once.

**Comment by sevenpixels** [comment]
Actually I think I see the problem ... I'm on MongoDB 4.0.13, not 4.2. I'm going to see if I can get the server on 4.2 and try again.

**Comment by jmikola** [comment]
> MongoDB is in Atlas and shows Version 4.0.13

Update pipelines definitely require MongoDB 4.2, as noted in both the [server release notes](https://docs.mongodb.com/manual/release-notes/4.2/#update-and-aggregation) and the library's documentation (see: [`Collection::updateMany()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-updateMany/#definition)). Do let us know if you find a place where we missed noting the server requirement.

As for the server error your received, it was quite different from what I saw when running MongoDB 4.0.x locally. Are you using the free tier of Atlas by any chance? AFAIK, that has an additional API layer in front of the backing database, which could explain why the error message was so different.

**Comment by sevenpixels** [comment]
It was a M2 cluster, $9/mo. I'm in the middle of trying to get it switched over to M10 which allows for 4.2.

**Comment by jmikola** [comment]
> It was a M2 cluster, $9/mo.

Thanks for clarifying. I should have specified "shared tier" instead of "free" in my last post. I'll follow up with Atlas folks via an internal channel to let them know about the error message inconsistency.

**Comment by sevenpixels** [comment]
Thank you! That worked. So it was just the fact that I wasn't on 4.2, which was my fault for not checking that

Another question in relation to this. Is there a way to store the timestamp `new MongoDB\BSON\UTCDateTime` when a new min or max is updated in a min_updated and max_updated field? Using the $min and $max just does it on it's own but I don't know if there is a way to tell if it actually updated the field or not.

So that you could track the date and time that the high or low was recorded.

**Comment by jmikola** [comment]
For non-pipeline updates, MongoDB historically provided a [`$currentDate`](https://docs.mongodb.com/manual/reference/operator/update/currentDate/) operator to return the current date (the same BSON type as PHP's UTCDateTime). An equivalent feature for the aggregation framework was introduced by [SERVER-23656](https://jira.mongodb.org/browse/SERVER-23656) in server version 4.2: the [`$$NOW`](https://docs.mongodb.com/manual/reference/aggregation-variables/#variable.NOW) variable.

I don't have any examples to refer you to, but I expect you can use a combination of `$$NOW` with [conditional operators](https://docs.mongodb.com/manual/reference/operator/aggregation/#conditional-expression-operators) to accomplish your goal. I expect the solution may be a bit convoluted since you'll need to determine if either `$min` or `$max` actually changed the document by preferring `$score` over the existing `$low_score` or `$high_score` field value, respectively. That said, don't feel pressured to try to put all of this logic into a single `$set` stage if you think it may be easier to use a series of [stages](https://docs.mongodb.com/manual/release-notes/4.2/#update-and-aggregation) to keep the code more readable. For example, you could compare `$low_score` and `$score` in one stage and conditionally set an `updatedAt` field to `$$NOW` (likewise for `$high_score`) and then do the `$min` and `$max` stuff in a subsequent, separate stage.

**Comment by sevenpixels** [comment]
Ok thanks. Appreciate the help.
