### ISSUE TITLE
Why this Library uses BulkWrite instead of Command to Insert/Update/Delete One document?

### ISSUE THREAD

**Issue by AbdulJabbarDumrai** [mongodb/mongo-php-library#737]
I was going through the codes and found that this library uses BulkWrite to even insert/update or delete One document while there is a better alternate provided by Mongo Driver to use Command.

BulkWrite has more overhead then Command. And as per documentation, BulkWrite is better when there are multiple queries to execute in order/un-ordered fashion.

Am I wrong or is there a particular reason which I am unaware of to use BulkWrite instead of Command? Thanks in anticipation.

For References:

https://github.com/mongodb/mongo-php-library/blob/master/src/Operation/InsertOne.php
https://docs.mongodb.com/manual/reference/command/insert/#dbcmd.insert
https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/
https://www.php.net/manual/en/class.mongodb-driver-command.php

**Comment by jmikola** [comment]
libmongoc, on which the `mongodb` extension depends, advises against using the generic command helpers for insert, update, and delete operations. This is primarily because these commands have special processing needs (e.g. validation, automatic batching, assembling result objects), which the generic command runners would not satisfy. The libmongoc docs does advise against using generic command runners, such as [Basic Write Operations](http://mongoc.org/libmongoc/current/mongoc_collection_write_command_with_opts.html#basic-write-operations) for the collection command helper. The PHP extension docs also repeat this advise ([`Manager::executeWriteCommand`](https://www.php.net/manual/en/mongodb-driver-manager.executewritecommand.php) pointing users to `executeBulkWrite`).

Despite "bulk" appearing the name, the libmongoc API (and wrapping PHP extension API) are still suitable for running individual write operations. The API is just designed to _allow_ for additional operations (of either the same or different operation types). While libmongoc does provide additional single-operation methods in its collection API, those methods and its bulk API both end up utilizing the same code in [`mongoc-write-command.c`](https://github.com/mongodb/mongo-c-driver/blob/master/src/libmongoc/src/mongoc/mongoc-write-command.c) to actually execute commands. Since one of the goals of the PHP extension was to keep its API as basic as possible and offload higher-level APIs to this library, we decided to implement a single BulkWrite API that could be used for both single and multiple write operations.

> And as per documentation, BulkWrite is better when there are multiple queries to execute in order/un-ordered fashion.

Since you linked to the MongoDB shell documentation in your original post, I assume that was inferred from the shell documentation (do correct me if I'm wrong). I'm not aware of that claim being made anywhere in the libmongoc or PHP extension documentation. Whenever possible, it's preferable to refer to individual driver documentation instead of shell APIs. Note that I'm referring to shell methods such as [`db.collection.bulkWrite/`](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/) here; other manual docs such as [command documentation](https://docs.mongodb.com/manual/reference/command/) do not have this issue, as they're documenting the server API (used by _both_ shell and driver).

**Comment by AbdulJabbarDumrai** [comment]
Since you have provided a in-depth details around the Library and Driver. I think I need to invest some time on it. Doing some research on your provided links and understanding it. 

And really appreciate for such detailed notes. That really help in better delivery.

**Comment by AbdulJabbarDumrai** [comment]
Since you have provided a in-depth details around the Library and Driver. I think I need to invest some time on it. Doing some research on your provided links and understanding it.

And really appreciate for such detailed notes. That really help in better delivery.

> libmongoc, on which the `mongodb` extension depends, advises against using the generic command helpers for insert, update, and delete operations. This is primarily because these commands have special processing needs (e.g. validation, automatic batching, assembling result objects), which the generic command runners would not satisfy. The libmongoc docs does advise against using generic command runners, such as [Basic Write Operations](http://mongoc.org/libmongoc/current/mongoc_collection_write_command_with_opts.html#basic-write-operations) for the collection command helper. The PHP extension docs also repeat this advise ([`Manager::executeWriteCommand`](https://www.php.net/manual/en/mongodb-driver-manager.executewritecommand.php) pointing users to `executeBulkWrite`).
> 
> Despite "bulk" appearing the name, the libmongoc API (and wrapping PHP extension API) are still suitable for running individual write operations. The API is just designed to _allow_ for additional operations (of either the same or different operation types). While libmongoc does provide additional single-operation methods in its collection API, those methods and its bulk API both end up utilizing the same code in [`mongoc-write-command.c`](https://github.com/mongodb/mongo-c-driver/blob/master/src/libmongoc/src/mongoc/mongoc-write-command.c) to actually execute commands. Since one of the goals of the PHP extension was to keep its API as basic as possible and offload higher-level APIs to this library, we decided to implement a single BulkWrite API that could be used for both single and multiple write operations.
> 
> > And as per documentation, BulkWrite is better when there are multiple queries to execute in order/un-ordered fashion.
> 
> Since you linked to the MongoDB shell documentation in your original post, I assume that was inferred from the shell documentation (do correct me if I'm wrong). I'm not aware of that claim being made anywhere in the libmongoc or PHP extension documentation. Whenever possible, it's preferable to refer to individual driver documentation instead of shell APIs. Note that I'm referring to shell methods such as [`db.collection.bulkWrite/`](https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/) here; other manual docs such as [command documentation](https://docs.mongodb.com/manual/reference/command/) do not have this issue, as they're documenting the server API (used by _both_ shell and driver).

Since you have provided a in-depth details around the Library and Driver. I think I need to invest some time on it. Doing some research on your provided links and understanding it.

And really appreciate for such detailed notes. That really help in better delivery.
