### ISSUE TITLE
Get collection statistics (PHP 7.3)

### ISSUE THREAD

**Issue by toaomatis** [mongodb/mongo-php-library#744]
Hi,

For statistic / archiving reasons we need to keep track of the total number of documents in several collections. 
For now we use the [countDocuments()](https://docs.mongodb.com/php-library/v1.6/reference/method/MongoDBCollection-countDocuments/index.html) function exposed by the library.

We don't need the `$filter` nor `$options` fields. Yet it creates quite a large aggregate pipeline for traversing the collection:
```
MongoDB\Operation\Aggregate Object
(
    [databaseName:MongoDB\Operation\Aggregate:private] => databaseName
    [collectionName:MongoDB\Operation\Aggregate:private] => collectionName
    [pipeline:MongoDB\Operation\Aggregate:private] => Array
        (
            [0] => Array
                (
                    [$match] => stdClass Object
                        (
                        )

                )

            [1] => Array
                (
                    [$group] => Array
                        (
                            [_id] => 1
                            [n] => Array
                                (
                                    [$sum] => 1
                                )

                        )

                )

        )

    [options:MongoDB\Operation\Aggregate:private] => Array
        (
            [readPreference] => MongoDB\Driver\ReadPreference Object
                (
                    [mode] => primary
                )

            [allowDiskUse] => 
            [useCursor] => 1
        )

)
```
We have several collections which contain over 20 million documents each. It takes over 30 seconds to run the aggregate above, while running either of these two commands in the MongoDB shell executes within milliseconds:
`db.getCollection('collectionName').stats()` 
`db.getCollection('collectionName').find({}).count()`

All three commands / queries generate the exact same answer. 
Is there a way to achieve either of the latter two calls from PHP without the need of an aggregate? 

I'm using version `1.6.0` of the library. Our MongoDB version is `3.4.20`

Many thanks in advance!

Matis

**Comment by alcaeus** [comment]
The CRUD specification has a section on the [Count API](https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#count-api-details). To quote:
> The count() helper is deprecated. It has always been implemented using the count command. The behavior of the count command differs depending on the options passed to it and may or may not provide an accurate count. When no query filter is provided the count command provides an estimate using collection metadata.

This is the main reason why there is a `countDocuments` and `estimatedDocumentCount` helper. If you want to get a **precise** number of the documents in a collection, or want to only count some of them, use `countDocuments`. This will create the aggregation pipeline you saw above and doesn't suffer from the flaws of the `count` command.

If you want an **estimated** number of documents and don't need filters, you can use the `estimatedDocumentCount` helper. This will look at the collection metadata to give you a number of documents, but this number may be off, for example due to orphaned documents or chunk migrations in sharded clusters.
