### ISSUE TITLE
updateOne with objectid?

### ISSUE THREAD

**Issue by eparlier** [mongodb/mongo-php-library#75]
Seems like there is noway to update a document based on its objectId.

hard-coded example:

$collection->updateOne(['_id' => '567eba6ea0b67b21dc004687'], ['$set' => ['some_property' => 'some_value']]);

Won't update. How to update by id?

**Comment by jmikola** [comment]
I don't believe this is any different than the legacy driver. The criteria you've defined is attempting to match an `_id` with the string value "567eba6ea0b67b21dc004687". You likely want to match on `new MongoDB\BSON\ObjectID("567eba6ea0b67b21dc004687")`. The same applies to other BSON types (e.g. matching on a date field would require you to use our BSON date object in your criteria).

Feel free to close this issue if that resolves it.

**Comment by eparlier** [comment]
Yup that solves my issue, thank you for replying

**Comment by bujardeari** [comment]
and how do you import MongoDB\BSON\ObjectID , i have a Slim application and have installet mongodb extension via composer  , but it cant find MongoDB\BSON\ObjectID class

**Comment by jmikola** [comment]
@bujardeari: [`MongoDB\BSON\ObjectID`](http://php.net/manual/en/class.mongodb-bson-objectid.php) is provided in the `mongodb` PECL extension. This is not to be confused with the [`mongodb/mongodb`](https://packagist.org/packages/mongodb/mongodb) package. Composer is used for installing packages but does not currently install PECL extensions. That said, it _can_ enforce the `mongodb/mongodb` package's [requirement](https://github.com/mongodb/mongo-php-library/blob/1.4.2/composer.json#L16) that the `mongodb` extension be installed on the system.

If your system does not currently have the `mongodb` extension installed, please follow one of the [installation procedures](http://php.net/manual/en/mongodb.installation.php) in the manual. Note that PHP web and CLI environments may have separate configuration files, so it's possible the extension is installed for a CLI environment, which Composer would use for checking requirements, but not a web SAPI where you may be trying to run your application.

In the future, please open a new GitHub issue rather than commenting on an old, closed thread. This will help ensure that your question gets seen and also avoid adding off-topic questions to a previous thread (in this case, the OP was asking about `updateOne` behavior and your question pertains to a missing class). You can always link back to an old issue for context if that would help.

**Comment by bujardeari** [comment]
it had it installed, the problem was only that after version 1.3 it was renamed to MongoDB\BSON\ObjectId and the previous one was MongoDB\BSON\ObjectID , and that confused me to try different things until i noticed the change.  However thank you for your description

**Comment by jmikola** [comment]
> the problem was only that after version 1.3 it was renamed to MongoDB\BSON\ObjectId and the previous one was MongoDB\BSON\ObjectID

Ah, that was indeed change in 1.3.0 with [PHPC-1004](https://jira.mongodb.org/browse/PHPC-1004). I obviously didn't give that much thought given that I referred to it as "ObjectID" in my last comment :smile: 

That said, I'm not sure how this came up for you, as class names in PHP are case-insensitive. We would not have made the change otherwise, as it would have been a BC break.

**Comment by bujardeari** [comment]
I was using it from within a Slim 3 application controller class, and that
made the difference.

**Comment by lindelius** [comment]
Until the class files have been either manually included or autoloaded, both namespaces and classes are case-sensitive. However, this shouldn't affect the driver classes since they are loaded instantly along with all other extensions.

@bujardeari Are you sure that the extension was properly loaded before when you experienced the class name issue?
