### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method MongoDB\Driver\Cursor::next()

### ISSUE THREAD

**Issue by ziyaindia** [mongodb/mongo-php-library#753]
**I have implemented following code:**

**To fetch collection by below function:**

```php
function searchQuery($collection, $limit, $filter = array(), $field = array()) {

            $options = array();
            if(!$limit) {
                $options = array(
                    "sort" => array("date" => -1)
                );
            } else {
                $options = array(
                    "sort" => array("date" => -1),
                    "limit"=> $limit
                );
            }

            $query = $this->get_dbquery($filter, $options);
            $this->cursor = $this->manager->executeQuery("$this->dbf.$collection", $query);
            $this->iterator = new IteratorIterator($this->cursor);
        }
```

**When a function needs next available records in a collection then i am calling following function:**

```php
function get_result_row () {

            if ($this->cursor->isDead()) {
                return $this->iterator->next();
            }
            return false;
        }
```

**I am getting following error:**

Fatal error: Uncaught MongoDB\Driver\Exception\RuntimeException: Cannot advance a completed or failed cursor. in /var/www/html/fnsv5/php/Database/mongoDatabase.php:59 Stack trace:

```
#0 /var/www/html/fnsv5/php/Database/mongoDatabase.php(59): IteratorIterator->next()
#1 /var/www/html/fnsv5/php/Database/mongoQueries.php(137): MONGODATABASE->get_result_row()
#2 /var/www/html/fnsv5/php/Database/reportingQueries.php(579): mongoQueries->getNextRecord() #3 /var/www/html/fnsv5/php/Database/reportingQueries.php(98): reportingQueries->reports_nextLocation()
#4 /var/www/html/fnsv5/php/Fleet/Reports/geofence.php(777): reportingQueries->reports_nextEvent()
#5 /var/www/html/fnsv5/php/Fleet/Reports/geofence.php(849): GEOFENCE_FNSv3_Report->computeParameters('944360', Array, Array)
#6 /var/www/html/fnsv5/php/Fleet/Reports/geofence.php(882): GEOFENCE_FNSv3_Report->getReportData()
#7 /var/www/html/fnsv5/php/Fleet/reportGeneration.php(229): GEOFENCE_FNSv3_Report->execute()
#8 /var/www/html/fnsv5/php/Administrator/admin.php(772): reportGenerati in /var/www/html/fnsv5/php/Database/mongoDatabase.php on line 59
```

Please suggest what I am doing wrong.

Thanks in Advance

**Comment by jmikola** [comment]
### Background information on `Cursor::isDead`

[`Cursor::isDead()`](https://github.com/mongodb/mongo-php-driver/blob/1.7.4/src/MongoDB/Cursor.c#L374) is a proxy for libmongoc's [`mongoc_cursor_more()`](https://github.com/mongodb/mongo-c-driver/blob/master/src/libmongoc/src/mongoc/mongoc-cursor.c#L1300) function, which returns whether the cursor's internal state is "done". The documentation for [`Cursor::isDead()`](https://www.php.net/manual/en/mongodb-driver-cursor.isdead.php) goes into more detail about what "done" implies, and makes the very important point that the driver can only definitively report that a cursor has _no_ more results (i.e. "done", or "dead" to use PHP method terminology), but it cannot do the opposite and definitively say whether a cursor has more results. If a cursor is not "dead", it may _potentially_ have more results, but confirming that may require communicating with the server, which `mongoc_cursor_more()` does not do (it only inspects the client-side state of the cursor).

If you're wondering what the point of this function is for regular queries, you're on the right track. Once we reach the end of a result set for a regular query, as you are doing here, the cursor is assuredly "dead". As noted in [its documentation](https://www.php.net/manual/en/mongodb-driver-cursor.isdead.php), `Cursor::isDead()` is primarily intended to be used for special, tailable cursors, where a driver might repeatedly ask the server for more results (as one might tail a log file from a CLI). In the context of tailable cursors, a cursor may not have any results on the client-side but may _potentially_ have more results if we ask the server for more.

### Exception message

The "Cannot advance a completed or failed cursor" error message originates from [`mongoc_cursor_next()`](https://github.com/mongodb/mongo-c-driver/blob/1.16.2/src/libmongoc/src/mongoc/mongoc-cursor.c#L1240), which is called from the PHP driver when the cursor's position is advanced (either by `foreach` or directly from `IteratorIterator::next()`, as in your example). We can expect this error in your implementation of `get_result_row` because you're essentially asking the driver if the cursor is "dead" (i.e. definitely no more results) and then attempting to advance to the next result (where there is none).

### Using IteratorIterator for regular queries

This brings me back to the [Wrapping a Normal Cursor](https://docs.mongodb.com/php-library/current/tutorial/tailable-cursor/#wrapping-a-normal-cursor) documentation I referenced in #703. The following paragraph is key, since `foreach` is the proper model of iteration that we want to manually perform:

> While this example is quite concise, there is actually quite a bit going on. The foreach construct begins by rewinding the iterable ($cursor in this case). It then checks if the current position is valid. If the position is not valid, the loop ends. Otherwise, the current key and value are accessed accordingly and the loop body is executed. Assuming a break has not occurred, the iterator then advances to the next position, control jumps back to the validity check, and the loop continues.

Rather than use `Cursor::isDead()`, we can rely on the IteratorIterator methods alone. In the following example, I'm using the [PHP library](https://github.com/mongodb/mongo-php-library) instead of the extension directly, as it has a more convenient API (and one that [closely resembles](https://docs.mongodb.com/php-library/current/upgrade/) the legacy extension). That said, the cursor object returned from `find()` here is the very same object you receive from `Manager::executeQuery()` in the `mongodb` extension.

```php
<?php

require_once 'vendor/autoload.php';

$client = new MongoDB\Client();
$collection = $client->test->foo;

$collection->drop();
$collection->insertMany([
  ['x' => 1],
  ['x' => 2],
  ['x' => 3],
]);

$cursor = $collection->find(['x' => ['$lt' => 3]]);
$iterator = new IteratorIterator($cursor);

/* A new cursor's position points before the first element, so we must rewind
 * to advance to the first position. However, it's still possible that there is no
 * element at that position so we won't attempt to access the data just yet. */
$iterator->rewind();

/* The valid() method tells us if it's safe to read the current position. Therefore,
 * we'll call this at every step of the loop. For our first iteration, this is just after
 * we rewound the cursor (advancing it to its first position). On subsequent
 * iterations, valid() will be called just after next(), which is the final instruction
 * in the loop body. */
while ($iterator->valid()) {
  /* current() returns whatever is at the current position. This is entirely a
   * client-side operation. */
  $document = $iterator->current();
  var_dump($document);
  /* next() advances to the next element, and potentially communicates with
   * the server. Doing this at the end of the loop is akin to doing `$i++` in a
   * basic for loop. */
  $iterator->next();
}
```

Running this script will print the first two documents, `{x: 1}` and `{x: 2}`.

If you want to replace the complete iteration of the `while` loop with a `get_result_row()` function, we have two options:

 * Have `get_result_row()` take the `IteratorIterator` as an argument, check `valid()`, and return `current()` if there is a valid document to read. If `valid()` was `false`, you can return whatever "empty" value you prefer (e.g. `false`, `null`).
 * Do the same as above, but also have `get_result_row()` advance the cursor position before it would return a valid document. And do not advance otherwise, lest we get an "Cannot advance a completed or failed cursor" error.

The first design would essentially be read-only function that you could call multiple times to read the same document without affecting the cursor's state, and you would need to call `$iterator->next()` between calls to `get_result_row()` to advance positions.

```php
// ...
$iterator = new IteratorIterator($cursor);
$iterator->rewind(); // Rewinding is still necessary to advance to the first position

$firstDocument = get_result_row($iterator);
// This works because get_result_row doesn't advance anything
$anotherInstanceOfTheFirstDocument = get_result_row($iterator);

$iterator->next();

$secondDocument = get_result_row($iterator);
```

In the second design, you could just call `get_result_row()` multiple times and have it return the full sequence of documents in the result set and then decide to stop if it ever returns your "empty" value.

```php
// ...
$iterator = new IteratorIterator($cursor);
$iterator->rewind();

$firstDocument = get_result_row($iterator);
$secondDocument = get_result_row($iterator);
```

If you are attempting to mimic the API of [`mysqli_fetch_row()`](https://www.php.net/manual/en/mysqli-result.fetch-row.php), I believe you'd want the second implementation as that function looks to advance the result set on each invocation.

**Comment by ziyaindia** [comment]
`function connect($username,$password,$hostname,$port, $dbname) {

            $this->serverString = "mongodb://".$username.":".$password."@".$hostname.":".$port."/".$this->dbf;

            try {
                $this->manager = new \MongoDB\Driver\Manager($this->serverString, array("connectTimeoutMS" => MONGO_CURSOR_TIMEOUT));
            } catch (Exception $e) {
                die('MongoDB NOT WORKING ERROR CODE '.$e->getCode().' ERROR MESSAGE '.$e->getMessage());
            }

            $this->uname = $username;
            $this->pass = $password;
            $this->dbf = $dbname;

            return $this->manager;
        }`

**Comment by jmikola** [comment]
[`MongoDB\Client`](https://docs.mongodb.com/php-library/current/reference/class/MongoDBClient/) in the library is the equivalent of [`MongoDB\Driver\Manager`](https://www.php.net/manual/en/class.mongodb-driver-manager.php) in the `mongodb` extension. The library builds upon the extension, so if you are using the library you can create a Client object in lieu of a Manager. The Client takes the same options (and some extras), as you'll find discussed in the documentation for [its constructor](https://docs.mongodb.com/php-library/current/reference/method/MongoDBClient__construct/).
