### ISSUE TITLE
InsertMany documents is not a list

### ISSUE THREAD

**Issue by klikpaspor** [mongodb/mongo-php-library#754]
```
public function Insert(string $collection, array $data){
        $client = new Client(
            'mongodb://'.urlencode('username').':'.urlencode('password').'@localhost:27017/?authSource=admin&authMechanism=SCRAM-SHA-256'
        );
        $insert = $client->inboxno->$collection;
        return $insert->insertMany($data);
    }
```

```
$b = self::Insert('users', array('username' => 'coba'));
print $b;
```

i'm got error `$documents is not a list (unexpected index: "username")`

```
D:\Db\vendor\mongodb\mongodb\src\Operation\InsertMany.php on line 95
foreach ($documents as $i => $document) {
            if ($i !== $expectedIndex) {
                throw new InvalidArgumentException(sprintf('$documents is not a list (unexpected index: "%s")', $i));
            }

            if (! is_array($document) && ! is_object($document)) {
                throw InvalidArgumentException::invalidType(sprintf('$documents[%d]', $i), $document, 'array or object');
            }

            $expectedIndex += 1;
        }
```

**Comment by jmikola** [comment]
This exception is expected as you are passing an associative array (a "document") to a method that expects a _list_ (or sequence/vector) of documents. You can review the [`InsertMany` constructor`](https://github.com/mongodb/mongo-php-library/blob/81a57c0d1fca902ae74eb4ae24f4ca23dbb08782/src/Operation/InsertMany.php#L85) to see how the library detects this and decides to raise the exception.

In your case, you would need to encapsulate the document in an array (e.g. `[['username' => 'coba']]`) instead of passing it on its own. That said, if you're just inserting a single document you should utilize the `insertOne` method instead of `insertMany`.

Contrast the examples for [`Collection::insertOne()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-insertOne/#example) and [`insertMany()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-insertMany/#example).
