### ISSUE TITLE
[Question] Failed to send "count" command with database "dbname": socket error or timeout

### ISSUE THREAD

**Issue by apsbd** [mongodb/mongo-php-library#757]
I have been running MongoDB in my Amazon since 2019. It has over millions of data and it was working fine until yesterday. But today when I try to query using Laravel jenssegers eloquent model it gives me this error:

Failed to send "count" command with database "dddb": socket error or timeout

```
at /var/www/html/console/vendor/mongodb/mongodb/src/Operation/Count.php:154
150| if (isset($this->options['readConcern']) && ! \MongoDB\server_supports_feature($server, self::$wireVersionForReadConcern)) {
151| throw UnsupportedException::readConcernNotSupported();
152| }
153|

154| $cursor = $server->executeReadCommand($this->databaseName, new Command($this->createCommandDocument()), $this->createOptions());
155| $result = current($cursor->toArray());
156|
157| // Older server versions may return a float
158| if ( ! isset($result->n) || ! (is_integer($result->n) || is_float($result->n))) {
```

Exception trace:

```
1 MongoDB\Driver\Server::executeReadCommand("dbname", Object(MongoDB\Driver\Command), [Object(MongoDB\Driver\ReadPreference)])
/var/www/html/console/vendor/mongodb/mongodb/src/Operation/Count.php:154

2 MongoDB\Operation\Count::execute(Object(MongoDB\Driver\Server))
/var/www/html/console/vendor/mongodb/mongodb/src/Collection.php:277
```

Please use the argument -v to see more details.

It would be really very helpful if you give me a solution.

Thanks in advance

**Comment by jmikola** [comment]
@apsbd: Please share the complete exception (class and full message). Also, please confirm if this exception is easily reproducible or whether this is an occasional exception.

From what you've shared already, I can tell you that a "socket error of timeout" indicates that the command either took too long to execute (beyond the driver's `socketTimeoutMS` option, which defaults to 300 seconds unless you've modified it) or the connection was dropped/interrupted for some other reason. It's unlikely that the issue originated in the driver or your application.

Additionally, it may be helpful to share more details about your deployment and the operation you're running. Off the top of my head, the following may be helpful:

 * Share your connection string (redact any sensitive information) so we can see any options being set at the client-level. If you are also provided database or collection-level options (e.g. custom read preference), share those as well.
 * Describe the full `count` command that you are executing. Share the query filter and any additional options being passed. How many seconds does the operation take to execute before it succeeds or raises an exception?
 * Describe the collection on which the operation is running. How many documents are in the collection in total and how many do you expect to be counted?
 * Share any indexes on the collection and indicate whether the `count` command is using one of these indexes.
 * If possible, share output from the [`explain`](https://docs.mongodb.com/manual/reference/command/explain/) command for the `count` command you're running, which may provide much of the above and tell us which index is likely to be used.
 * Share details about the MongoDB deployment. Is this a replica set or a sharded cluster? If a replica set, is the query being issued against the primary or a secondary?
 * Attempt to run the equivalent `count` operation in the MongoDB shell when connected to the same server and share the result and timing for the operation to execute.

**Comment by apsbd** [comment]
@jmikola Thanks for your reply. 

- I installed MongoDB in my AWS EC2 instance (t2.2xlarge 8 core 32 GiB RAM) and kept all default settings in the /etc/mongodb.conf (Only Auth is enabled, and IP is bind to the localhost only).
-  The database is running as a stand-alone deployment and I've over 1 Billion documents in a single collection. The instance is running on Amazon Linux and it was working great until few days ago it shows me this error while I tried to run a command from Laravel CLI. 
- The database is running in the localhost and the auth is enabled and the authentication database is admin.
- I've 6 Indexes but no indexes were used in the ```count``` and it's working fine from the MongoDB shell. Only I got this error when I try the same count/query from the Laravel CLI. 
- I'm expecting around 325M of the count. 

The strange part is it was working fine before and all of a sudden it stops working. I'm no expert in setup MongoDB so any help is appreciable.

Here's the gist of my Laravel Command Code that gives me the error: 

```
protected $filter = ["date_added" => ["$type" => "string", "$ne"=> ""]];

public function handle()
{
        $db = DB::connection('mongodb');

        $collection = $db->selectCollection('contacts_collection');
        $cursor = $collection->find($this->filter);
        $total = $collection->count($this->filter);
        ......
        ......
}
```

Thanks

**Comment by jmikola** [comment]
Some more info missing from my previous request:

 * Share your connection string (redact any sensitive information) so we can see any options being set at the client-level. If you are also provided database or collection-level options (e.g. custom read preference), share those as well.
 * How many seconds does the operation take to execute before it succeeds or raises an exception? Report this for _both_ the MongoDB shell and the PHP driver.
 * Share output from the explain command for the count command you're running.

The [`Collection::explain()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-explain/#examples) documentation has an example, which happens to use the count command. Please run that from PHP and share a `var_dump()` of the output. In your case, you'd want to replace the third argument to the `Count` constructor with your query filter.

It's quite possible that an unindexed count operation on a collection with more than a billion documents is timing out due to a socket timeout. I don't know offhand if the shell enforces a socket timeout, but the PHP driver does default to 300 seconds as noted in my last comment.

In any event, answers to the second and third bullets above should help narrow this down. If you are hitting a socket timeout from PHP, the fact that it's a CLI environment would support that. Most web SAPIs would time out the request after 30 seconds (long before the driver's 300 second default), but I believe the CLI has no limit of PHP execution time, which would allow you to hit the driver's socket timeout.

I expect the ultimate solution is going to be creating an index to accommodate this query filter.

**Comment by apsbd** [comment]
@jmikola Here's what you've asked for:

- Connection String:
This is what I get when I try to get the connection from my PHP client
```
MongoDB\Client {#4128
    manager: MongoDB\Driver\Manager {#4127},
    uri: "mongodb://localhost:27017/admin",
    typeMap: [
        "array" => "MongoDB\Model\BSONArray",
        "document" => "MongoDB\Model\BSONDocument",
        "root" => "MongoDB\Model\BSONDocument",
    ],
    writeConcern: MongoDB\Driver\WriteConcern {#4124},
}
```
Let me know if this is correct or how I can get the connection string correctly. 

- MongoDB\Collection::explain from PHP client:
```
MongoDB\Operation\Count^ {#4151
  -databaseName: "mydb"
  -collectionName: "mycollection"
  -filter: array:1 [
    "date_added" => array:2 [
      "$type" => "string"
      "$ne" => ""
    ]
  ]
  -options: []
}

>>> $result = $collection->explain($count);                                                                

MongoDB/Driver/Exception/ConnectionTimeoutException with message 'Failed to send "explain" command with database "mydb": Failed to read 4 bytes: socket error or timeout'

```

- Explain from MongoDB shell 

```
{
        "queryPlanner" : {
                "plannerVersion" : 1,
                "namespace" : "mydb.contacts_collection",
                "indexFilterSet" : false,
                "parsedQuery" : {
                        "$and" : [
                                {
                                        "$nor" : [
                                                {
                                                        "date_added" : {
                                                                "$eq" : ""
                                                        }
                                                }
                                        ]
                                },
                                {
                                        "date_added" : {
                                                "$type" : [
                                                        2
                                                ]
                                        }
                                }
                        ]
                },
                "winningPlan" : {
                        "stage" : "COUNT",
                        "inputStage" : {
                                "stage" : "COLLSCAN",
                                "filter" : {
                                        "$and" : [
                                                {
                                                        "$nor" : [
                                                                {
                                                                        "date_added" : {
                                                                                "$eq" : ""
                                                                        }
                                                                }
                                                        ]
                                                },
                                                {
                                                        "date_added" : {
                                                                "$type" : [
                                                                        2
                                                                ]
                                                        }
                                                }
                                        ]
                                },
                                "direction" : "forward"
                        }
                },
                "rejectedPlans" : [ ]
        },
        "executionStats" : {
                "executionSuccess" : true,
                "nReturned" : 0,
                "executionTimeMillis" : 835758,
                "totalKeysExamined" : 0,
                "totalDocsExamined" : 325981182,
                "executionStages" : {
                        "stage" : "COUNT",
                        "nReturned" : 0,
                        "executionTimeMillisEstimate" : 814353,
                        "works" : 325981184,
                        "advanced" : 0,
                        "needTime" : 325981183,
                        "needYield" : 0,
                        "saveState" : 2546769,
                        "restoreState" : 2546769,
                        "isEOF" : 1,
                        "invalidates" : 0,
                        "nCounted" : 280139059,
                        "nSkipped" : 0,
                        "inputStage" : {
                                "stage" : "COLLSCAN",
                                "filter" : {
                                        "$and" : [
                                                {
                                                        "$nor" : [
                                                                {
                                                                        "date_added" : {
                                                                                "$eq" : ""
                                                                        }
                                                                }
                                                        ]
                                                },
                                                {
                                                        "date_added" : {
                                                                "$type" : [
                                                                        2
                                                                ]
                                                        }
                                                }
                                        ]
                                },
                                "nReturned" : 280139059,
                                "executionTimeMillisEstimate" : 801643,
                                "works" : 325981184,
                                "advanced" : 280139059,
                                "needTime" : 45842124,
                                "needYield" : 0,
                                "saveState" : 2546769,
                                "restoreState" : 2546769,
                                "isEOF" : 1,
                                "invalidates" : 0,
                                "direction" : "forward",
                                "docsExamined" : 325981182
                        }
                }
        },
        "serverInfo" : {
                "host" : "ip-10-0-0-11",
                "port" : 27017,
                "version" : "3.6.18",
                "gitVersion" : "2005f25eed7ed88fa698d9b800fe536bb0410ba4"
        },
        "ok" : 1
}
```

- I've got a correction about Index. the date_added field above is an index. I've checked and made sure. 

- Could you please, let me know how to increase **socketTimeoutMS** from 300 seconds to something else in PHP settings. 

- I've created a test server with a smaller database with the same PC configuration and weirdly enough, it's showing the exact error. As I mentioned before, this query was working fine in the main server before a few days earlier. 

- Also, after fixing this error, I'd like to take some professional advice as consultancy (paid) from you, if you are interested. 

Thanks in advance.

**Comment by jmikola** [comment]
Looking at the MongoDB shell's output, I see `"executionTimeMillis" : 835758`. That figure definitely exceeds the 300 second default in the PHP driver.

`socketTimeoutMS` is a connection string option, so you can either specify it in the connection string directly (e.g. `mongodb://example.com/?socketTimeoutMS=123456`) or via the second options array parameter to the Manager or Client constructors. See [`Client::__construct()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBClient__construct/) docs, which describe how to specify options. That page references [`Manager::__construct()`](https://www.php.net/manual/en/mongodb-driver-manager.construct.php) for docs on the supported options themselves to avoid duplication, since they are all implemented in the base extension (apart from `typeMap`, which is something supported in the Client constructor's third parameter).

That said, the query is only dealing with the `date_added` field, so I think the best course of action would be to [create an index](https://docs.mongodb.com/manual/indexes/) on that field. This should avoid the need to do a very expensive [collection scan](https://stackoverflow.com/a/21667451/162228) in favor of an index scan, which would hopefully all be in memory. Ultimately, this could reduce the execution time from 800+ seconds down to just a few seconds (if that).

Lastly, I don't have any availability for side work, but MongoDB definitely offers consulting services and could deal with analyzing an existing applications and making performance/schema recommendations. Please see https://www.mongodb.com/products/consulting if you're interested in pursuing that.

**Comment by apsbd** [comment]
@jmikola Thank you very much for your time and help. I really appreciated it. 

I've been able to fix this issue by setting executionTimeMillis in the options. That's really awesome :)

Again, thanks for your awesome help.

Regards, 
Ahmed
