### ISSUE TITLE
PHP operation mongodb, how to join the table query

### ISSUE THREAD

**Issue by cyesky** [mongodb/mongo-php-library#767]

**Comment by jmikola** [comment]
If you have general questions about using MongoDB, those would be better suited for the [community forums](https://developer.mongodb.com/community/forums/) or Stack Overflow. GitHub and JIRA issues on the PHP projects should be reserved for bug reports or technical questions specifically about the PHP driver.

That said, [How to join multiple collections with $lookup in mongodb
](https://stackoverflow.com/q/35813854/162228) on Stack Overflow may answer your question.

If you have additional information to add to this question that would make it relevant to the PHP driver, please follow up or edit the original post. Otherwise, I'll circle back tomorrow and close this issue.
