### ISSUE TITLE
composer issue

### ISSUE THREAD

**Issue by pjebs** [mongodb/mongo-php-library#82]
I am testing my app on both php 7 and hhvm.

I have successfully installed the relevant mongodb.so extension.
`composer require "mongodb/mongodb=^1.0.0@beta"`
I noticed that when I use php 7 to run composer update, it installs `mongodb/mongodb (1.0.0-beta2)`.
The same code running MongoDB then works on php 7 BUT does not work on HHVM: 

error: `Fatal error: Call to undefined method MongoDB\\Driver\\Manager::getReadConcern() in /home/vagrant/Code/ICO2/vendor/mongodb/mongodb/src/Collection.php on line 105`

When I use hhvm to run composer update, it removes `1.0.0-beta2` and installs `1.0.0-beta1`.
The same code then WORKS on php 7 and hhvm.

What is going on? Is there are breaking change in the `beta2` library?

**Comment by jmikola** [comment]
This is due to the ReadConcern class not yet being implemented in the HHVM driver (see: [HHVM-145](https://jira.mongodb.org/browse/HHVM-145)). @derickr and I actually spoke about this earlier in the week, and it's definitely on his radar before tagging a 1.1.x release candidate.

On a somewhat unrelated note: we've been holding off on a stable release for HHVM due to an outstanding memory corruption bug we've been tracking.

**Comment by jmikola** [comment]
I'm going to close this out as [HHVM driver 1.1.0RC1](https://github.com/mongodb/mongo-hhvm-driver/releases/tag/1.1.0RC1) has been released and is now consistent with the 1.1.x API of the PHP driver). HHVM's memory corruption bug still has not been resolved, which is why it's an RC instead of stable release. Feel free to follow up if there's still an issue.
