### ISSUE TITLE
Aggregation $setWindowFields with $rank - (None) must be specified with '{}' as the value

### ISSUE THREAD

**Issue by lachlanhickey** [mongodb/mongo-php-library#849]
### Bug Report

I've just upgraded to MongoDB 5.0 and have to say I'm loving the new features. $rank is making things a lot cleaner for my aggregations.

I receiving the following error when running $setWindowFields and $rank in PHP

>  (None) must be specified with '{}' as the value

### Environment

PHP7.4-FPM
ext 1.10 + lib 1.9

### Test Script

The following code runs in MongoDB shell 

    { 
            "$setWindowFields" : { 
                "partitionBy" : { 
                    "split" : "$split_id"
                }, 
                "sortBy" : { 
                    "time" : 1.0
                }, 
                "output" : { 
                    "position" : { 
                        "$rank" : { 

                        }
                    }, 
                    "leader" : { 
                        "$first" : "$time"
                    }
                }
            }
        }

The below in PHP produces the above error. 

    [
        '$setWindowFields' => [
            'partitionBy' => [
                'split' => '$split_id'
            ],
            'sortBy' => [
                'time' => 1.0
            ],
            'output' => [
                'position' => [
                    '$rank' => []
                ],
                'leader' => [
                    '$first' => '$time'
                ]
            ]
        ]
    ],

Is this a bug or just me not formatting the PHP correctly.

**Comment by jmikola** [comment]
Looking at the [server docs for `$rank`](https://docs.mongodb.com/manual/reference/operator/aggregation/rank/), it looks like an empty BSON document is always expected as its value. In your PHP example, you're specifying an empty array, which is going to serialize as an empty BSON array. The [Serialization to BSON](https://www.php.net/manual/en/mongodb.persistence.serialization.php) article in the extension documentation explains how different arrays serialize to BSON:

 * Packed arrays (i.e. the keys start at 0 and are sequential without gaps) become a BSON array
 * Non-packed arrays (i.e. having associative (string) keys, the keys don't start at 0, or when there are gaps) become a BSON object
 * A top-level (root) document, always serializes as a BSON document

I realize it may not have been clear that an empty array is considered "packed", so I just revised the documentation in https://github.com/php/doc-en/commit/d011dc842117a9dbd02b95a3d0a820d3d973ebfd.

If you'd like to guarantee that a BSON document is provided, the easiest way to do so is to specify an empty PHP object (e.g. `(object) []` or `new \stdClass`). Alternatively, you could use the library's [`MongoDB\Model\BSONDocument` class](https://docs.mongodb.com/php-library/current/reference/bson/), which will always serialize to a BSON document, but that has a bit more overhead since that's utilizing the [`MongoDB\BSON\Serializable`](https://www.php.net/manual/en/mongodb-bson-serializable.bsonserialize.php) interface.

**Comment by lachlanhickey** [comment]
Perfect @jmikola - `(object) []` has solved all my issues. 

Appreciate the prompt reply!
