### ISSUE TITLE
How to use collection that has dots in its name?

### ISSUE THREAD

**Issue by sshilko** [mongodb/mongo-php-library#86]
```
$cname = 'aaa.bbb';
$collection = new \MongoDB\Collection($manager, cname);
//results in database = aaa , collection = bbb 
//being used instead
```

**Comment by jmikola** [comment]
The Collection constructor takes a [namespace](https://docs.mongodb.org/manual/faq/developers/#faq-dev-namespace) as its second argument. This string is exploded on a dot character into two parts to yield the database and collection names.

If you had a collection named "aaa.bbb" in the "test" database, you would use "test.aaa.bbb" as the namespace. See [the implementation](https://github.com/mongodb/mongo-php-library/blob/80a0d523b61615a9532bbf62c0894dbb2a772c90/src/Collection.php#L79) for more details, along with some documentation above.

The `selectCollection()` methods on the Client and Database objects should also handle this for you, if you'd like to use those instead of constructing a Collection manually.
