### ISSUE TITLE
javascript function documentation

### ISSUE THREAD

**Issue by Bill-ColeUS** [mongodb/mongo-php-library#895]
### Bug Report
Apologies if this was documented somewhere else, but I can't find a way to perform a find() which contains a javascript function. I am trying to convert the following mongo shell command into PHP.

Unfortunately, I can't find any documentation that mentions this. I would appreciate some help and pointers.

Thank you.

```
db.collection.find(

	function() {

		var findKey = "someArray";
		var findVal = "someValueWithinTheArray";
		var parent = "";

		function inspectObj(doc) {

			return Object.keys(doc).some(function(key) {

				if( typeof(doc[key]) == "object" && doc[key] !== null) {

					parent = key;

					return inspectObj(doc[key]);

				}

				if( parent === findKey && doc[key] === findVal ) {

					return true;

				}

				return false;

			});

		}

		return inspectObj(this);

	}

)
```

### Environment
AlmaLinux 8.5
PHP 8.0.16
Mongo PHP Library 1.11.0
MongoDB 5.0.6 (mongodb-org-server-5.0.6-1.el8.x86_64)

```
mongodb
libbson headers version => 1.20.0
libbson library version => 1.20.0
libmongoc headers version => 1.20.0
libmongoc library version => 1.20.0
libmongoc SSL => enabled
libmongoc SSL library => OpenSSL
libmongoc crypto => enabled
libmongoc crypto library => libcrypto
libmongoc crypto system profile => enabled
libmongoc SASL => enabled
libmongoc ICU => enabled
libmongoc compression => enabled
libmongoc compression snappy => enabled
libmongoc compression zlib => enabled
libmongoc compression zstd => enabled
libmongocrypt headers version => 1.3.0
libmongocrypt library version => 1.3.0
libmongocrypt crypto => enabled
libmongocrypt crypto library => libcrypto
mongodb.debug => no value => no value
mongodb.mock_service_id => Off => Off
```

**Comment by jmikola** [comment]
This is the first time I've seen a function used as the `query` argument to [`db.collection.find()`](https://docs.mongodb.com/manual/reference/method/db.collection.find/). This doesn't even appear to be documented in the manual, so I decided to inspect the source code for the `find()` helper in a MongoDB 4.4.0 shell to see what's going on.

```
MongoDB Enterprise rs0:PRIMARY> db.foo.find
function(query, fields, limit, skip, batchSize, options) {
    var cursor = new DBQuery(this._mongo,
                             this._db,
                             this,
                             this._fullName,
                             this._massageObject(query),
                             fields,
                             limit,
                             skip,
                             batchSize,
                             options || this.getQueryOptions());

    {
        const session = this.getDB().getSession();

        const readPreference = session._getSessionAwareClient().getReadPreference(session);
        if (readPreference !== null) {
            cursor.readPref(readPreference.mode, readPreference.tags);
        }

        const readConcern = session._getSessionAwareClient().getReadConcern(session);
        if (readConcern !== null) {
            cursor.readConcern(readConcern.level);
        }
    }

    return cursor;
}
```

Here, we see the `query` argument is passed through a `db.collection._massageObject` function before being used to construct the internal DBQuery object. If we inspect the source of _that_ function we have:

```
MongoDB Enterprise rs0:PRIMARY> db.foo._massageObject
function(q) {
    if (!q)
        return {};

    var type = typeof q;

    if (type == "function")
        return {$where: q};

    if (q.isObjectId)
        return {_id: q};

    if (type == "object")
        return q;

    if (type == "string") {
        // If the string is 24 hex characters, it is most likely an ObjectId.
        if (/^[0-9a-fA-F]{24}$/.test(q)) {
            return {_id: ObjectId(q)};
        }

        return {$where: q};
    }

    throw Error("don't know how to massage : " + type);
}
```

When this function encounters a Javascript function, it wraps it in a new query document using the [`$where`](https://docs.mongodb.com/manual/reference/operator/query/where/) operator. Given that, I think the equivalent query in the PHP driver would be to pass the following as the `$filter` argument to [`MongoDB\Collection::find()`](https://docs.mongodb.com/php-library/current/reference/method/MongoDBCollection-find/):

```php
[ '$where' => new MongoDB\BSON\Javascript('...') ]
```

[MongoDB\BSON\Javascript](https://www.php.net/manual/en/class.mongodb-bson-javascript.php) is the corresponding BSON class for representing a Javascript function. It doesn't show up much in the server/driver documentation since the use of Javascript functions is not encouraged, but the [Store a JavaScript Function on the Server](https://docs.mongodb.com/manual/tutorial/store-javascript-function-on-server/) tutorial talks about the function as a BSON type, which can be used with query operators such as `$where` or stored directly in the server (like any other BSON type).

**Comment by Bill-ColeUS** [comment]
WOW

That is some excellent research and a detailed reply.

Thank you very much!
