### ISSUE TITLE
[question] Replacement fore MongoCode ?

### ISSUE THREAD

**Issue by Alsatian67** [mongodb/mongo-php-library#93]
I'm working on changing an app from old driver to this library with the new PHP driver.

I had some kind of code :

```
$func = 'db.BlogPost.find().forEach(function(doc){
            db.BlogPost.update(
                {_id:doc._id},
                {$set:{n: NumberLong(db.Comment.find({blogpost:doc._id}).count())}}
            );
        });'

$code = new \MongoCode($func);
$response = $db->execute($code);
```

I don't find any replacement for this MongoCode() feature is it intended ?

**Comment by jacqueswaller** [comment]
I think the `MongoDB\BSON\Javascript` class is the equivalent though I haven't used it yet.

**Comment by flashjay** [comment]
usage:
MongoDB\Database::command(['eval' =>"function() { return {$func}; }", 'args' => $args, 'nolock' => true])

**Comment by jmikola** [comment]
As @jacqueswaller suggested, [`MongoDB\BSON\Javascript`](http://php.net/mongodb-bson-javascript) class is the new driver's equivalent for the legacy MongoCode class. @flashjay's example appears to work because the server happens to accept a string for the [`eval` command](https://docs.mongodb.org/master/reference/command/eval/); however, I'm not sure if other JavaScript commands (e.g. [`mapReduce`](https://docs.mongodb.org/master/reference/command/mapReduce/)) do the same. Either way, I would suggest using the Javascript class in your application so not to depend on any undocumented server behavior.

As for the code example in the original question, there is really no need for Javascript evaluation in that scenario. You will generally be _much_ better off iterating on the blog posts in PHP and issuing multiple updates (via [BulkWrite](http://php.net/mongodb-driver-bulkwrite)). Using the [aggregation framework](https://docs.mongodb.org/master/core/aggregation-pipeline/), you can do this in a two-step operation (i.e. two round trips to the server):

1. Construct an aggregation pipeline to `$group` on the comments collection, using the blog ID as the bucket identifier (`$id`) and projecting a running count into a separate field (i.e. `{$sum: 1}`).
2. Create a BulkWrite object and append updates for each aggregate result, setting the blog post's `n` field accordingly.

The above situation would only handle blog posts with at least one comment, so you may want to lead with a mass update on blog posts to set `n` to zero for all posts. Alternatively, you can lead with a separate query for all blog post IDs to collect them and diff against the aggregation results. For each post not in the aggregation results, you could then explicitly set it to zero.

**Comment by Alsatian67** [comment]
@jmikola I just tried your method with aggregator, and it works fine.
Thank you very much for the explaination.
