### ISSUE TITLE
TLS connection with mongo cluster failed (while single host works)

### ISSUE THREAD

**Issue by HalleyUK** [mongodb/mongo-php-library#947]

**Comment by jmikola** [comment]
> When I use TLS, it works if I just specify the mongo host with single host name such as `'host' => 'dev2-ent-mongodb1'` (with replicaSet and CAfile etc). But it throw this error when I specify the host as a cluster such as: `'host' => 'dev2-ent-mongodb1,dev2-ent-mongodb2,dev2-ent-mongodb3'`.

Neither the PHP driver nor library take a `host` option, so it seems like you're using another library on top of the driver. To get to the root of this issue, please share two scripts using _just_ the driver and library that reproduces successful connection for a single host and error for multiple hosts.

For example:

 * Construct a [`MongoDB\Client`](https://www.mongodb.com/docs/php-library/current/reference/method/MongoDBClient__construct/) object with the appropriate connection string and options(s). Note that the full list of supported URI options are documented in [`MongoDB\Driver\Manager`](https://www.php.net/manual/en/mongodb-driver-manager.construct.php).
 * Either select a server (e.g. `$client->getManager()->selectServer()`) or issue a simple command (e.g. `$client->admin->command(['ping' => 1])`) to initialize the connection.

So please prepare two scripts (each with the appropriate connection options) and share their output when executing them through a CLI environment. I expect we'll see no output if `selectServer()` or `command()` succeeds and an uncaught exception otherwise. Once we have that, we can look at what the driver is doing directly.

---

The PHP driver's TLS is handled by whatever library is linked by libmongoc (and detected during compilation). This will most likely be OpenSSL, but the particular version of OpenSSL used may still differ from other applications (e.g. Mongo Studio 3T) if you happen to have multiple versions on your system. We can confirm exactly what libmongoc uses by running `ldd /path/to/mongodb.so` (where `/path/to/mongodb.so` is the compiled PHP extension). For instance, on my system:

```
$ ldd ~/phpc/modules/mongodb.so
	linux-vdso.so.1 (0x00007ffc2fd63000)
	libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007efc2b98c000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007efc2b970000)
	libzstd.so.1 => /usr/lib/x86_64-linux-gnu/libzstd.so.1 (0x00007efc2b8c7000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007efc2b8aa000)
	libssl.so.1.1 => /usr/lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007efc2b817000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007efc2b541000)
	libicuuc.so.66 => /usr/lib/x86_64-linux-gnu/libicuuc.so.66 (0x00007efc2b359000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc2b336000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc2b144000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007efc2af62000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007efc2af47000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007efc2af41000)
	libicudata.so.66 => /usr/lib/x86_64-linux-gnu/libicudata.so.66 (0x00007efc2947e000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007efc2932f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007efc2bbf0000)
```

The "IP address mismatch" error suggests that the certificate is actually being properly checked by OpenSSL and the root issue is likely an incorrect certificate configuration. You should also be able to verify the certificate directly using the [openssl verify](https://www.openssl.org/docs/man1.1.1/man1/openssl-verify.html) command and the `-verify_ip <ip>` and `-verify_hostname <hostname>` options. That would help you debug the certificate issue independent of the PHP driver (and MongoDB).

**Comment by HalleyUK** [comment]
Hi, thanks for the reply.

My script for single host mongo connection is as follows, by which I can
see a "success" output.

<?php
$loader = new \Phalcon\Loader();

$loader->registerNamespaces([
    'Phalcon' =>
'/var/www/mount/multi-tenant/enterprise-api/app/library/Phalcon',
]);

$loader->register();
$dsn = sprintf(
    'mongodb://%s:%s@%s', 'developer', 'DevPass123', 'dev2-ent-mongodb1'
);
$options = [
    'serverSelectionTryOnce' => FALSE, // it will try untill timeout
    'serverSelectionTimeoutMS' => 15000, // 15 sec
    'replicaSet' => 'dev2-ent-mongodb',
    'tls' => true,
    "tlsCAFile" =>
'/var/www/mount/multi-tenant/enterprise-api/app/files/cert/db/ca-cert.pem',
    "tlsAllowInvalidHostnames" => true,
];
$mongoDb = new \Phalcon\Db\Adapter\MongoDB\Client($dsn, $options);

$db =  $mongoDb->selectDatabase('dev_multi_tenant_enterprise2');
$db->command(['ping' => 1]);
echo "success".PHP_EOL;


My script for multiple hosts mongo connection is as follows, by which I can
see an error output.

<?php
$loader = new \Phalcon\Loader();

$loader->registerNamespaces([
    'Phalcon' =>
'/var/www/mount/multi-tenant/enterprise-api/app/library/Phalcon',
]);

$loader->register();
$dsn = sprintf(
    'mongodb://%s:%s@%s', 'developer', 'DevPass123',
'dev2-ent-mongodb1,dev2-ent-mongodb2,dev2-ent-mongodb3'
);
$options = [
    'serverSelectionTryOnce' => FALSE, // it will try untill timeout
    'serverSelectionTimeoutMS' => 15000, // 15 sec
    'replicaSet' => 'dev2-ent-mongodb',
    'tls' => true,
    "tlsCAFile" =>
'/var/www/mount/multi-tenant/enterprise-api/app/files/cert/db/ca-cert.pem',
//    "tlsAllowInvalidHostnames" => true,
];
$client = new \Phalcon\Db\Adapter\MongoDB\Client($dsn, $options);
$db =  $client->selectDatabase('dev_multi_tenant_enterprise2');
$db->command(['ping' => 1]);
echo "success".PHP_EOL;

the error output:
***@***.***:# php ./tls_cluster_hosts.php
PHP Fatal error:  Uncaught
MongoDB\Driver\Exception\ConnectionTimeoutException: No suitable servers
found: `serverselectiontimeoutms` timed out: [TLS handshake failed:
certificate verify failed (64): IP address mismatch calling hello on '
10.107.1.202:27017'] [TLS handshake failed: certificate verify failed (64):
IP address mismatch calling hello on '10.107.1.68:27017'] [TLS handshake
failed: certificate verify failed (64): IP address mismatch calling hello
on '10.107.1.135:27017'] in
/var/www/mount/multi-tenant/enterprise-api/app/library/Phalcon/Db/Adapter/MongoDB/Database.php:179
Stack trace:
#0
/var/www/mount/multi-tenant/enterprise-api/app/library/Phalcon/Db/Adapter/MongoDB/Database.php(179):
MongoDB\Driver\Manager->selectServer(Object(MongoDB\Driver\ReadPreference))
#1
/var/www/mount/multi-tenant/enterprise-api/app/files/cert/db/tls_cluster_hosts.php(22):
Phalcon\Db\Adapter\MongoDB\Database->command(Array)
#2 {main}
  thrown in
/var/www/mount/multi-tenant/enterprise-api/app/library/Phalcon/Db/Adapter/MongoDB/Database.php
on line 179

Your library code is at path
/var/www/mount/multi-tenant/enterprise-api/app/library/Phalcon/Db/Adapter/MongDB
 in
my case.
I don't use a client side certificate in this case. Just a CA. With Studio
3T, the multiple hosts option works as in attached pictures.
[image: image.png][image: image.png]
My environment is PHP 7.3.33-1+ubuntu20.04.1 in docker.

The mongo.so output as requested:
***@***.***: # ldd /usr/lib/php/20180731/mongodb.so
        linux-vdso.so.1 (0x00007ffd6d92f000)
        libsnappy.so.1 => /lib/x86_64-linux-gnu/libsnappy.so.1
(0x00007f91ee8c6000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f91ee8aa000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1
(0x00007f91ee801000)
        libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2
(0x00007f91ee7e4000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1
(0x00007f91ee751000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1
(0x00007f91ee47b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0
(0x00007f91ee456000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f91ee264000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6
(0x00007f91ee082000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1
(0x00007f91ee067000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f91ee061000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f91eea5f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f91edf12000)

Regards,
Halley

**Comment by HalleyUK** [comment]
Just to update one more piece of information: If I set the replicaSet in the connection, no matter I use single host or cluster hosts, it always fails. If I don't use the  replicaSet, but use single host, it works. So probably it has something to do with how the lib check the IP address when replicaSet is used.

**Comment by jmikola** [comment]
Note: I restored the original bug report contents since this may be relevant to other users that come across the same error message down the line.
